### ISSUE TITLE
FR:  Standardize on Fully Qualified module names

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1003]
##### SUMMARY
The roles are a mix of fully qualified module names and the older style.  Need to go through and standardize on the newer style.  Also, there are a number of places where deprecated modules (i.e. include) are used that need to be updated.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Various roles and molecule

**Comment by WebSpider** [comment]
Good first issue it says. Well, let's try it :)
