### ISSUE TITLE
Refactor zabbix_mediatype to match other modules

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#101]
##### SUMMARY
Currently zabbix_mediatype is structured around only functions while other modules use classes. This makes it hard to streamline the module - so at least a quick-and-dirty refactor to class usage would help.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_mediatype

##### ADDITIONAL INFORMATION
Just an follow up on my work on #97

**Comment by rockaut** [comment]
I'm already working on this - PR inbound.

**Comment by rockaut** [comment]
I see that there are so many changes incoming from other thing. I'll do the PR if it has stabilized later on.

**Comment by D3DeFi** [comment]
> I see that there are so many changes incoming from other thing. I'll do the PR if it has stabilized later on.

sorry about that and thank you for this ideas and their implementation. Hopefully @sky-joker can look at the #82 soon so you can continue with this work

**Comment by rockaut** [comment]
Nothing to worry and no stress. It was my fault to not have a better look at the open issues.
Will just rebase and redo after merge.

**Comment by D3DeFi** [comment]
closed by #153
