### ISSUE TITLE
Zabbix_inventory for zabbix 5.0 login failed 

### ISSUE THREAD

**Issue by ops4cloud** [ansible-collections/community.zabbix#1016]
##### SUMMARY
Since release 2.0.0 of the collection, is no way to login into zabbix 5.0 for **zabbix_inventory** now in use :

**zabbix_inventory line +397**

```json
{
   "username": XXXXXX
   "password": XXXXXX
}
```

and in older version of collection 1.9.3 it's:

```json
{
  "user": XXXXXX
  "password": XXXXXX
}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- **zabbix_inventory.py**

##### ANSIBLE VERSION

ansible [core 2.12.10]

**Comment by pyrodie18** [comment]
As noted in the release notes, 2.0 depreciated all support for anything < Zabbix 6.0
