### ISSUE TITLE
zabbix_agent role must be run as root. /Debian

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/community.zabbix#1021]
##### SUMMARY

Running the zabbix_agent role on a Debian-based distribution that is marked by the role as "old" triggers the execution of one task where it is very obvious that a `become: true` instruction is missing

https://github.com/ansible-collections/community.zabbix/blob/4d96320bc0a9db5d5dbfe5c5c9d463a1d70c6a83/roles/zabbix_agent/tasks/Debian.yml#L52
is an obvious task where `become: true` is missing

in other roles, the equivalent tasks were patched in #1010, which fixed #922

##### ISSUE TYPE
- Bug Report

##### EXPECTED RESULTS

role works

##### ACTUAL RESULTS
```
[...]
TASK [community.zabbix.zabbix_agent : Debian | Create /etc/apt/keyrings/ on older versions] **************************
fatal: [mydebianhost]: FAILED! => changed=false
  msg: 'There was an issue creating /etc/apt/keyrings as requested: [Errno 13] Permission denied: b''/etc/apt/keyrings'''
  path: /etc/apt/keyrings/
```

**Comment by pyrodie18** [comment]
Sorry that we missed an obvious location where the fix was obvious.
