### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1023]
We've pushed a few bug fixes and several minor changes.  Probably about time to cut another release.

@BGmot  and @D3DeFi  is there anything else you'd like to see closed out before we cut it?  I want to finish up #1005 (started on it but have a few tests failing that I need to fix).  Maybe also #1002 and #1001 if I have time.  I'm thinking cut the release this coming weekend if that works for you guys have you have the cycles to do some last-minute reviews?

**Comment by D3DeFi** [comment]
Folks, very good job with the changes and repository so far! I am sorry that I am of no use, but I am having trouble dedicating any time at all to this community. Ansible and Zabbix both are something that am not using very much lately and have to focus elsewhere.

That said, I have no plans or requirements on what to include or not in the next releases

**Comment by BGmot** [comment]
Unfortunately currently I can contribute only on weekends. Let's finish the issues you mentioned and release. I am not an expert in Debian APT sources but I can try to tackle these issues.

**Comment by pyrodie18** [comment]
OK, so I never got around to #1001.  I would like to have gotten that included but my work schedule has officially exploded and while I think this is going to be straightforward to solve, I'd rather not let this release wait any longer.  I will be putting in PRs momentarily for #1021 and #1014.  I have a PR that is good to go for #1005 if you can go ahead and take a peak and approve that.

**Comment by BGmot** [comment]
Reviewed all and approved. Thanks!

**Comment by pyrodie18** [comment]
Merge and release cut complete....Thanks all!

**Comment by BGmot** [comment]
Great job @pyrodie18 ! Thanks!
