### ISSUE TITLE
`type` parameter of zabbix_user

### ISSUE THREAD

**Issue by markuman** [ansible-collections/community.zabbix#1040]
With community.zabbix 2.0.0, the `type` parameter of `zabbix_user` was removed.  
https://github.com/ansible-collections/community.zabbix/blob/1.9.3/plugins/modules/zabbix_user.py#L183-L191

>             - I(type) can be used when Zabbix version is 5.0 or lower.

How ever, the `type` parameter can be used in 6.0 LTS. And now, it's not setable anymore.  

Any words about this?

**Comment by markuman** [comment]
The example section of the documentation still mentioned the parameter: https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_user.py#L258

**Comment by pyrodie18** [comment]
Maybe I'm missing it but there is no mention of a `type` attribute in the 6.0 Zabbix API documentation (https://www.zabbix.com/documentation/6.0/en/manual/api/reference/user/object).  If I'm off, please point it out.

**Comment by richlv** [comment]
> The example section of the documentation still mentioned the parameter: https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_user.py#L258

Now at https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_user.py#L265 .
I guess the intent is to use "role" there?
