### ISSUE TITLE
Apache vhost bug on "zabix_web" role 

### ISSUE THREAD

**Issue by nat-0205** [ansible-collections/community.zabbix#1051]
##### SUMMARY

Hi, I've noticed that when the var "zabbix_web_create_vhost" is set to false, the "Apache | Enable Site (Debian Only)" module is executed in "zabbix_web/tasks/apache.yml", which is a module that should only be executed if the "zabbix_web_create_vhost" variable is set to true, which gives me an error when the role is executed.

I found a solution by modifying part of the module by adding ""and zabbix_web_create_vhost"" to the "when" condition which worked very well.

- name: "Apache | Enable Site (Debian Only)"
  file:
    src: "{{ zabbix_web_vhost_location }}"
    dest: /etc/apache2/sites-enabled/zabbix.conf
    state: link
    owner: "{{ zabbix_web_user }}"
    group: "{{ zabbix_web_group }}"
    mode: 0644
  become: true
  when: ansible_os_family == "Debian" and zabbix_web_create_vhost
  tags:
    - config

##### ISSUE TYPE

- Bug Report
- Bug solution

##### COMPONENT NAME

- ROLE : zabbix_web
- TASK: apache.yml
- MODULE: Apache | Enable Site (Debian Only) 

##### ANSIBLE VERSION

``ansible [core 2.14.1]
  python version = 3.10.6 [GCC 11.3.0] 
  jinja version = 3.1.2
```

##### OS / ENVIRONMENT / Zabbix Version

- OS version : Ubuntu 22.04.2 LTS

**Comment by pyrodie18** [comment]
Great catch @nat-0205 , I'd encourage you to actually create the fix and put a PR in.
