### ISSUE TITLE
Using multiple Include in zabbix_agent2.conf

### ISSUE THREAD

**Issue by aaujon** [ansible-collections/community.zabbix#1056]
Hi,

I'm trying to deploy zabbix-agent2 but I'm struggling using zabbix_agent2_include.
I'm deploying userparameters in zabbix-agent2.d/ and zabbix plugins are located (using ubuntu package) in zabbix-agent2.d/plugins.d/
In zabbix-agent role I can only define one path for the include parameter, if I choose /etc/zabbix/zabbix-agent2.d, my userparamerters files are loaded but the postgresql plugin isn't, so I can't use it.
One way to do that is to use 2 Include directives in zabbix-agent2.conf, for example :
```
Include=/etc/zabbix/zabbix_agent2.d/
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf 
```

I can't find a way to do it using current role, Am I missing something or should zabbix_agent2_include be a list ?

Thanks !

**Comment by Thulium-Drake** [comment]
I was just working on the same problem ;-)

What you could do in the mean time is create a include file in ```/etc/zabbix/zabbix_agent2.d/include_plugins.d.conf``` with the following:

```
Include=/etc/zabbix/zabbix_agent2.d/plugins.d
```

This fixed it on my end :)

**Comment by aaujon** [comment]
Thanks for the MR ! I will wait for a new release :)

**Comment by Thulium-Drake** [comment]
@pyrodie18 @BGmot It seems that with c2a32d5 this was lost as it was not added to the new agent.conf.j2
