### ISSUE TITLE
Question:  Remove Upgrade.md?

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1062]
##### SUMMARY
As noted in #1048  the [UPGRADE docs](https://github.com/ansible-collections/community.zabbix/blob/main/docs/UPGRADE.md) hasn't been updated in over two years, and doesn't accurate reflect any of the upgrade instructions.  I know I for one didn't even think about this document as we've pushed changes.  Has it outlived its usefulness and should be removed?

##### ISSUE TYPE
- Feature Idea

**Comment by dj-wasabi** [comment]
I would get rid of it. My 2 cents. 😄

**Comment by BGmot** [comment]
Let's remove.

**Comment by mathieumd** [comment]
Still linked from the [README.md](https://github.com/ansible-collections/community.zabbix/tree/main#upgrading-collection)

Providing some hints to help smooth upgrade from version to version, for those of us who don't track changes, would still be a good idea, though...
