### ISSUE TITLE
QUESTION:  Major Release for 7.0 Release?

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1069]
Zabbix should be releasing 7.0 in the next couple of months.  Do we want drop support for 6.2/4 at that time or keep them in there for right now?

**Comment by pyrodie18** [comment]
I'm voting with major release and drop support for the 6.X versions (other than 6.0).  Also, retire Debian 1804, Ansible 2.12 and 2.13 (retires in Nov)

**Comment by markuman** [comment]
> I'm voting with major release and drop support for the 6.X versions (other than 6.0). Also, retire Debian 1804, Ansible 2.12 and 2.13 (retires in Nov)

+1

if it's EOL, the collection should follow https://endoflife.date/zabbix
