### ISSUE TITLE
Zabbix-Web 6.4 required PHP 7.4 or higher

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-collections/community.zabbix#1088]
##### SUMMARY

Zabbix 6.4 requires PHP 7.4.0 or higher in order to work, however, on RHEL8 the default Appstream module that is enabled is 7.2. Which is insufficient. The role however does not fix the module that is enabled in order to have a working end situation. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_web
##### ANSIBLE VERSION

```paste below
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 6.4
RHEL 8.8

##### STEPS TO REPRODUCE

Run the zabbix_web role against a RHEL8 target with Zabbix 6.4 as the desired version.

```yaml

```

##### EXPECTED RESULTS

It to disable the default Appstream module and enable 7.4 or 8.0.

##### ACTUAL RESULTS

It installs just fine, but Zabbix WebUI does not work due to the too old PHP version

```paste below

```

**Comment by pyrodie18** [comment]
The web role doesn't install PHP at all.  It depends on you installing it yourself prior to running the role.

**Comment by Thulium-Drake** [comment]
That's not entirely true, one of the tasks installs ```zabbix-frontend-php```, but it doesn't take in account the minimum required version of PHP.

This effectively breaks the role on RHEL8 for Zabbix 6.2+ (as they bumped the required version of PHP in 6.4).
