### ISSUE TITLE
Role zabbix-proxy wrongly creates sqlite3 DB file

### ISSUE THREAD

**Issue by KarlikB** [ansible-collections/community.zabbix#1093]
##### SUMMARY
Zabbix-proxy role tries to generate sqlite3 DB file but resulting file is not readable by proxy.
I tested it on zabbix 6.4
Zabbix-proxy since at least 6.0 (do not know if also in previous version) generates DB file during start if it does not exists yet.
Easiest fix may be simply remove tasks "Sqlite3 | Handle Compressed Schema File" and "Sqlite3 | Importing schema file" in https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_proxy/tasks/sqlite3.yml
As a workaround I disabled DB cretion by flag zabbix_proxy_database_creation: false, created DB direstory manually and everything works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
role zabbix-proxy in sqlite3 mode

##### ANSIBLE VERSION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version
RHEL9, Zabbix 6.4

##### STEPS TO REPRODUCE
Install zabbix-proxy sqlite3 with enabled flag zabbix_proxy_database_creation: true

##### EXPECTED RESULTS
Zabbix-proxy role do not try to create sqlite3 DB file and let proxy binary to handle it.

**Comment by pyrodie18** [comment]
To make sure I understand what you're saying.  By default as of at least 6.0, if I start proxy and there's no database built out (at least with SQLite), Proxy will take care of building it within the database engine itself?  Assuming that's correct though, is there a problem caused by populating the DB as part of the role?

**Comment by KarlikB** [comment]
Exactly, zabbix proxy creates SQLite db file itself if not exist durinf proxy start.

My workaround is:

set flag to prevent DB handling by role (default is true)
zabbix_proxy_database_creation: false

Create directory necessary for DB file

- name: Zabbix proxy DB directory
  ansible.builtin.file:
    path: "/var/lib/zabbix"
    state: directory
    owner: zabbix
    group: zabbix
    mode: "0700"
    seuser: system_u
    setype: zabbix_var_lib_t
  become: true
  register: zabbixproxydbdir

Modify config file to point DBName=/var/lib/zabbix/zabbix_proxy.db

Start proxy, there is snippet from proxy logfile that realizes non existence DB file and creates it.
` 15065:20230922:084907.634 using configuration file: /etc/zabbix/zabbix_proxy.conf
 15065:20230922:084907.635 cannot open database file "/var/lib/zabbix/zabbix_proxy.db": [2] No such file or directory
 15065:20230922:084907.635 creating database ...
 15065:20230922:084911.205 slow query: 3.568965 sec, "CREATE TABLE role (
roleid bigint  NOT NULL,
name varchar(255) DEFAULT '' NOT NULL,
type integer DEFAULT '0' NOT NULL,
readonly integer DEFAULT '0' NOT NULL,
...`

And proxy works well.

I tried

**Comment by KarlikB** [comment]
I tested the behaviour and it is weird.
The directory /var/lib/zabbix is not created by role at all, so DB file cannot be generated/used.

I will perform some more tests.

**Comment by KarlikB** [comment]
Sorry, my bad.
It was playbook written by colleague that uses only mechanism to work with zabbix API but package installation and configuration has been done custom way.

Sorry and thanks for your time.
