### ISSUE TITLE
Module Dev Help

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1114]
@BGmot, I'm trying to update the modules for 7.0 and could use some help.  I know python just fine but haven't had a ton of experience with modules.  Right now working on the proxy one and trying to debug it.  I'm trying to do it through vs code following https://medium.com/@tushe_33516/guide-to-writing-and-debugging-ansible-modules-in-vscode-a-nearly-perfect-setup-ad54024a466a but have problems feeding the httpapi the information needed to connect.  Do you have a better method?

Troy

**Comment by BGmot** [comment]
Hi @pyrodie18, isn't it a bit early to develop for 7.0? It's still several months away.
Anyway I just use vim in my console and run integration tests to see whether I get what I expect to get from the module. If it fails with exception then you see where it failed, if it does not provide good test result (you expect one thing but it returns another one) then you fix your module logic. I can provide detailed instructions if you want of how I set up my test environment (you need a running Zabbix too and running Zabbix in docker containers is part of integration tests too). I am an 'old school boy' and quite happy with just terminal without any fancy VS code/plugins.
Anyway your article looks interesting and I'll probably take a deeper look some time later.

**Comment by pyrodie18** [comment]
Several months.  According to their roadmap, it should have been out like 2 months ago.  It's available in beta currently.

**Comment by BGmot** [comment]
Don't trust their roadmap. But if you feel like then by all means do 7.0.

**Comment by pyrodie18** [comment]
lol ok...noted

**Comment by BGmot** [comment]
Here is how I do all the testing locally. Let's say you want to test against Ansible 2.14 and python 3.10. I am running this on Ubuntu 22.
Prepare environment:
```
sudo apt install python3.10
sudo apt install python3-virtualenv
virtualenv -p python3.10 ~/env_py310_ans214
source ~/env_py310_ans214/bin/activate
python3 -m pip install ansible-core==2.14
# To install develop branch of Ansible use following
# python3 -m pip install https://github.com/ansible/ansible/archive/devel.tar.gz
python3 -m pip install pycodestyle rstcheck zabbix_api voluptuous flake8 tox
```

Clone your forked repo (in my case it's git@github.com:BGmot/community.zabbix.git):
```
mkdkir -p ~/.ansible/collections/ansible_collections/community/zabbix
cd ~/.ansible/collections/ansible_collections/community/zabbix
git clone git@github.com:BGmot/community.zabbix.git .
git remote add upstream https://github.com/ansible-collections/community.zabbix.git
git fetch upstream
```

Spin up Zabbix containers with the version you want to test against:
```
export zabbix_version=6.0
docker-compose up -d
```

Now you can run all the tests:
```
flake8 plugins/
ansible-test sanity -v --color --exclude molecule/ --python 3.10
# Following will test all the modules
ansible-test integration -v --color --diff --python 3.10 --requirements --coverage
# You can test only one module (the one you are now working on) by specifying module name
# ansible-test integration -v --color --diff --python 3.10 --requirements --coverage test_zabbix_user
tox -elinters-py3 -vv
# You can test whether documentation section is ok for specific module
ansible-doc -t module community.zabbix.zabbix_user
python3.9 -m pycodestyle --max-line-length 160 --config /dev/null --ignore E402,E741,W503,W504 plugins/modules/
ansible-test sanity --test validate-modules
```

If all the tests pass you can push to GitHub so all the tests will be executed against all the versions in our matrix.

Don't forget to destroy containers:
```
docker-compose down
```
Hope that helps.
