### ISSUE TITLE
API connection never made from the Zabbix server

### ISSUE THREAD

**Issue by richlv** [ansible-collections/community.zabbix#1129]
##### SUMMARY
Used older versions of the collection, attempting to move to the most recent one - git checkout from yesterday.
Ansible core 2.11.12.

Trying to use Zabbix modules that should be executed from the Zabbix server itself. Running the playbook against the Zabbix server, the action always seems to be executed from the Ansible controller instead.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_group

##### ANSIBLE VERSION
```
ansible [core 2.11.12] 
  config file = /opt/ansible/config/ansible-config-host.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv-ansible/lib/python3.6/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/venv-ansible/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION
```
DEFAULT_FORKS(/opt/ansible/config/ansible-config-host.cfg) = 100
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config-host.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/config/ansible-config-host.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
RHEL 8.2 on the Ansible controller.

##### STEPS TO REPRODUCE
```yaml
- name: Set other API access detail
  set_fact:
    ansible_network_os: community.zabbix.zabbix
    ansible_host: "{{inventory_hostname}}"
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_user: username
    ansible_httpapi_pass: "{{password}}"

- name: Create Zabbix host groups
  community.zabbix.zabbix_group:
    state: present
    host_groups: "{{hostgroups_global + hostgroups}}"
  delegate_to: "{{inventory_hostname}}"
```

##### EXPECTED RESULTS
Commands run from the delegate_to host.

##### ACTUAL RESULTS
Commands run from the Ansible controller.

```paste below
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Loading collection ansible.netcommon from /opt/venv-ansible/lib/python3.6/site-packages/ansible_collections/ansible/netcommon
<zabbix.server> attempting to start connection
<zabbix.server> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /opt/venv-ansible/bin/ansible-connection
<zabbix.server> local domain socket does not exist, starting it
<zabbix.server> control socket path is /home/user/.ansible/pc/f6043cd9e6
<zabbix.server> redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<zabbix.server> Loading collection ansible.netcommon from /opt/venv-ansible/lib/python3.6/site-packages/ansible_collections/ansible/netcommon
<zabbix.server> Loading collection community.zabbix from /home/user/collections-dev/collections/ansible_collections/community/zabbix
<zabbix.server> local domain socket listeners started successfully
<zabbix.server> loaded API plugin ansible_collections.community.zabbix.plugins.httpapi.zabbix from path /home/user/collections-dev/collections/ansible_collections/community/zabbix/plugins/httpapi/zabbix.py for platform type community.zabbix.zabbix
<zabbix.server> 
<zabbix.server> local domain socket path is /home/user/.ansible/pc/f6043cd9e6
<zabbix.server> ESTABLISH LOCAL CONNECTION FOR USER: user
<zabbix.server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-local-2669003z0098bu0 `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149 `" && echo ansible-tmp-1700008186.181238-2669079-182825811348149="` echo /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149 `" ) && sleep 0'
Using module file /home/user/collections-dev/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py
<zabbix.server> PUT /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/tmpz2_aqq0w TO /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149/AnsiballZ_zabbix_group.py
<zabbix.server> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149/ /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149/AnsiballZ_zabbix_group.py && sleep 0'
<zabbix.server> EXEC /bin/sh -c '/opt/venv-ansible/bin/python3.6 /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149/AnsiballZ_zabbix_group.py && sleep 0'

<zabbix.server> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-local-2669003z0098bu0/ansible-tmp-1700008186.181238-2669079-182825811348149/ > /dev/null 2>&1 && sleep 0'
```

**Comment by BGmot** [comment]
First of all you need to choose either `ansible_host` or `delegate_to` (I prefer `delegate_to`).
`inventory_hostname` in both cases needs to be your Zabbix server host.
Secondly what do you mean by `Commands run from the Ansible controller.`, this is how httpapi connection plugin works - first it creates a temporary socket and "tunnels" HTTP(s) traffic to Zabbix server through this socket.

Anyway what is this issue about? something does not work?

**Comment by richlv** [comment]
Thank you for the clarification on the parameters - used one initially, added more when that didn't work :)
The Zabbix API is not reachable directly from the Ansible controller. Previous versions of the collection worked by making a connection to the target host and running the API operations from there.
With the latest version, this connection is attempted from the Ansible controller instead.

**Comment by BGmot** [comment]
As described in documentation https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_group_module.html#examples Ansible uses `ansible_user` and `ansible_httpapi_pass` as username/password or token `ansible_zabbix_auth_key` to authenticate at Zabbix REST API, `ansible_ssh_user` has no play here.

In regards to execution, yes in previous versions of this collection (1.9) you could execute from remote host - Ansible would make SSH connection to remote host and execute modules there but you would need to have zabbixpy module installed on this remote host.

With current version of collection Zabbix server is treated as ordinary remote host from Ansible inventory but instead of SSH a connection to this host is made via HTTP(S). We can't change this behaviour as the core of httpapi connection module is provided by Ansible itself.

Hope this helps.

**Comment by richlv** [comment]
Thanks, I was hoping `ansible_ssh_user` would still be used for the SSH connection, and the API connection would be made from the remote host.
Does this mean that there is no way to make the API connection from the remote host with the latest version?

**Comment by BGmot** [comment]
>  Does this mean that there is no way to make the API connection from the remote host with the latest version?
Yes, it does.

**Comment by richlv** [comment]
Thank you so much for the confirmation.
Perhaps it would be worth explicitly mentioning this in https://galaxy.ansible.com/ui/repo/published/community/zabbix/docs/ or a similar place?
Spent quite a lot of time debugging why the connections are not made like they were previously, a note might help somebody else :)

**Comment by konstantin-kornienko** [comment]
> > Does this mean that there is no way to make the API connection from the remote host with the latest version?
> 
> Yes, it does.

It breaks multiple use case scenarios, like using bastion hosts and so on. Sad.

**Comment by BGmot** [comment]
> > > Does this mean that there is no way to make the API connection from the remote host with the latest version?
> > 
> > 
> > Yes, it does.
> 
> It breaks multiple use case scenarios, like using bastion hosts and so on. Sad.
Can you please clarify what scenario it breaks?

**Comment by richlv** [comment]
Not the previous poster, but one scenario - the environment where the Zabbix frontend resides is accessible via Ansible connection only. With that becoming impossible, firewall changes required to allow direct Ansible controller -> API connectivity.

**Comment by BGmot** [comment]
If by Ansible connection you mean SSH then yes.
What we do here is the way practically all well known collections that use any REST API do.
If you have valid use case then security team should review and just open HTTPS traffic, I don't see any problems here.

**Comment by BGmot** [comment]
That is interesting... Because when we used third party plugin zabbix-api it also executed all actions (HTTP API calls) from the Ansible controller.
Can you please share the code you use with 1.8.0 that would execute these calls from different (remote) host?

**Comment by richlv** [comment]
I do not have access to the previous code, but it followed the general practice of running the task on the corresponding host.
It could have been the Zabbix server (connecting to localhost for the API even), or a delegated host. Whichever it was, it had to have the zabbix-api lib installed.

**Comment by BGmot** [comment]
Ok, now I understand. If "bastion" has zabbix-api then yes, sure. But decision was made to switch to httpapi connection plugin which is part of Ansible so what you used to do is now impossible.
