### ISSUE TITLE
Some module dependencies not documented

### ISSUE THREAD

**Issue by richlv** [ansible-collections/community.zabbix#1130]
##### SUMMARY
It seems that some module dependencies are not documented - if I've missed something, very sorry about that.

Checked https://galaxy.ansible.com/ui/repo/published/community/zabbix/docs/ , https://github.com/ansible-collections/community.zabbix/blob/main/README.md , https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_mediatype_module.html#ansible-collections-community-zabbix-zabbix-mediatype-module .

This might be relevant for multiple modules:

https://github.com/search?q=repo%3Aansible-collections%2Fcommunity.zabbix+ansible.module_utils&type=code

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Documentation, possibly

##### ANSIBLE VERSION
```
ansible [core 2.11.12] 
  config file = /opt/ansible/config/ansible-config-host.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv-ansible/lib/python3.6/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/venv-ansible/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 3.0.1
  libyaml = True
```

##### CONFIGURATION
```
DEFAULT_FORKS(/opt/ansible/config/ansible-config-host.cfg) = 100
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config-host.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/config/ansible-config-host.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
RHEL 8.2 on the Ansible controller.

##### STEPS TO REPRODUCE
Use the zabbix_mediatype module.

##### EXPECTED RESULTS
Works, when installed according to the documentation.

##### ACTUAL RESULTS
Fails:

```
fatal: [host]: FAILED! => {"msg": "Could not find imported module support code for ansible_collections.community.zabbix.plugins.modules.zabbix_mediatype.  Looked for (['ansible.module_utils.compat.version.LooseVersion', 'ansible.module_utils.compat.version'])"}
```

**Comment by richlv** [comment]
Although this could also be some Ansible/Python version conflict, https://github.com/ansible/ansible/issues/73831 .

**Comment by pyrodie18** [comment]
The mediatype module requires python >= 3.9  Also ansible-core 2.11 has been EOL for over a year now.   I'd suggest upgrading both and see if that works.

**Comment by richlv** [comment]
Ahhh, I see... missed the Python 3.9 part, wasn't expecting that.
Thank you so much for spotting that, must be the cause. Perhaps a more explicit version warning would help - but if that's complicated, hopefully this issue will steer people in the correct direction :)
