### ISSUE TITLE
Inconsistent macro support in zabbix_host and zabbix_hostmacro

### ISSUE THREAD

**Issue by richlv** [ansible-collections/community.zabbix#114]
##### SUMMARY
Macro support between zabbix_host and zabbix_hostmacro is inconsistent, including a bug in zabbix_host and missing features in zabbix_hostmacro.
Listing these in a single issue, please let me know if they should be split out.

a) zabbix_host unconditionally uppercases all macro names, breaking macro context - zabbix_hostmacro has additional handling for macro context.
b) zabbix_host supports secret macros and macro description, while zabbix_hostmacro does not.

There might be other differences, so far only spotted these.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
devel

**Comment by richlv** [comment]
No clue whether modules can reuse code - like macro name validation and mangling here. Perhaps that is easier to maintain longterm, compared to duplicate code in each module.

**Comment by D3DeFi** [comment]
Hi @richlv and thank you for the issue.

I recall thinking about zabbix_hostmacro when I was updating zabbix_host module, but somehow forgot to both at least open an issue or make a fix for it.

As for the code reuse, we've already started doing some small steps towards it (see #107). Maybe fix for user macros won't be implemented that way right now, but will surely be reworked such in the future.

**Comment by D3DeFi** [comment]
Btw, since you are probably using secret user macros, does it make sense to you have are they handled in `zabbix_host` module? API is not returning `value` for the macro so we have no way of knowing whether user has updated it. There were two possibilities from my point of view at the time:
- always update macros of type secret - no idempotency
- ask user to update something else (description) alongside the value so the module knows that it should issue an update

**Comment by richlv** [comment]
Hi, thank you for the response and all the great improvements.
Sorry, not using secret macros yet - still on Zabbix 4.0.
While updating the description is hackish, treating anything with a secret macro as always changed does not seem good either.
Keeping the current behaviour seems like the best approach, until/unless somebody comes up with a better idea.

**Comment by richlv** [comment]
Would a copy-paste of the context handling from the macro module to the host module be acceptable for now?
I could try a crude pull request if so.

**Comment by D3DeFi** [comment]
> Would a copy-paste of the context handling from the macro module to the host module be acceptable for now?
> 
> I could try a crude pull request if so.

It should be for now. I am sorry for late replies and no implementation yet, haven't had that much time lately

**Comment by richlv** [comment]
No worries and thank you for all the great modules and help :)
I've submitted a crude pull request which only deals with macro context. Kept normalize_macro_name() as-is from zabbix_hostmacro, might be a tiny bit easier to merge later.

**Comment by rockaut** [comment]
I have to look into secret macros too. I guess best way would be to implement it in a way the module can be used with and without the secret portion:
- used without: module reports changed=True/False accordingly
- used with: module will always report changed=True
collection.grafana.grafana_datasource is implemented this way for example.

This way a user can implement two play tasks: first one will set the non-secrets, second one the secrets.
To be true I haven't looked into the API yet if it would work this way.

**Comment by D3DeFi** [comment]
The first one works now unless user provides "type: secret" to one of the macros.

Second one is just a matter of how we document it. I've previously decided to go with hackish solution of updating description, but this can easily be changed in the code to always do an update of every "type: secret" macros.

Only difference in api is that "zbx.hostmacro.get" does not return any "value" for secret macros.

**Comment by D3DeFi** [comment]
zabbix_hostmacro now supports macro types #456

this issue has become stale and should be fixed already so I am closing it
