### ISSUE TITLE
centoc7 x zabbix.proxy combination deployment is failed. because MariaDB 10.8 is dead(EOS) and repo link return 404.

### ISSUE THREAD

**Issue by miettal** [ansible-collections/community.zabbix#1148]
##### SUMMARY

centoc7 x zabbix.proxy combination deployment is failed. because MariaDB 10.8 is dead(EOS) and repo link return 404.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_proxy role.

##### ANSIBLE VERSION
https://github.com/ansible-collections/community.zabbix/actions/runs/7307787096/job/19913806734?pr=1145#step:7:228

##### CONFIGURATION
https://github.com/ansible-collections/community.zabbix/actions/runs/7307787096/job/19913806734?pr=1145#step:7:228

##### OS / ENVIRONMENT / Zabbix Version
https://github.com/ansible-collections/community.zabbix/actions/runs/7307787096/job/19913806734?pr=1145#step:7:228

##### STEPS TO REPRODUCE

https://github.com/ansible-collections/community.zabbix/actions/runs/7307787096/job/19913806734?pr=1145#step:7:228

##### EXPECTED RESULTS
success

##### ACTUAL RESULTS
failue
https://github.com/ansible-collections/community.zabbix/actions/runs/7307787096/job/19913806734?pr=1145#step:7:228

**Comment by BGmot** [comment]
@miettal would you able to submit a PR to fix this?

**Comment by BGmot** [comment]
Running the test in my local dev environment I get a success. Trying to find out what is going on.

**Comment by pyrodie18** [comment]
Not sure how you would succeed. I just went to the repo and its definitely gone.  I'm working a PR right now that will update it to 10.11.  I think we go ahead and finish killing off Centos 7 entirely with 3.0 reguardless of when we put it out.  Its EOL in 6 months anyway.

**Comment by BGmot** [comment]
This is how it worked in my local dev environment:
```
{
    "attempts": 1,
    "changed": true,
    "msg": "",
    "rc": 0,
    "results": [
        "Installed: python3-cryptography-3.2.1-6.el8.aarch64",
        "Installed: libedit-3.1-23.20170329cvs.el8.aarch64",
        "Installed: python3-PyMySQL-0.10.1-2.module+el8.4.0+597+ddf0ddea.noarch",
        "Installed: mysql-8.0.32-1.module+el8.8.0+1283+4b88a3a8.0.1.aarch64",
        "Installed: mysql-common-8.0.32-1.module+el8.8.0+1283+4b88a3a8.0.1.aarch64",
        "Installed: python3-ply-3.9-9.el8.noarch",
        "Installed: python3-pycparser-2.14-14.el8.noarch",
        "Installed: python3-cffi-1.11.5-6.el8.aarch64"
    ]
}
```
