### ISSUE TITLE
KeyError: 'proxy_hostid'  community.zabbix.zabbix_host

### ISSUE THREAD

**Issue by Midas1989** [ansible-collections/community.zabbix#1163]
When you have subgroups in zabbix
![image](https://github.com/ansible-collections/community.zabbix/assets/6429642/e667264a-88ac-49c1-b9bb-a9f66d681038)

You become an error when you override a host information

TASK [Remove all groups from the host] *****************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'proxy_hostid'
fatal: [server1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/users/ata0258253/.ansible/tmp/ansible-local-974097red6ju3e/ansible-tmp-1705068150.160186-976173-241943272178657/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/users/ata0258253/.ansible/tmp/ansible-local-974097red6ju3e/ansible-tmp-1705068150.160186-976173-241943272178657/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/users/ata0258253/.ansible/tmp/ansible-local-974097red6ju3e/ansible-tmp-1705068150.160186-976173-241943272178657/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_vtcm06jk/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1250, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_vtcm06jk/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1093, in main\nKeyError: 'proxy_hostid'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'proxy_hostid'

**Comment by BGmot** [comment]
Please submit Ansible code you used to get this error.

**Comment by Midas1989** [comment]
THis one

    - name: Remove all groups from the host
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_host: "{{ zabbix_url }}"
        ansible_zabbix_url_path: ""
      community.zabbix.zabbix_host:
        host_name: "{{ ansible_facts['hostname'] }}"
        host_groups: []


or this one

    - name: Create a new host or rewrite an existing host's info
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_host: "{{ zabbix_url }}"
        ansible_zabbix_url_path: ""
      become: false
      community.zabbix.zabbix_host:
        host_name: "{{ ansible_facts['hostname'] }}"
        host_groups: "{{ hostgroups }}"
        link_templates: "{{ ansible_facts['link_templates'] }}"
        status: enabled
        state: present
        inventory_mode: manual
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_facts['default_ipv4']['address'] }}"
            dns: "{{ ansible_facts['fqdn'] }}"
            port: "10050"
        proxy: "{{ zabbix_proxy }}"
        description: "{{ ansible_facts['ansible_local']['DESC'] }}"
        tags: "{{ combined_tags }}"
        tls_accept: 2
        tls_connect: 2
        tls_psk: "98b0a6e37e59a2991232d5ce8b10e7440b33c25c368ae69b085b32ce8309ddcc"
        tls_psk_identity: "Zabbix-pki-1"
      delegate_to: localhost


both have the same problem, when in the existing host object store the following groups
![image](https://github.com/ansible-collections/community.zabbix/assets/6429642/811e1dc9-7eff-4f0d-b14d-f7a5adeeb101)

When the existing host have this groups
![image](https://github.com/ansible-collections/community.zabbix/assets/6429642/14c63f70-885e-4afb-8435-5400d62350a7)

The jobs running without problems.


Also twhen i create new hosts with this groups with the playbook
![image](https://github.com/ansible-collections/community.zabbix/assets/6429642/3c4ea14b-3799-4cc7-a041-629632cc0e7d)

the first time the job is running

**Comment by BGmot** [comment]
Thank you. By the way `groups:` cannot be empty list.

**Comment by Midas1989** [comment]
Sorry but the problem ist also with filled groups.

Please read the issue

I can create hosts inital without problems (also with subgroups in the list), on the second run i have the issue. 
Only the created group have subgroups in the groups.
