### ISSUE TITLE
Step "Debian | Download gpg key" reports change in check mode

### ISSUE THREAD

**Issue by besole** [ansible-collections/community.zabbix#1170]
##### SUMMARY
When running a role in check mode after an initial successful run without check mode, the Step "Debian | Download gpg key" in `tasks/Debian.yml" reports changes, even though the gpg key did not change.
There is an open issue for this in the ansible project with further information (https://github.com/ansible/ansible/issues/65687)

The used module for this step (`ansible.builtin.get_url`) checks for an existing file and sends a `If-Modified-Since` HTTP header. If the Server the responds with a 304 status, no changes will be reported.
This is not the case for `http://repo.zabbix.com/zabbix-official-repo.key`. A `200 OK` Code is returned even if a 'If-Modified-Since' header is present and it's newer than the returned `Last-Modified` header

Additionaly, `ansible.builtin.get_url` uses a HEAD request when using check mode, which returns only headers without body content. Ansible then checks the checksum of the existing gpg key file against the checksum of the empty body, which obviously do not match

I propose one of the following workarounds
- The Webserver returns a `304 Not Modified` HTTP status code for an unmodified gpg key on an HTTP HEAD request with `If-Modified-Since` header
  - needs to be implemented by repo.zabbix.com server, unlikely to be changed?
- use `ansible.builtin.get_url` with `checksum:` and `force: false`
  - checksum can be a url to a checksum file or static checksum like `sha1:<checksum>`
  - this allows ansible to check the existing file against a supplied checksum, which would need to be updated when the gpg key changes

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
all roles:
- zabbix_agent
- zabbix_javagateway
- zabbix_proxy
- zabbix_server
- zabbix_web

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.2]
  config file = /ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/ansible/ansible.cfg) = facts
COLLECTIONS_PATHS(/ansible/ansible.cfg) = ['/ansible/collections']
CONFIG_FILE() = /ansible/ansible.cfg
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = ['/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/ansible/ansible.cfg) = yaml
```

##### OS / ENVIRONMENT / Zabbix Version
OS: Debian GNU/Linux 12 (bookworm)

##### STEPS TO REPRODUCE
1. Install e.g. zabbix agent with role `zabbix_agent` (example playbook below)
2. Run playbook with `--check` command line argument -> Downloading gpg key will report a change
3. Run playbook without `--check` -> no change will be reported

```yaml
- name: Install Zabbix Agent
  hosts: all
  roles:
    - community.zabbix.zabbix_agent
```

##### EXPECTED RESULTS
no change should be reported when using check mode (`--check`) if the gpg key has not changed

##### ACTUAL RESULTS

the play reports a change in check mode, even if the key has not actually changed.
a run without check mode will not report any changes (as expected)

```paste below
...

TASK [community.zabbix.zabbix_agent : Debian | Download gpg key] ******************************
changed: [zabbix01] => changed=true 
  checksum_dest: 2e9c2a85f0ef5f81e21734833f61e7774441bd48    <- checksum of existing key file
  checksum_src: da39a3ee5e6b4b0d3255bfef95601890afd80709     <- checksum for empty string (sha1sum /dev/null)
  dest: /etc/apt/keyrings//zabbix-official-repo.asc
  elapsed: 0
  gid: 0
  group: root
  mode: '0644'
  msg: OK (2938 bytes)
  owner: root
  size: 2938
  src: /home/ansible/.ansible/tmp/ansible-tmp-1705560440.8606417-218106-34349412065866/tmp80lzc4es
  state: file
  uid: 0
  url: http://repo.zabbix.com/zabbix-official-repo.key

...
```

**Comment by pyrodie18** [comment]
My own personal opinion is that this is a bug with the module, and not the role.  I have no idea how often those GPG keys change but having to update that value would a manual process.  I am unsure off the top of my head, but I think that if we provide a checksum and the current file doesn't match it downloads and if it still doesn't match (because the key has changed and we haven't updated the checksum) that the module will fail.  I think that the module failing simply because a change in GPG key hadn't been noticed/updated would have a lot more significant impact then a false CHANGED return when running in check mode.

**Comment by besole** [comment]
thanks for your thoughts @pyrodie18 

you're right, the role would fail when supplying a checksum with a changed
