### ISSUE TITLE
create host in 7.0.0beta1 failed

### ISSUE THREAD

**Issue by Midas1989** [ansible-collections/community.zabbix#1179]
**Problem Version**
7.0.0beta1

**last valid version**
7.0.0alpha9

**Collection version:** 
3.1.0

**Playbook task:**
```
    - name: Create a new host or rewrite an existing host's info
      vars:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_host: "{{ zabbix_url }}"
        ansible_zabbix_url_path: ""
      become: false
      community.zabbix.zabbix_host:
        host_name: "{{ inventory_hostname }}"
        host_groups: "{{ hostgroups }}"
        state: present
        proxy: "{{ zabbix_proxy }}"
      delegate_to: localhost
```

**Error:**
TASK [Create a new host or rewrite an existing host's info] ********************************************************************************************************************************************************************************************************************************
task path: /home/users/myusername/zabbix/ansible/inital_host_generation/create-and-link-hostgroups.yml:173
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
Read vars_file 'main.yml'
Read vars_file 'tags.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
Read vars_file '{{ STAGE }}_secure_vars.yml'
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<my_ansible_server> ESTABLISH LOCAL CONNECTION FOR USER: myusername
<my_ansible_server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z `"&& mkdir "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.7615504-919581-24783441732932 `"
&& echo ansible-tmp-1707722608.7615504-919581-24783441732932="` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.7615504-919581-24783441732932 `" ) && sleep 0'
<my_ansible_server> ESTABLISH LOCAL CONNECTION FOR USER: myusername
<my_ansible_server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z `"&& mkdir "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.9947107-919591-189812142470341 `"
 && echo ansible-tmp-1707722608.9947107-919591-189812142470341="` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.9947107-919591-189812142470341 `" ) && sleep 0'
<my_ansible_server> ESTABLISH LOCAL CONNECTION FOR USER: myusername
<my_ansible_server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z `"&& mkdir "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.0297549-919579-183452751449037 `"
 && echo ansible-tmp-1707722609.0297549-919579-183452751449037="` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.0297549-919579-183452751449037 `" ) && sleep 0'
Using module file /home/users/myusername/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<my_ansible_server> PUT /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/tmptf53ir9e TO /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.7615504-919581-24783441732932/AnsiballZ_zabbix_host.py
Using module file /home/users/myusername/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<my_ansible_server> PUT /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/tmplxe4h4ui TO /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.9947107-919591-189812142470341/AnsiballZ_zabbix_host.py
<my_ansible_server> EXEC /bin/sh -c 'chmod u+x /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.9947107-919591-189812142470341/ /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.9947107-919591-189
812142470341/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> EXEC /bin/sh -c 'chmod u+x /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.7615504-919581-24783441732932/ /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.7615504-919581-2478
3441732932/AnsiballZ_zabbix_host.py && sleep 0'
Using module file /home/users/myusername/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<my_ansible_server> PUT /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/tmpj3kdzz8l TO /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.0297549-919579-183452751449037/AnsiballZ_zabbix_host.py
<my_ansible_server> EXEC /bin/sh -c 'chmod u+x /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.0297549-919579-183452751449037/ /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.0297549-919579-183
452751449037/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> EXEC /bin/sh -c '/usr/bin/python3.11 /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.9947107-919591-189812142470341/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> EXEC /bin/sh -c '/usr/bin/python3.11 /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722608.7615504-919581-24783441732932/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> ESTABLISH LOCAL CONNECTION FOR USER: myusername
<my_ansible_server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z `"&& mkdir "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.196379-919584-139840854607322 `"
&& echo ansible-tmp-1707722609.196379-919584-139840854607322="` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.196379-919584-139840854607322 `" ) && sleep 0'
<my_ansible_server> EXEC /bin/sh -c '/usr/bin/python3.11 /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.0297549-919579-183452751449037/AnsiballZ_zabbix_host.py && sleep 0'
Using module file /home/users/myusername/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<my_ansible_server> PUT /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/tmp25sdfmls TO /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.196379-919584-139840854607322/AnsiballZ_zabbix_host.py
<my_ansible_server> EXEC /bin/sh -c 'chmod u+x /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.196379-919584-139840854607322/ /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.196379-919584-13984
0854607322/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> ESTABLISH LOCAL CONNECTION FOR USER: myusername
<my_ansible_server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z `"&& mkdir "` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240188493788602 `"
 && echo ansible-tmp-1707722609.2107372-919586-240188493788602="` echo /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240188493788602 `" ) && sleep 0'
<my_ansible_server> EXEC /bin/sh -c '/usr/bin/python3.11 /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.196379-919584-139840854607322/AnsiballZ_zabbix_host.py && sleep 0'
Using module file /home/users/myusername/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<my_ansible_server> PUT /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/tmp0m7xg8id TO /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240188493788602/AnsiballZ_zabbix_host.py
<my_ansible_server> EXEC /bin/sh -c 'chmod u+x /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240188493788602/ /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240
188493788602/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> EXEC /bin/sh -c '/usr/bin/python3.11 /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240188493788602/AnsiballZ_zabbix_host.py && sleep 0'
<my_ansible_server> EXEC /bin/sh -c 'rm -f -r /home/users/myusername/.ansible/tmp/ansible-local-918778e_6jss_z/ansible-tmp-1707722609.2107372-919586-240188493788602/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_9qwfv6wd/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 29, in _httpapi_error_handle
    code, response = self.connection.send_request(data=payload)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_9qwfv6wd/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [server01 -> localhost({{ zabbix_url }})]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": null,
            "force": true,
            "host_groups": [
                "all",
                "mygroup",
                "mygroup/mygroup1",
                "mygroup/mygroup2"
            ],
            "host_name": "server01",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [],
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": null,
            "macros": null,
            "proxy": "",
            "state": "present",
            "status": "enabled",
            "tags": null,
            "tls_accept": null,
            "tls_connect": null,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "visible_name": null
        }
    },
    "msg": "connection error occurred: REST API returned {'code': -32602, 'message': 'Invalid params.', 'data': 'Invalid parameter \"/1/groups/1\": unexpected parameter \"name\".'} when sending {\"jsonrpc\": \"2.0\", \"method\": \"host.update\", \"id\": \"gtrgtrgr-254r-5t5t-5tg4-gtg5
2cbdb804\", \"params\": {\"hostid\": \"10796\", \"groups\": [{\"groupid\": \"29\", \"name\": \"all\", \"flags\": \"0\", \"uuid\": \"44659adbcd0144e4b010aba9ea8d6877\"}, {\"groupid\": \"134\", \"name\": \"mygroup\", \"flags\": \"0\", \"uuid\": \"fdffj89rf548877fj8754r59874uf78
f\"}, {\"groupid\": \"135\", \"name\": \"mygroup/mygroup1\", \"flags\": \"0\", \"uuid\": \"4c30480b1dfd4cdc8fdff2358e720d4e\"}, {\"groupid\": \"140\", \"name\": \"mygroup/mygroup2\", \"flags\": \"0\", \"uuid\": \"hnuhd873478rh349hr3987r34\"}], \"status\": 0, \"proxy_hostid\": 0
}, \"auth\": \"myapikey\"}"
}

**Comment by pyrodie18** [comment]
@Midas1989 we have not started work on 7.0 yet and will not until they actually release.  I am going to close this for now but if it is still valid when 7.0 officially comes out, please feel free to re-open it.
