### ISSUE TITLE
Unable to use Zabbix collection

### ISSUE THREAD

**Issue by olistu** [ansible-collections/community.zabbix#1182]
Hi,

I want to use the Zabbix Community with my Ansible Tower. I have create my own Execution environment to add Community_Zabbix module.

[root@svx-cds-03t ~]# podman container run -it localhost/ee_unifr_24:latest ansible-galaxy collection list |grep zabbix
community.zabbix              2.3.1
[root@svx-cds-03t ~]#

My playbook is :
- name: Zabbix maintenance mode
  hosts: ansible-tower-server.toto.ch
  vars:
    zabbix_api_token: 60460362b83e4407f76863c40c60f082c375d0ddccdd220108c246f0efc26e2e
    ansible_zabbix_auth_key: "{{ zabbix_api_token }}"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8080
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_host: zabbix-server.toto.ch
  
  tasks:
  - name: Retrieve API information
    community.zabbix.zabbix_api_info:
    register: zbx_api_info
    ignore_errors: true

  - name: Display API information
    debug:
      msg: 
        - '{{ zby_api_info }}'
    ignore_errors: true

The error is :
{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-21woo_9gq3/ansible-tmp-1708080499.719198-67-191031388465380/AnsiballZ_zabbix_api_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-21woo_9gq3/ansible-tmp-1708080499.719198-67-191031388465380/AnsiballZ_zabbix_api_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-21woo_9gq3/ansible-tmp-1708080499.719198-67-191031388465380/AnsiballZ_zabbix_api_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_api_info', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_api_info', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_api_info.py\", line 108, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_api_info.py\", line 103, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_api_info.py\", line 80, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 20, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.\n\n",
  "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-21woo_9gq3/ansible-tmp-1708080499.719198-67-191031388465380/AnsiballZ_zabbix_api_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-21woo_9gq3/ansible-tmp-1708080499.719198-67-191031388465380/AnsiballZ_zabbix_api_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-21woo_9gq3/ansible-tmp-1708080499.719198-67-191031388465380/AnsiballZ_zabbix_api_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_api_info', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_api_info', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_api_info.py\", line 108, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_api_info.py\", line 103, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_api_info.py\", line 80, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 20, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_api_info_payload_3jc83r0u/ansible_community.zabbix.zabbix_api_info_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.\n\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": null,
  "changed": false
}

I need help
Regards
Olivier

**Comment by invisibleninja06** [comment]
I had the same issue and seems that `ansible_zabbix_url_path: ''` must be set otherwise it fails even though the module documentation doesnt list it as required.

I see two fixes here that i will list in order of best to worst in my opinion
- make it so that we dont need to specify `ansible_zabbix_url_path`
- mark `ansible_zabbix_url_path` are required

**Comment by invisibleninja06** [comment]
Odd because my zabbix server loads fine if i use fdqn/zabbix but the module before I specified `ansible_zabbix_url_path` would result in `File not found`

**Comment by invisibleninja06** [comment]
Also interesting that if i try `/zabbix` or `zabbix` the latter of which should be the default, i get the same File not found error. 

Not entirely sure why this is getting pre-maturely closed, have you tested this on your end?

Full traceback is
```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-674djsje016/ansible-tmp-1709576972.7182903-720-2683324732135/AnsiballZ_zabbix_proxy_info.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-674djsje016/ansible-tmp-1709576972.7182903-720-2683324732135/AnsiballZ_zabbix_proxy_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-674djsje016/ansible-tmp-1709576972.7182903-720-2683324732135/AnsiballZ_zabbix_proxy_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_proxy_info', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_proxy_info', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_proxy_info.py", line 173, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_proxy_info.py", line 167, in main
  File "/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-674djsje016/ansible-tmp-1709576972.7182903-720-2683324732135/AnsiballZ_zabbix_proxy_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-674djsje016/ansible-tmp-1709576972.7182903-720-2683324732135/AnsiballZ_zabbix_proxy_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-674djsje016/ansible-tmp-1709576972.7182903-720-2683324732135/AnsiballZ_zabbix_proxy_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_proxy_info', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_proxy_info', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_proxy_info.py\", line 173, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_proxy_info.py\", line 167, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 20, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_proxy_info_payload_13n6r8p5/ansible_community.zabbix.zabbix_proxy_info_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.\n\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

We have zabbix server installed via docker compose.
Like i said, if i set the url path to `''` than everything is working.

**Comment by BGmot** [comment]
> Like i said, if i set the url path to '' than everything is working.
So what's the problem then?

**Comment by invisibleninja06** [comment]
I shouldn't have to specify the URL because as you said the default is fqdn.com/zabbix (which works if i enter that url or curl it) but if i dont specify `ansible_zabbix_url_path=''` it results in the error.

If its optional and uses the default of `zabbix` than i shouldnt be getting any errors if there is no bug here.

**Comment by invisibleninja06** [comment]
Assuming @olistu can confirm setting `ansible_zabbix_url_path=''` fixes the issue it will be two users with the same issue where we must specify an empty value for an optional parameter.

**Comment by BGmot** [comment]
What I am trying to say is that it's not "an issue". If I make `ansible_zabbix_url_path=''` default then other people will complain about failures because their Zabbix default installation will be at `http://<url>/zabbix`

**Comment by invisibleninja06** [comment]
Its an issue because we shouldn't need to specify it at all.
Setting it to empty is only a work around, not asking you to make that the default.
There really seems to a bug here because even setting it to zabbix, which correct me if i am wrong, should work, does not.

**Comment by invisibleninja06** [comment]
Also the error is super non descriptive which tells me something deeper is probably breaking.

**Comment by invisibleninja06** [comment]
Ok I get it now.
The default is assuming that zabbix web server is installed as a subdomain which in our case its not.

We access example.com to reach zabbix and not example.com/zabbix

Trying to curl `exmaple.com/zabbix/api_jsonrpc.php` returned the same file not found error.
instead doing a curl on `example.com/api_jsonrpc.php` returns a response

It not super clear in the documentation of the zabbix httpapi as it mentions
"Specifies path portion in Zabbix WebUI URL, e.g. for https://myzabbixfarm.com/zabbixeu zabbix_url_path=zabbixeu" 

This made me try https://example.com/zabbix in a web browser to validate and that works.
Maybe the example should be clearer or provide the curl way to validate this or specify for installations without a subdomain it should be set to `''`

https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_httpapi.html

**Comment by BGmot** [comment]
@invisibleninja06 does this https://github.com/ansible-collections/community.zabbix/pull/1189 look better?

**Comment by invisibleninja06** [comment]
That's great, thank you very much.

**Comment by invisibleninja06** [comment]
> @invisibleninja06 does this #1189 look better?

This is perfect, thank you very much.
