### ISSUE TITLE
zabbix_user: user_medias is deprecated (unexpected parameter \"user_medias\")

### ISSUE THREAD

**Issue by lucas-padilia-lgti** [ansible-collections/community.zabbix#1191]
##### SUMMARY
The module is attempting to send data using the old Zabbix API structure, which used "user_medias," whereas the current structure only uses "medias."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_user

##### ANSIBLE VERSION
ansible [core 2.12.10]

##### STEPS TO REPRODUCE
Create a playbook and add/change a media type and the error will happen

unexpected parameter \"user_medias\"

**Comment by BGmot** [comment]
What version of this collection are you using? What version of Zabbix? Please post a playbook code snippet that causes this issue.

**Comment by pyrodie18** [comment]
No reply left and as best as I can tell this is a very old version.  Closing for now but feel free to re-open it if/when you reply with the requested informatino.
