### ISSUE TITLE
Wrong include dir is being removed here

### ISSUE THREAD

**Issue by badfiles** [ansible-collections/community.zabbix#1236]
This line removes agent II include dir trying to remove agent I include dir

https://github.com/ansible-collections/community.zabbix/blob/64b6687b9a6763c1987902aec05244db02e6e75d/roles/zabbix_agent/tasks/remove.yml#L23

**Comment by derekpurdy** [comment]
I'm having the same issue, it seems to break zabbix_agent2 from being able to start as "/etc/zabbix/zabbix_agent2.d" is missing.

`Jun  2 09:58:36 zabbix zabbix_agent2[1122563]: zabbix_agent2 [1122563]: ERROR: Cannot read configuration: cannot include "/etc/zabbix/zabbix_agent2.d": stat /etc/zabbix/zabbix_agent2.d: no such file or directory`

**Comment by derekpurdy** [comment]
it does seem like a show stopper, it basically breaks zabbix_agent2 from working out of the box without manually modifying the remove task in the collection (or modifying the template conf file to not include an include line.)

**Comment by krauthosting** [comment]
@pyrodie18 Same as #1263 will this be backported to stable point release `2.5.1`?

**Comment by pyrodie18** [comment]
No, as a collection we're only maintaining the current version and not previous versions.
