### ISSUE TITLE
Zabbix agent 2 persistent buffer is broken

### ISSUE THREAD

**Issue by badfiles** [ansible-collections/community.zabbix#1237]
The enable parameter is missing in agent template

https://github.com/ansible-collections/community.zabbix/commit/c2a32d5ea130eadbf4c4a0b6160757cd9a7e8ac9#r142464773

**Comment by badfiles** [comment]
now the zabbix_agent_persistentbuffer is missing in the rest of the code

**Comment by pyrodie18** [comment]
@badfiles  take a look at https://github.com/ansible-collections/community.zabbix/pull/1278 and tell me if I actually fixed this finally

**Comment by badfiles** [comment]
yes, now it works
