### ISSUE TITLE
community.zabbix was NOT installed successfully: - sorry, community.zabbix was not found on https://galaxy.ansible.com.

### ISSUE THREAD

**Issue by itJunky** [ansible-collections/community.zabbix#124]
##### SUMMARY
Trying to get role from ansible-galaxy, but have error:

```
~/.ansible> ansible-galaxy collection install community.zabbix --ignore-errors
- downloading role 'collection', owned by 
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

- downloading role 'zabbix', owned by community
 [WARNING]: - community.zabbix was NOT installed successfully: - sorry, community.zabbix was not found on https://galaxy.ansible.com.
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
installation

##### ANSIBLE VERSION

```
~/.ansible> ansible --version
ansible 2.7.8
```

##### CONFIGURATION

```
empty output
```

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu 19.04 where run ansible-playbook
Astra Linux SE 1.5 (Smolensk) is a target for playbook

##### STEPS TO REPRODUCE

Just run  `ansible-galaxy collection install community.zabbix`

##### EXPECTED RESULTS
Just install ansible role

##### ACTUAL RESULTS

```
~/.ansible> ansible-galaxy -vvvv collection install community.zabbix --ignore-errors
ansible-galaxy 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.7.3 (default, Oct  7 2019, 12:56:13) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
Opened /home/~/.ansible_galaxy
Processing role collection 
Opened /home/~/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'collection', owned by 
https://galaxy.ansible.com/api/v1/roles/?owner__username=&name=collection
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

Processing role community.zabbix 
Opened /home/~/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'zabbix', owned by community
https://galaxy.ansible.com/api/v1/roles/?owner__username=community&name=zabbix
 [WARNING]: - community.zabbix was NOT installed successfully: - sorry, community.zabbix was not found on https://galaxy.ansible.com.
```

**Comment by sky-joker** [comment]
Hi @itJunky

The full support of Collections is since Ansible 2.9.  
Can you please version up from 2.7.8 to 2.9 or more and try it again?

https://www.ansible.com/blog/getting-started-with-ansible-collections

**Comment by gundalow** [comment]
Don't think this would help this, though adding `meta/runtime.yml` into the repo would be good
```
---
requires_ansible: '>=2.9.10'
```

**Comment by D3DeFi** [comment]
> Don't think this would help this, though adding `meta/runtime.yml` into the repo would be good
> 
> ```
> ---
> requires_ansible: '>=2.9.10'
> ```

how would this affect roles @gundalow ?

@dj-wasabi do you have specific version you are trying to support for the ansible?

**Comment by dj-wasabi** [comment]
With the specific `meta/main.yml` files in each role, there is also a version configured. Do we need to remove that (directory) - or update it - so it matches the minimum of 2.9.10? I tested the roles with 2.9.11.

**Comment by D3DeFi** [comment]
> With the specific `meta/main.yml` files in each role, there is also a version configured. Do we need to remove that (directory) - or update it - so it matches the minimum of 2.9.10? I tested the roles with 2.9.11.

Thanks for pointing that out. I am not sure if that file is taken into account anymore since these roles are no longer standalone and come as a part of collection. Collections were not properly supported prior 2.9.10 and users with older ansible versions won't be able to install it.  

However, that doesn't mean that manually downloading the role and running it on lets say 2.7 wont work. 

So only difference  meta/runtime.yml should do is that it will fail with unsupported version if someone on older ansible version will try `ansible-galaxy install community.zabbix`? But name runtime.yml hints that it may have other effects, like failing during each `ansible-playbook` execution if ansible version is lower. @gundalow ?

**Comment by D3DeFi** [comment]
closing as this is marked as wont fix anyways, addition of meta/runtime.yml will not make this collection support ansible version < 2.9.10 anyways
