### ISSUE TITLE
Remove Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1252]
As part of 3.0.0 release remove support for Ubuntu 18.04 which is EOL.

**Comment by krauthosting** [comment]
@pyrodie18 What about enterprise customers with ESM who have still support?
I gently disagree we remove support with distro that their vendors still support.

**Comment by pyrodie18** [comment]
This collection doesn't have ESM so there is no way for us to test against it.  As a rule to make things manageable we only support operating systems and versions of Zabbix that are fully supported by their respective vendor.  Understand that even though this collection is part of the Ansible community, it is 100% community maintained and not at all maintained by RedHat and the core ansible team.  Our goal is to support as many common use cases as we can within reason but admittedly chose not to support every possible configuration out there.
