### ISSUE TITLE
Remove Support for Debian 10

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1253]
As part of the 3.0.0 cleanup, remove support for Debian 10 which is EOL.

**Comment by BGmot** [comment]
Project name "Zabbix 3.0" is a bit confusing, maybe we should rename it to something like "Version 3.0" or "Collection version 3.0"?

**Comment by pyrodie18** [comment]
> Project name "Zabbix 3.0" is a bit confusing, maybe we should rename it to something like "Version 3.0" or "Collection version 3.0"?

Updated the project name
