### ISSUE TITLE
Implement a connection dictionary on modules

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#126]
##### SUMMARY
Currently we need to write the common connection `server_url, login_user, login_password` on each tasks in plays. That's repeating. The AVI modules for example has a neat feature for this [see Ansible Docs](https://docs.ansible.com/ansible/latest/modules/avi_network_module.html#parameter-avi_credentials) / [github avi modules](https://github.com/ansible/ansible/tree/stable-2.9/lib/ansible/modules/network/avi) .

One the one hand they provide the parameters on each module like we do. But they also have a parameter `avi_credentials` which you can pass an dictionary with the connection parameters. So you just call this one parameter in the tasks and "store" a dictionary with the other parameters in the inventory. I like this - will do a PR.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_connection or zabbix_credentials for each module

##### ADDITIONAL INFORMATION
Additional links to avi for examples:
[avi commit on credentials](https://github.com/ansible/ansible/commit/6d21cebd7d8b5ecc30c2d01d0eeb6e44d2d5fa06)
[avi helpers ](https://github.com/ansible/ansible/blob/0b8354751b3ecbdba1813030411701af1895bdfa/lib/ansible/module_utils/network/avi/avi_api.py)

**Comment by tcraxs** [comment]
I like your approach and like to see the PR.
Another option could be using the [playbook module_defaults](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html) instead of rewriting the same thing in every task. I also saw this the first time a few week ago, but helped me out for example in the integration tests (see [here](https://github.com/ansible-collections/community.zabbix/blob/master/tests/integration/targets/test_zabbix_discovery_rule/tasks/main.yml#L7)). Just think about it :)

**Comment by rockaut** [comment]
@tcraxs didn't know this either thank you. But imo the additional parameter might still work.
module_defaults have to be set in each play as I read it. With the new parameter one can initialize/set it in the inventory.

**Comment by rockaut** [comment]
Thinking about it, with the new parameter you can also work on multiple zabbix instances at once.

**Comment by D3DeFi** [comment]
I’ve already seen this in f5 modules and I think there is no harm in implementing it. With the ZabbixBase it should even be elegant and not require any hackish solutions.

We, however, need to support old way
for some time too before deprecating it in favor of zabbix_credentials.

**Comment by rockaut** [comment]
You know what ... screw this for now! I tried to wrap my head around how we can make this failsafe from a user perspective and I cant get it working.

With basic ansible you can't define the required parameters detailed enough and the required_* arguments for AnsibleModule aren't able do recursively define requirements. Also with the current refactoring of all modules I feel it has potential to generate a gigantic fail.

I'll drop the PR and close this Issue for now while keeping it in my brain for later after we figured out the ZabbixBase things more closely.
