### ISSUE TITLE
Ansible.netcommon collection dependency outdated

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-collections/community.zabbix#1266]
##### SUMMARY

I ran into an issue running the role because some changes that were made to netaddr and how it's handled in Ansible. The issue was fixed by manually updating the ansible.utils collection from 2.6.1 to 4.1.0. (ansible-galaxy collection install ansible.utils)

So I went looking why it wasn't updated. I noticed that this collection still refers to ansible.netcommon below 3.1.1 which in turn refers to ansible.utils below 3.0.0.

However, that release of ansible.netcommon is over 2 years old by now, the current version is 6.1.3

Time to update? :)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Collection dependencies

**Comment by pyrodie18** [comment]
Just looked at this.  We have a requirement of >= 3.1.1 and in fact our molecule testing runs against 6.1.1.  You're more than welcome to upgrade without issue.
