### ISSUE TITLE
Tags in LLD rules

### ISSUE THREAD

**Issue by BGmot** [ansible-collections/community.zabbix#1269]
Hi @aplathrop ,
can you please clarify where these tags should go to?
https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_discoveryrule.py#L228
I cannot find this neither in UI nor in API documentation for 6.4.
It is failing for 7.0 as it has stricter parameters check.

**Comment by aplathrop** [comment]
That looks like I copy-pasted the examples I wrote for zabbix_item (their API methods are surprisingly similar) and didn't delete the tags from the item module. I can submit a PR to change that example to something that works if you would like

**Comment by BGmot** [comment]
Thanks for looking into this so quickly. Yes, please update EXAMPLES section and tests as well (in a PR).

**Comment by BGmot** [comment]
Also please mention somewhere in documentation that this is *LLD discovery rules*
