### ISSUE TITLE
Zabbix_action module missing operation value2 parameter

### ISSUE THREAD

**Issue by adrianlzt** [ansible-collections/community.zabbix#13]
##### SUMMARY
If ``condition.type`` is ``event_tag_value``, parameters ``value`` and ``value2`` must be set, but ``value2`` is not documented.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
zabbix_action module

##### ANSIBLE VERSION

```paste below
master
```

**Comment by D3DeFi** [comment]
Thank you for reporting this @adrianlzt !

I will try to look at it when I have a time. It is indeed true that we miss `value2` as can be seen in [action API documentation](https://www.zabbix.com/documentation/4.4/manual/api/reference/action/object#action_filter_condition)

**Comment by D3DeFi** [comment]
@adrianlzt can you please confirm, that you can use `value2` with condition type `event_tag_value` even if it is not documented as stated in #43?
