### ISSUE TITLE
Regarding flake8 syntax checking test

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#130]
##### SUMMARY

In the current CI have problems with it can't detection of unused variable and imported library.  
So, I'm working on a new test with flake8 and tox.  
After tests with flake8, I found unused variables and library in some modules and module_utils.  
If I will PR do you think it would be better to split the branches like CI refactoring before? (ex: devel_tox_flake8)

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

plugins/module_utils/base.py
plugins/module_utils/helpers.py
plugins/module_utils/wrappers.py
plugins/modules/zabbix_action.py
plugins/modules/zabbix_group.py
plugins/modules/zabbix_group_info.py
plugins/modules/zabbix_maintenance.py
plugins/modules/zabbix_mediatype.py
plugins/modules/zabbix_template_info.py
plugins/modules/zabbix_user.py
plugins/modules/zabbix_valuemap.py
plugins/modules/zabbix_service.py

##### ADDITIONAL INFORMATION

I used [tox.ini](https://github.com/ansible-collections/vmware/blob/main/tox.ini) of VMware Collection as a guide.

**Comment by D3DeFi** [comment]
Thank you for looking into this

**Comment by sky-joker** [comment]
Thank you @D3DeFi for looking at this issue.
I’m going to create a new PR for this issue :)
