### ISSUE TITLE
[Zabbix Agent] Windows Agent installation is executed 2 times

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/community.zabbix#1300]
##### SUMMARY
Windows Agent installation is executed 2 times due to include_role task.

[Task](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/main.yml#L41)

If variable zabbix_manage_repo isn't set to false for Windows systems, task Windows.yml will be executed from:
[Task](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_repo/tasks/main.yml#L7)

Specific task file isn't available in role so Ansible falls back to Windows.yml from role-zabbix-agent.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

Ansible 2.16

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 6.0.30
Windows Server 2022

##### EXPECTED RESULTS
Running installation with one execution.

##### ACTUAL RESULTS
Agent installation is executed 2 times.

**Comment by the-iot** [comment]
please add merge into main and release 3.0.2 - momentary we cant install zabbix agent on windows with release 3.x
