### ISSUE TITLE
Dropping support for agent2????

### ISSUE THREAD

**Issue by CompPhy** [ansible-collections/community.zabbix#1308]
I just notice this comment in changelogs:  "Support for zabbix_agent2 to be removed in 3.0.0"

Is there a specific reason for this?  It is being fully supported in the Zabbix 7.0 release, so shouldn't this collection also support it?  It seems like Zabbix is trying to push users towards using Agent2 more, as it's seen a lot of new plugin, etc.

We utilize agent2 almost exclusively in our environment, and loosing support in Ansible will be a huge burden.

https://www.zabbix.com/documentation/current/en/manual/concepts/agent2

**Comment by the-iot** [comment]
hi,

the support is not drop.

only the vars renamed.

**Comment by CompPhy** [comment]
Thank you, that's great news.
