### ISSUE TITLE
publish version 3.0.1 as release 

### ISSUE THREAD

**Issue by the-iot** [ansible-collections/community.zabbix#1309]
hello,

please publish version 3.0.1 on Git so that you can create a new execution environment in ansible awx. currently only version 3.0.0 with the Windows bug is available.

Only 3.0.0 is available for Galaxy.

**Comment by pyrodie18** [comment]
Crap forgot to tag the release.  Just got off a plane will take care of when I get home

**Comment by BGmot** [comment]
I pushed the tag.

**Comment by BGmot** [comment]
@the-iot it's available now in Galaxy.
