### ISSUE TITLE
Molecule Failures

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1324]
@BGmot  do we have any ideas why the hell Molecule keeps failing.  I feel like it has happened SIGNIFICANTLY more since @eb4x  brought in #1303  but I see no reason why it would be happening.  Either of you guys have ideas?

**Comment by pyrodie18** [comment]
Ok, looking closer it looks like it is AWAYS only the agent role and ALWAYS only Debian/Ubuntu that is failing.

**Comment by BGmot** [comment]
Yes, but re-running the same tests help.

**Comment by BGmot** [comment]
Moreover, when I execute these tests on my local machine they never fail.

**Comment by eb4x** [comment]
I noticed the same errors in github_workflows of zabbix_agent on debian/ubuntu systems like a week or two before merge aswell. They all seem to fail during the exact same step, during copying of the ansiballz onto the host/container in some prepare.yml step, straight after the container has been created.

Some other things to consider are if the github ubuntu-20.04 runner image has changed recently or the geerlingguy images.

**Comment by pyrodie18** [comment]
Haven't looked at either of those images but not a bad idea.

**Comment by BGmot** [comment]
geerlingguy's geerlingguy/docker-debian11-ansible last change was on  Dec 25, 2022 and it is failing for us.
ubuntu-20.04 runner is used for all other OS's tests and they don't fail.

**Comment by BGmot** [comment]
I don't know what is wrong with Ubuntu and Debian images but I assumed that containers are not "quite ready" for "prepare" operations after their creation so adding little delay after a container is created and before molecule starts pushing its files into the container seems to fix the issue (I ran number of tests in GitHub and all of them succeeded). Let's see whether it really fixes the issue.
