### ISSUE TITLE
update zabbix-agent2

### ISSUE THREAD

**Issue by jawm111** [ansible-collections/community.zabbix#1327]
##### SUMMARY
Is it possible only update zabbix-agent2, without updating *conf files etc?

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by pyrodie18** [comment]
What do you mean by update the agent?

**Comment by jawm111** [comment]
Sorry for the bad explanation. I mean just update zabbix-agent2 from version 6.2 to version 6.4 and the conf file does not need to be changed.

**Comment by pyrodie18** [comment]
If you skip the `config` tags when you run the playbook it will skip the templating although not sure if it will cause you problems.  Off the top of my head, I don't recall what (if any) changes in the config file happen between 6.2 and 6.4

**Comment by BGmot** [comment]
If you define all variables with values different from default then you'll be fine.

**Comment by jawm111** [comment]
> If you skip the `config` tags when you run the playbook it will skip the templating although not sure if it will cause you problems. Off the top of my head, I don't recall what (if any) changes in the config file happen between 6.2 and 6.4

Thanks for the tip about skipping the config tags. It solved the problem!
