### ISSUE TITLE
point release 3.0.4 breaks AutoPSK

### ISSUE THREAD

**Issue by krauthosting** [ansible-collections/community.zabbix#1350]
##### SUMMARY
@pyrodie18 @BGmot Hey bros, this again breaks stuff in a minor release :scream_cat:   
FYI We originally contributed the whole logic behind `zabbix_agent_tlspsk_auto`  
Again goal was security by default and avoid Zabbix's unencrypted by default.   
Breaking commits came for issue #1338 via PR #1343 and released as `3.0.4`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`zabbix_agent` role

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.8]
  config file = /home/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### OS / ENVIRONMENT / Zabbix Version
Ubuntu 22.04 LTS / Ansible Conroller / Zabbix 6.0 LTS>

##### STEPS TO REPRODUCE
Enabling `zabbix_agent_tlspsk_auto` leads now to `TLSAccept=psk,unencrypted`  
![Screenshot from 2024-07-23 16-29-31](https://github.com/user-attachments/assets/ef7f2a3c-3994-4b97-918e-a40793542553)  
Beside insecure defaults it also functionally breaks the `zabbix_agent` role:  
![Screenshot from 2024-07-23 16-08-56](https://github.com/user-attachments/assets/b4f45820-7d1d-45ff-8749-7b7d19da55c1)

**Comment by andrew-landsverk-win** [comment]
I notice this issue still affects 3.1.0.

**Comment by pyrodie18** [comment]
Yep, no one has submitted a PR for it yet and me and all of the other maintainers are busy on various other things.

**Comment by iwan-usn** [comment]
As of 3.1.2 the issue is still apparent.

**Comment by Thulium-Drake** [comment]
You can workaround it by adding the following to your inventory variables:

```
zabbix_agent_tlsaccept: 'psk'
zabbix_agent_tlsconnect: 'psk'
```

I'll try to make some time next week to investigate this and make a PR :-)
