### ISSUE TITLE
New Maintainers

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#1373]
We're looking for a couple of people to join the maintainer team for the collection.  Ideally we'd like someone who is a solid Zabbix enthusiast who can offer up at least an hour or two of their time a week (more often than not).  Need people that can review PRs, look at issues, and if you have the time/desire to close out a ticket or two fantastic.  If you're interested, reply to this.

**Comment by pyrodie18** [comment]
@eb4x  and @masa-orca

**Comment by masa-orca** [comment]
@pyrodie18 I am interested to become maintainer!
