### ISSUE TITLE
Missing documentation file

### ISSUE THREAD

**Issue by evilhamsterman** [ansible-collections/community.zabbix#1382]
##### SUMMARY
The main README says 

> Make sure to read [UPGRADE](https://github.com/ansible-collections/community.zabbix/blob/main/docs/UPGRADE.md) document before installing newer version of this collection.

However that file does not exist

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Documentation

##### ANSIBLE VERSION
NA

##### CONFIGURATION
NA

##### OS / ENVIRONMENT / Zabbix Version
NA

##### STEPS TO REPRODUCE
Look at the main README, click the link

##### EXPECTED RESULTS
Not get a 404 but get documenation about information that may be important in an upgrade

##### ACTUAL RESULTS
404 not found

**Comment by pyrodie18** [comment]
After reviewing, there aren't any special instructions required for upgrading the collection.  Removed the comment in the README.
