### ISSUE TITLE
Zabbix Agent 2, 'PersistentBuffer' doesn't work

### ISSUE THREAD

**Issue by Antaiir** [ansible-collections/community.zabbix#1405]
##### SUMMARY

Hi there,

this seems broken for me (or lack of understanding on my end). 

I have the buffer on the agents enabled and set:
```
EnablePersistentBuffer=1
PersistentBufferPeriod=15d
PersistentBufferFile=/tmp/zabbix_BufferFile.sqlite
```

All is working fine as long as the Zabbix-Server is online. 

When i take the server offline (it's just not a 24/7 running machine), the buffer file is created with rw permit for user zabbix, it contains only the IP address and hostname of the agent, but no other data are added. The file size also doesn't increase after the file is created.

When the server is back online, there are no data for the agents for the offline duration of the server.

Both, server and agent, are in the same network. Zabbix is 7.0 LTS, server is a headless Ubuntu-Server 24.04.1 LTS and agents are running either on the same OS version as the server or on a Debian 12.7.0.

I have no idea, what i could have done wrong or what's causing this.

Thank you. :-)

##### ISSUE TYPE

 Bug Report

##### COMPONENT NAME

zabbix-agent2

##### OS / ENVIRONMENT / Zabbix Version

Zabbix server 7.0 LTS is on a headless Ubuntu server 24.04.1 LTS in a ProxMox vm, running with MySQl and Nginx.

1. zabbix-agent2 is running 24/7 on a headless Debian 12.7.0 running on a Futro S520, same network as the server
2. zabbix-agent2 is running on a headless Ubuntu server 24.04.1 LTS in a ProxMox vm, running in an external network.

Both agents on different environment show identical behavior. I use passive mode in both cases.

##### STEPS TO REPRODUCE

- configure the agent for persistent buffering
- stop the server while the agents running
- wait a few minutes
- start the server
- look at the monitoring data from that agents on the server
- see the gap in agent data during the server offline duration

##### EXPECTED RESULTS

No loss of monitoring data from running agents while the server is offline. In my understanding that's what `persistent buffer` means. I assume, the agents should transfer their stored data from the buffer file to the server as soon as the server is available again.

##### ACTUAL RESULTS

Loss of monitoring data from running agents while the server is offline, because there are no data buffered in the buffer file as expected, therefore no data are forwared to the server when it's available again.

The buffer file is created but not filled with monitoring data.

No additional log data is created for the agents when the server is offline.

![zabbix-gap](https://github.com/user-attachments/assets/6299bc1e-10d8-41c4-92e5-ef4459c497f6)

**Comment by pyrodie18** [comment]
Have you verified that the settings you put in the playbook actually exist in the .conf file?  While I don't doubt what you're saying at all, this strikes me as either a missing configuration setting, or a problem with Zabbix itself.  Unless you're putting in a setting in the var and it doesn't translate down correctly, or we're simply not exposing a setting that should be there, then it doesn't sound like a problem with the role itself.

**Comment by Antaiir** [comment]
Thanks for reply.

I also think, it's a zabbix issue, so i also reached out to them. The entries are set in the `zabbix_agent2.conf`.
