### ISSUE TITLE
Using only api functionality

### ISSUE THREAD

**Issue by dshleg** [ansible-collections/community.zabbix#1423]
##### SUMMARY

Now is not possible create host without gathering facts .
This need for hosts monitored only by SNMP aka network devices(switches, routers), pdu units

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_agent role

##### ADDITIONAL INFORMATION

Idea: move api functionality to separated role or add optional key for run only api tasks without gathering facts.
Now if set option gather_facts: no causes fail tasks with a lot of undefined variables

```yaml

```

**Comment by pyrodie18** [comment]
The goal of the roles here is not to support the addition of routers or switches, that is what the modules are for which you can use directly in your own role/playbook.
