### ISSUE TITLE
Problem with zabbix 7.2 beta release

### ISSUE THREAD

**Issue by CappuccinoCake** [ansible-collections/community.zabbix#1428]
##### SUMMARY
Good morning, I have tried to use this module with the new zabbix version 7.2 beta, and i have seen, that the auth property for the api was removed in this version. Would it be possible for you, that you update the module according to the new authentication mechanisms usable, as auth property was already deprecated in 7.2

##### ISSUE TYPE
- New API params in version 7.2

##### ADDITIONAL INFORMATION

```
REST API returned {''code'': -32600, ''message'': ''Invalid request.'', ''data'': ''Invalid parameter "/": unexpected parameter "auth".''} when sending {"jsonrpc": "2.0", "method": "template.get", "id": "5f18f2f5-0743-4b6b-ad48-5591f7b1da96", "params": {"output": ["templateid"], "filter": {"host": "Linux by Zabbix agent"}}, "auth": "REDACTED_FOR_PRIVACY"}'
```

If you need more info about this problem, feel free to ask me.

Thanks in advance.
Patrick.

**Comment by BGmot** [comment]
Zabbix 7.2 has not been released yet. We'll work on this collection compatibility with 7.2 when it is released.

**Comment by CappuccinoCake** [comment]
Wouldn't it be an idea implement the new things already, as there are users, that use the beta version for some features, if they are already known. So when zabbix 7.2 is released, the module would be working already?

Patrick.

**Comment by BGmot** [comment]
Things are changing in pre-release versions.
But sure go ahead if you want and start adapting this collection to 7.2.

**Comment by Menollo** [comment]
Zabbix 7.2 is final, still same problem

**Comment by BGmot** [comment]
@Menollo have you submitted any pull requests to fix this?

**Comment by Menollo** [comment]
I've not a neat fix... I've fixed it for myself with an ugly hack:

```diff
--- ansible_collections/community/zabbix/plugins/httpapi/zabbix.py.orig	2024-12-11 15:33:33.656117174 +0100
+++ ansible_collections/community/zabbix/plugins/httpapi/zabbix.py	2024-12-11 15:35:58.136120373 +0100
@@ -134,24 +134,16 @@ class HttpApi(HttpApiBase):
         if not data:
             data = {}
 
-        if self.connection._auth:
-            data['auth'] = self.connection._auth['auth']
-
+        api_token = self.get_option('zabbix_auth_key')
         hdrs = {
             'Content-Type': 'application/json-rpc',
             'Accept': 'application/json',
+            'Authorization': 'Bearer %s' % api_token,
         }
-        http_login_user = self.get_option('http_login_user')
-        http_login_password = self.get_option('http_login_password')
-        if http_login_user and http_login_user != '-42':
-            # Need to add Basic auth header
-            credentials = (http_login_user + ':' + http_login_password).encode('ascii')
-            hdrs['Authorization'] = 'Basic ' + base64.b64encode(credentials).decode("ascii")
 
         if data['method'] in ['user.login', 'apiinfo.version']:
-            # user.login and apiinfo.version do not need "auth" in data
-            # we provided fake one in login() method to correctly handle HTTP basic auth header
-            data.pop('auth', None)
+            # user.login and apiinfo.version do not need "Authorization" header
+            hdrs.pop('Authorization', None)
 
         data = json.dumps(data)
         try:
```

**Comment by BGmot** [comment]
It's not a fix, it's workaround. We will take care of this. A bit of patience please.
