### ISSUE TITLE
When using the zabbix_agent_firewalld_enable: true zabbix_agent_firewall_enable: true check if the service exists to execute the task

### ISSUE THREAD

**Issue by possebon** [ansible-collections/community.zabbix#144]
##### SUMMARY

First, I have to say that I am registering as a feature idea and not as a bug because I understand that the issue may be directly related to how the host inventory is created.

When I set the `zabbix_agent_firewalld_enable: true` and `zabbix_agent_firewall_enable: true` and I use the playbook to install the zabbix-agent with a host group on Ansible to different versions os Linux or distributions, I can get errors on `firewalld-reload` task if on the particular host has `iptables` and not the `firewalld`.

In my scenario I decided to create a group of hosts to all Linux servers for each site and I have some servers that has `iptables` and other that has `firewalld`.

```
RUNNING HANDLER [community.zabbix.zabbix_agent : firewalld-reload] ***************************************************************************************************************
fatal: [iris-dbserver]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--reload"], "delta": "0:00:00.268054", "end": "2020-07-21 13:42:08.975283", "msg": "non-zero return code", "rc": 252, "start": "2020-07-21 13:42:08.707229", "stderr": "FirewallD is not running", "stderr_lines": ["FirewallD is not running"], "stdout": "", "stdout_lines": []}
fatal: [dc01-nlb01]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--reload"], "delta": "0:00:00.305413", "end": "2020-07-21 13:42:09.036888", "msg": "non-zero return code", "rc": 252, "start": "2020-07-21 13:42:08.731475", "stderr": "FirewallD is not running", "stderr_lines": ["FirewallD is not running"], "stdout": "", "stdout_lines": []}
fatal: [iris-reverseproxy]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--reload"], "delta": "0:00:00.280244", "end": "2020-07-21 13:42:09.067773", "msg": "non-zero return code", "rc": 252, "start": "2020-07-21 13:42:08.787529", "stderr": "FirewallD is not running", "stderr_lines": ["FirewallD is not running"], "stdout": "", "stdout_lines": []}
fatal: [iris-webserver]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--reload"], "delta": "0:00:00.256579", "end": "2020-07-21 13:42:09.197894", "msg": "non-zero return code", "rc": 252, "start": "2020-07-21 13:42:08.941315", "stderr": "FirewallD is not running", "stderr_lines": ["FirewallD is not running"], "stdout": "", "stdout_lines": []}
fatal: [bnglv-ippbx01]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--reload"], "delta": "0:00:00.227043", "end": "2020-07-21 13:40:04.290788", "msg": "non-zero return code", "rc": 252, "start": "2020-07-21 13:40:04.063745", "stderr": "FirewallD is not running", "stderr_lines": ["FirewallD is not running"], "stdout": "", "stdout_lines": []}
changed: [dc01-gitlabce01]

PLAY RECAP ***********************************************************************************************************************************************************************
bnglv-ippbx01              : ok=18   changed=2    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0
dc01-gitlabce01            : ok=23   changed=3    unreachable=0    failed=0    skipped=33   rescued=0    ignored=0
dc01-nlb01                 : ok=18   changed=2    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0
iris-dbserver              : ok=18   changed=2    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0
iris-reverseproxy          : ok=18   changed=2    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0
iris-webserver             : ok=18   changed=2    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Roles
zabbix-agent
zabbix-server
##### ADDITIONAL INFORMATION

In my opinion there are two approaches to avoid that:

1. Use the `ignore_errors` on both tasks, the simpler way, not sure if it's the more "elegant" way.
1. Check if there is a `firewalld` service running set to some flag and on `firewallcmd-reload` task, refactoring it to execute only if flag is true (or maybe there is a direct way to test on the task if firewalld is present)

The second approach could be considered an anti-pattern but is something that came to my mind. I'm still learning Ansible so probably my suggestions could be wrong.

```yaml

```

**Comment by dj-wasabi** [comment]
Hi @possebon 

Sorry for late reply, but there are 2 variables that currently is set to `False`:

* `zabbix_agent_firewall_enable`
* `zabbix_agent_firewalld_enable`

The first one is specific for `iptables`, the 2nd one is for `firewalld`. It is not automatic, but you can configure it per host differently by setting one to `True`.

Does this hat help? Or you look to see it more in an automatic way?

I personally don't like `ignore_errors`. It turns up "red" in your output and you are alerted that something is going wrong, but you then also say no worries, we just ignore it and move on. Maybe a `block` can help it, but I even think it shows an error? Or do you have other (and probably) better solution(s)?
