### ISSUE TITLE
Initial commit into Ansible Galaxy

### ISSUE THREAD

**Issue by ericsysmin** [ansible-collections/community.zabbix#15]
##### SUMMARY
This collection is not yet available in Ansible Galaxy, can we have someone upload it?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by D3DeFi** [comment]
Hi Eric and thanks for raising this issue, I agree that it is the high time to move with this.

@gundalow is this possible now? Last time we spoke on a chat you mentioned something about zuul tests if I remember correctly and that we need to wait for them to be able to release on galaxy.

Another problem is that I don't have permissions to release into the https://galaxy.ansible.com/community namespace.

**Comment by sky-joker** [comment]
Thank you @D3DeFi and @ericsysmin
I was just about to create an issue about this question.

**Comment by gundalow** [comment]
Hi,
I've manually built and release `0.1.0` https://galaxy.ansible.com/community/zabbix
It's still on my todo list to add automatic building on git tag, let me see if I can push that towards the top of my list.

**Comment by sky-joker** [comment]
Thank you @gundalow :)

**Comment by ericsysmin** [comment]
@gundalow thank you, was trying to use this collection as I am moving everything to use collections. :)
