### ISSUE TITLE
Implement Ansible Connection for connection handling

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#161]
##### SUMMARY
Since Ansible 2.6, HttpApi and Connection is the preferred way for calling http/api endpoints. Other collections like splunk have adopted this already in a clean way.

This will also "fix" the problem with opening new zabbix sessions on each executed tasks instead of one persistent session for a play. This behavior is causing some troubles with huge inventories/changes for me.

NOTE: I'm already playing around with this but want to first successfully do #104 to have a baseline.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
Things to consider:
- handling backward compatibility ( see aruba collection as they've done it with now deprecated module property )
- Closing Zabbix Session which is currently handled by atexit usage
- Reopening Zabbix Session which is only implemented since API 4.0

See:
- https://github.com/ansible-collections/splunk.es
- https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/httpapi/__init__.py

**Comment by rockaut** [comment]
*yay* had a breakthrough over the weekend. After the chats with @Qualtos last week I got some great advices and insights.

Got it working and it really, really, really helps to get big playbooks down in resource consumption!
Currently each task!!! is doing:
- login
- action(s)
- logout

So if you, for example are going through your zabbix_host playbook with 100 hosts you have around 300 http calls to the zabbix api - of course depending on what you actually do for the host - but let's go with this for simplicity. Matters worse each login and logout call is also a db-action in the api.
With the new connection I got this down to 102 calls! So just login -> actions -> logout! The magic here happens as the connection is done in a separate process per play (that said if you have more plays in one playbook of course you would do again more  logins/-outs).

So my plan for now:
- implement it for basic usage
-- still with zabbix-api!
-- as an option to the current workflow!
- in further releases
-- refactor thing to replace zabbix-api as a whole ... no more dependencies?
- at some point switch it to the default
- and later remove old things

**Comment by rockaut** [comment]
Additionally this feature would enable the usage of some of the newer features of ansible network modules too. So for example you might just throw a .yaml structured file with the hosts and properties at the modules and you're good to go. (I can't find the link currently - it was shown in an talk while AnsibleFest2020 - will edit the comment later on).

**Comment by D3DeFi** [comment]
Agree with leaving zabbix-api altogether. Although it is a good module, it is not well maintained and I had a need (2 times already) to change something there and only was able to get changes through once, when I scavenged internet for maintainer's email and contacted him/her directly.

This also nicely ties to rework that I would like to done sometimes... somewhere... as zabbix_host becomes more and more unmaintanable (template/screen/action pehaps too)

**Comment by rockaut** [comment]
You're right @D3DeFi. I sat long in the night because I ran against an issue with the implementation. I have another idea what to try next.
But even if this works out I really would like to remove zabbix-api from the equasion as soon as possible. I don't think getting something implemented is too much of a problem as zabbix-api as such isn't great magic.

**Comment by rockaut** [comment]
Just for sake of documentation: my problem of implementing ansible "native" connection/httpapi lies within my idea to get it running with zabbix-api as "backend". Ansible connection/httpapi classes are made for jsonrpc communication as a whole and work by feeding them data into abstracted functions.
As I said my first step is to include zabbix-api as a backend but then move the abstraction done there to the httpapi class itself. I realy just want to get it running in some kind and login/logout is the lowest hanging fruit as I see it.

I guess that was the word of warning @qualtos had for me last week (the I told you so moment (-; ).

**Comment by rockaut** [comment]
close for #444
