### ISSUE TITLE
[Discussion] Should be Python 2.7 abondoned?

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#163]
##### SUMMARY
Currently there are tests against <=2.7 and most of the code is also handled to be compatible. But imo it get's harder and somewhat limiting. So, as 2 is officially dead and other collections also already dumped it, should it be graved here too, maybe with 1.0 for 2.10? IDK but I don't think it's necessary for ansible as such.

To be clear, I don't mean to rewrite all to only fit Python 3, just to dump the tests for <3.x so we can ignore that for future code.

##### ISSUE TYPE
- Discussion

**Comment by dj-wasabi** [comment]
I personally think we should follow Ansible with this. If they still support 2.x, we should do that as well until they decide to stop supporting it with release x.x. Otherwise I am all up for dropping support for 2.x.

**Comment by rockaut** [comment]
> I personally think we should follow Ansible with this. If they still support 2.x, we should do that as well until they decide to stop supporting it with release x.x. Otherwise I am all up for dropping support for 2.x.

I get your thinking and totally accept it ... but ;-) if not the collections starting to abandon a outdated and security-related-problem the "mothership" will not follow suit or at least will have it harder to do it.

**Comment by sky-joker** [comment]
I'd like to confirm the advice of @gundalow.  
Does Collection need to support the same python version as Ansible?

**Comment by D3DeFi** [comment]
I would like to work with f strings and wallruses :( But I believe that we need to follow ansible in this since we will be included in the releases

**Comment by D3DeFi** [comment]
Theoretical: what would happen if drop py2.x after 1.0.0, start working only on 2.0.0 and only backport small changes? 

How would this look with 1.x.0 releases? This would probably lock us only to 1.0.x and then having 2.x.x normally, right?
