### ISSUE TITLE
Zabbix 5.0 requires different config setting for extended range of numeric values

### ISSUE THREAD

**Issue by stephankn** [ansible-collections/community.zabbix#165]
##### SUMMARY

Zabbix 5.0 changed numeric precision. See:
https://www.zabbix.com/documentation/current/manual/installation/upgrade_notes_500

New databases (e.g. created by zabbix_server) have this already. So it needs to include the setting in the web frontend config as well:

```
// Use IEEE754 compatible value range for 64-bit Numeric (float) history values.
// This option is enabled by default for new Zabbix installations.
// For upgraded installations, please read database upgrade notes before enabling this option.
$DB['DOUBLE_IEEE754']   = true;
```

This setting should only be made when creating new database with correct setup (Zabbix 5 and up and db creation).

For upgrades a manual conversion step is needed which also includes adding this config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_web
File:
https://github.com/ansible-collections/community.zabbix/blob/master/roles/zabbix_web/templates/zabbix.conf.php.j2

##### OS / ENVIRONMENT / Zabbix Version
Tested with Zabbix 5.0 install (based on collections version: "d56f2ad2fac946ab3cfbd640ea5a2c3066ddf6b3")
on Ubuntu 20.04 LTS, fresh install.

##### STEPS TO REPRODUCE
Install fresh zabbix_web. Frontend displays warning:

"Database history tables upgraded  No"

##### EXPECTED RESULTS
expect matching config setup.

**Comment by dj-wasabi** [comment]
Hi @stephankn 

If a PR is made, are you able to test this one before merging? Because to me it seems like a basic change to hat needs to be applied to the mentioned template.

Kind regards,
Werner

**Comment by stephankn** [comment]
Yes, I think I can test this.

I wonder what is the conditions under which we need to add this to the front-end. We have to be careful to not break idempotency.

Also how to handle upgrades? In these situations you have an old DB and zabbix_server might upgrade packages, but the DB needs to be manually patched.

So in situations in which the role created the database we know that the database structure is right. We can then add the config flag. 
I think we do not need to worry about older versions of zabbix. Just adding another unknown config setting to older zabbix front-ends should not harm.

It is known since 5.0.2:
https://github.com/zabbix/zabbix/commit/00b7d07c16c6f2824261f15611a6f5edeb918c9d

Should the role detect the state of the database and set the flag accordingly?

**Comment by dj-wasabi** [comment]
Hi @stephankn 

Well, I don't want to do upgrades on a database server with any of these roles. This should be the primary responsibility of the people/teams owning the database and I don't want to be the one that might make an error and f*ck things up for them. Yes, Zabbix also does upgrades when you deploy a new version. But that is all tested and probably follows certain CI tests to validate the behaviour of that.

I haven't taken a look at it yet (Work), but do you think it is easy enough to detect the state with Ansible? If so, then I think this would be the best option. Otherwise we have to think of a proper variable name, document that, find a way to set the correct value and if people didn't do the upgrade/change yet then they should override it.

**Comment by stephankn** [comment]
Sounds more complicated.

As the zabbix_web is de-coupled from the server we do not have the details at hand whether zabbix_server got installed together with a database. 
If we know that this role installed a fresh database, then the structure is correct and we can add the config in the PHP file without thinking about Zabbix version.

Please confirm that the role zabbix_web has no knowledge about the state of db creation via zabbix_server.

So without knowing this, we need to query. This role knows the db type and host, including the credential to log in.

Assuming the DB is running, we can query for the type.

For PostgreSQL there exists a `postgresql_query` module. For MySQL I found nothing similar, so would need to call the mysql binary and hope it is available.

Old scheme uses this (in Mysql 8.0 deprecated) type:

```
SELECT numeric_precision FROM information_schema.columns WHERE table_schema='zabbix' AND table_name='history' AND column_name='value';
+-------------------+
| numeric_precision |
+-------------------+
|                16 |
+-------------------+

```

in fresh installs or after the required conversion it is:

```
SELECT numeric_precision FROM information_schema.columns WHERE table_schema='zabbix' AND table_name='history' AND column_name='value';
+-------------------+
| NUMERIC_PRECISION |
+-------------------+
|                22 |
+-------------------+
```

This query should work with PostgreSQL as well, but I have no environment to test it.
https://www.postgresql.org/docs/current/infoschema-columns.html

**Comment by stephankn** [comment]
Another idea easier to implement, but requiring manual steps from users:
add `zabbix_web_doubleprecision` variable and in case this is true, add the relevant config portion. Default probably set to false to not break anything existing.
Documentation must point out that for fresh and upgraded installs this variable has to be set top true.

**Comment by stephankn** [comment]
As all is caused by the frontend requiring a manual confirmation of the datatype I filed a bug-report there. Best would be the frontend does a detection. https://support.zabbix.com/browse/ZBX-18177

**Comment by markuman** [comment]
As far as I understand, this is an Issue if you come from zabbix <= 5.x.x?  
So when doing a new installation with `community.zabbix.zabbix_server` based on mariadb 10.6, I would expect that `$DB['DOUBLE_IEEE754'] = true;` is set by default and there is nothing I have to do, right?  
But after a fresh installation of zabbix 6.0 with the collection role, I see `Database history tables upgraded: no` on the System information page.

Furthermore, the linked sql statements for mariadb/mysql did nothing

```sql
MariaDB [zabbix]> show create table history;
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                                                                                                                                                      |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| history | CREATE TABLE `history` (
  `itemid` bigint(20) unsigned NOT NULL,
  `clock` int(11) NOT NULL DEFAULT 0,
  `value` double NOT NULL DEFAULT 0,
  `ns` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`itemid`,`clock`,`ns`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

MariaDB [zabbix]> show create table trends;
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                                                                                                                                                                                                                                                                              |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| trends | CREATE TABLE `trends` (
  `itemid` bigint(20) unsigned NOT NULL,
  `clock` int(11) NOT NULL DEFAULT 0,
  `num` int(11) NOT NULL DEFAULT 0,
  `value_min` double NOT NULL DEFAULT 0,
  `value_avg` double NOT NULL DEFAULT 0,
  `value_max` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`itemid`,`clock`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

MariaDB [zabbix]> ALTER TABLE history MODIFY value DOUBLE PRECISION DEFAULT '0.0000' NOT NULL;
Query OK, 0 rows affected (0.009 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [zabbix]> ALTER TABLE trends MODIFY value_min DOUBLE PRECISION DEFAULT '0.0000' NOT NULL, MODIFY value_avg DOUBLE PRECISION DEFAULT '0.0000' NOT NULL, MODIFY value_max DOUBLE PRECISION DEFAULT '0.0000' NOT NULL;
Query OK, 0 rows affected (0.020 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

**Comment by stephankn** [comment]
@markuman this issue was about a mandatory upgrade of types from older versions to zabbix 5.
Is sounds a bit like your recent issue is unrelated. You can check the current settings with:

    SELECT numeric_precision FROM information_schema.columns WHERE table_schema='zabbix' AND table_name='history' AND column_name='value';

If this is 22, then all the discussion here does not apply to your case, as you have it already created with the correct settings.
