### ISSUE TITLE
Regarding the branche name

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#167]
##### SUMMARY

It looks like the collections branch name decided to change master to main by Ansible maintainer.

see:

* https://github.com/ansible-collections/overview/issues/83
* https://github.com/ansible-collections/overview/issues/87

I create this issue for we don't forget.

**Comment by D3DeFi** [comment]
Do we want to rename it? If yes, before 1.0.0?

**Comment by sky-joker** [comment]
If possible that I think desirable that we should rename the current branch before the 1.0.0 release.  
If we would like to change the current branch name I wonder we need to request to @gundalow?  
After confirming with `Settings`, I had not to privilege of changing the branch name.

**Comment by gundalow** [comment]
> Do we want to rename it? If yes, before 1.0.0?

Yes before 1.0.0 would be clearnen

@sky-joker You now have the powers, be careful :+1: 

https://github.com/ansible/community/wiki/Changing-the-git-default-branch-to-main has the steps in

**Comment by sky-joker** [comment]
I checked that I have the privilege of changing the branch name.  
Thank you @gundalow for giving privilege.

**Comment by D3DeFi** [comment]
Thank you for handling this @sky-joker @gundalow 

Feel free to change this whenever (just notify us on Gitter). Handful of developers we are we can survive this change without any major announcements :)

**Comment by sky-joker** [comment]
@D3DeFi 

First, I'm going to check the changing branch name procedure with my GitHub test repository by the end of the day or tomorrow.  
If the procedure is no problem, I will do a consultation for the date of changing the branch name.

**Comment by sky-joker** [comment]
While looking at the renaming procedure, I tried the renaming branch name succeeded with my GitHub test repository :)  
I think this project will be of the renaming repo name procedure the following.

* create the main branch
* change the main to the default branch 
* if exists PR to the master, change to the main
* remove the master branch

We need to decide on the implementation date of the branch renaming.  

@D3DeFi @dj-wasabi

Do you have a preferred implementation date?

**Comment by D3DeFi** [comment]
Maybe if you have time to quickly go through all of the PRs from @dj-wasabi as I think they are ready to be merged and then? For example sometime tomorrow? 

I dont really mind the date as long as it suits you.

**Comment by D3DeFi** [comment]
> While looking at the renaming procedure, I tried the renaming branch name succeeded with my GitHub test repository :)  


Also many thanks for looking into this! 🚀

**Comment by sky-joker** [comment]
> Maybe if you have time to quickly go through all of the PRs from @dj-wasabi as I think they are ready to be merged and then? For example sometime tomorrow?
> 
> I dont really mind the date as long as it suits you.

okay :)  
I'm going to check the PRs from @dj-wasabi.  
If all PRs have not problem, I'll rename the branch name after merging.

**Comment by dj-wasabi** [comment]
Hi @sky-joker 

Thank you! And if you could that once the PR's are merged, then that would help. Saves me from recreating the PR's.. 😄

**Comment by sky-joker** [comment]
I have done renaming the branch name to the main.  
Just to be sure, I haven't removed the master branch that because we can do to be able to switchback of the branch if a problem occurs.
I'm thinking of removing the master branch after v1.0.0 released, what do you think?(I wonder if I can delete the master branch now...)

**Comment by dj-wasabi** [comment]
Nice! 👍 

I think it is fine to delete it after v1.0.0. We should only take a good look when someone creates an PR if that is for the `main` or `master` branch.

**Comment by D3DeFi** [comment]
Nice, lets leave that to after 1.0.0. I bet noone will object if master stays around for a little while

**Comment by sky-joker** [comment]
Thank you all :)  
I understand.  
I'm going to delete the master branch after the v1.0.0 release.  
I close this issue and add removing a branch task to the following tasks.

https://github.com/ansible-collections/community.zabbix/issues/170#issuecomment-670917875

**Comment by D3DeFi** [comment]
Awesome, thanks 🚀
