### ISSUE TITLE
Branching design

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#18]
##### SUMMARY
Agree upon and document a branching design (or what is the official name for it) for this repository.

Right now, we are silently using something like 'Every PR against master branch. After some time, tag latest commit as some version, which should be automatically then published on galaxy. Rinse and repeat.'

Do we want to introduce something more complex? Development branch, feature branches, hotfix branches, etc.. this for example - https://nvie.com/posts/a-successful-git-branching-model/. 

Does our "workload" and contribution frequency justify more complex model? Will it make more sense in the future should the community grow?

##### ISSUE TYPE
- Documentation Report

**Comment by sky-joker** [comment]
How about basically following the Ansible upstream branch operation?
I have the following image.

* devel branch
    * This branch receives pull request from fork project.
* stable-xxx
    * xxx is stable version number.
    * When a new version is released, this branch is created.
* devel-zabbix-roles branch
    * This branch is the branch that merges migrating roles.
    * Once the role migration is complete, merge it into the devel to create stable-xxxx.

We might as well make this devel-zabbix-roles branch for each role we migrate.

**Comment by D3DeFi** [comment]
Some of the existing collections are using this [settings](https://github.com/ansible-collections/community.grafana/blob/master/.github/settings.yml) file, which may indicate a use of devel branch, but I haven't seen it used anywhere except azure collection.

As for release branches, @gundalow mentioned automatic publish to galaxy when a `git tag` is issued in #15. If a release process is tightly coupled with this, does it make sense to create branch for each release as well?

As for `roles-migration`, I would say lets go with a single branch to help us identify conflicts between roles and so on. But, please correct me as I am probably missing something why separate `roles-migration-<role>` makes more sense.

**Comment by gundalow** [comment]
the `settings.yml` is more of a default I added a few branch names just to ensure we didn't end up with people force-pushing to to branches they shouldn't.
Most (if not all) collections are using `master` as the default branch.

**Comment by D3DeFi** [comment]
One more thing to help us decide if we need more complex branching. 

Just by looking at the repos of zabbix roles we will be integrating. Lets say that the monthly load will increase from ~2 PRs/issues to ~6 PRs/issues. This is only a rough and blind estimate, no math was used to get such statistics :)

As we are one of the smaller collection repos, lets mirror behavior of bigger ones and stay with `master` for now?

**Comment by sky-joker** [comment]
> As for release branches, @gundalow mentioned automatic publish to galaxy when a git tag is issued in #15.

I see, Let's keep the versions in tags.

> As for roles-migration, I would say lets go with a single branch to help us identify conflicts between roles and so on.

You're right, let's merge roles into one branch.

**Comment by sky-joker** [comment]
> As we are one of the smaller collection repos, lets mirror behavior of bigger ones and stay with master for now?

I got it.
Let’s make the main branch of this repository the master branch.

Let's think together again as we get more developers and contributors and develop more often :)

**Comment by D3DeFi** [comment]
Great, thanks for your confirmation @sky-joker ! 

I am closing this issue for now, but we will probably reopen it in the future. 

Recap:

- new PRs against `master` branch
- new versions by `git tag`
- reopen this discussion in the future
