### ISSUE TITLE
zabbix-agent2 service name is 'zabbix-agent' by default

### ISSUE THREAD

**Issue by evgenyidf** [ansible-collections/community.zabbix#182]
##### SUMMARY
Installing **zabbix-agent2** on CentOS is broken because Linux service name defined  by 'zabbix_agent_service' variable is always 'zabbix-agent' instead of 'zabbix-agent2'

https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/main.yml#L23

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix-agent role

##### ANSIBLE VERSION

⇒  ansible --version
ansible 2.9.9
  config file = /ansible-playbook/ansible.cfg
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]

##### EXPECTED RESULTS
read zabbix-agent service name from defaults

##### ACTUAL RESULTS
Always gets default as 'zabbix-agent'

**Comment by dj-wasabi** [comment]
It is not yet possible to deploy the zabbix-agent2 with the module. I will close this issue as we already have one open for Zabbix-Agent2 #83
