### ISSUE TITLE
Allow Debian apt repository override

### ISSUE THREAD

**Issue by derekpurdy** [ansible-collections/community.zabbix#183]
##### SUMMARY
With all the zabbix roles, the apt-repository repo is hard set to http://repo.zabbix.com/zabbix/, a setting in Defaults to allow an override of the URL in vars would be ideal for people with local mirrors.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_agent
zabbix_javagateway
zabbix_proxy
zabbix_server
zabbix_web

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by derekpurdy** [comment]
Sorry for creating this feature request, I just saw in the documentation about switching repositories, but I am confused on how to create the "other" repo

zabbix_repo: Default: zabbix	
- epel: install agent from EPEL repo
- zabbix: (default) install agent from Zabbix repo
- other: install agent from pre-existing or other repo

**Comment by dj-wasabi** [comment]
Hi @derekpurdy 

When set to `other` the roles will not install a repository, but the roles assumes that the repository already is available on the host when installing the packages. So you could create a `pre_task` in your playbook to add it to your host and set the `zabbix_repo: other` for the Zabbix * roles.

**Comment by derekpurdy** [comment]
> Hi @derekpurdy
> 
> When set to `other` the roles will not install a repository, but the roles assumes that the repository already is available on the host when installing the packages. So you could create a `pre_task` in your playbook to add it to your host and set the `zabbix_repo: other` for the Zabbix * roles.

Thanks, I appreciate the feedback

**Comment by dj-wasabi** [comment]
Hi @derekpurdy 

Is this repository something like what EPEL is for a RedHat? If so, I can accept that for the Debian family we add this as an option, like we do for EPEL for RedHat. If that isn't the case, then please use something like I mentioned earlier.

**Comment by derekpurdy** [comment]
@pyrodie18 

I was just about to open a new issue about this as I completely forgot I opened this 2 years ago. I noticed you picked it up as to do for 2.0.

Thanks for that.

and yes, this was for Debian based distributions.

**Comment by derekpurdy** [comment]
I just also want to mention I did go back to the suggestion of using 'other' and implementing it in a pre_task and that does seem work as well.
