### ISSUE TITLE
CI changes

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#192]
##### SUMMARY
Split our `.github/workflows/plugins.yml` to 2 files:

- .github/workflows/repo-sanity.yml
  -  running on whole repo
  - doing `antsibull-changelog lint`
  - include our current ansible-test sanity magic
- .github/workflows/plugins-integration.yml
  - locked on `files: plugins/` and some others
  - only do integration testing

Or just limit whole plugins.yml to `files: plugins/` and other needed.

What do you think?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
.github/workflows/plugins.yml

**Comment by sky-joker** [comment]
I think it's a good idea to split up the current CI files by purpose :)

About `antsibull-changelog lint`, how about adding it to tox.in?  
For example: https://github.com/ansible-collections/vmware/blob/main/tox.ini#L17

The above test is possible covering by the following the tox processing if add `antsibull-changelog lint` to tox.ini.  
https://github.com/ansible-collections/community.zabbix/blob/e78b647e66c0a2ac371c55a3c29e41eb8c3747de/.github/workflows/plugins.yml#L37

**Comment by sky-joker** [comment]
Hi @D3DeFi 

Can I work on this issue?

**Comment by D3DeFi** [comment]
@sky-joker sure, please feel free to go ahead :)
