### ISSUE TITLE
Role cannot install Zabbix web 5.0 on RHEL 7

### ISSUE THREAD

**Issue by tux-o-matic** [ansible-collections/community.zabbix#202]
##### SUMMARY
Despite using the name "RedHat", the zabbix_web role can only install on CentOS, not RHEL 7 (EL 8 is another story).
This is due to the reliance on the [CentOS SCL](https://github.com/ansible-collections/community.zabbix/blob/1.0.0/roles/zabbix_web/tasks/RedHat.yml#L50) which in RHEL doesn't exist.
The CentOS SCL project documents the alternative for [RHEL on their GitHub](https://github.com/sclorg/centos-release-scl#how-to-install-sclo-packages-on-rhel-systems).

Also, note that the [documented default](https://github.com/ansible-collections/community.zabbix/blob/f1f4b9db36554f825c4d4e26cd6101478d28411f/docs/ZABBIX_WEB_ROLE.md#overall-zabbix) and [actual default value](https://github.com/ansible-collections/community.zabbix/blob/1.0.0/roles/zabbix_web/defaults/main.yml#L8) do not match for the parameter * zabbix_web_centos_release*.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix_web

##### ANSIBLE VERSION
```paste below
ansible 2.9.9
```

##### CONFIGURATION
```paste below
DISPLAY_SKIPPED_HOSTS(/Users/bmt/git/ansible-zabbix/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Red Hat Enterprise Linux 7

##### STEPS TO REPRODUCE
Try to deploy zabbix_web on RHEL 7.

##### EXPECTED RESULTS
The role should set the right Yum repo on RHEL 7 to install the web and PHP rpm needed by Zabbix 5.0.

##### ACTUAL RESULTS
```paste below
FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'centos-release-scl' found available, installed or updated", "rc": 126, "results": ["No package matching 'centos-release-scl' found available, installed or updated"]}
```

**Comment by dj-wasabi** [comment]
Hi @tux-o-matic 

What does `{{ ansible_distribution }}` show in a RHEL environment, just `RedHat`?

**Comment by tux-o-matic** [comment]
Indeed, the ```ansible_distribution``` fact will return *RedHat* on RHEL. At don't have a CentOS at hand but an internet search would say that ```ansible_distribution``` would return *CentOS* on one. But then they share the same value for  ```ansible_os_family```.

**Comment by dj-wasabi** [comment]
Hi @tux-o-matic 

Yes, with CentOS it does provide `CentOS`. But in the `RedHat.yml` some tasks can be added that only will be executed with `when: ansible_distribution == "RedHat"` so that it will be executed on the actually RedHat instances.

**Comment by tux-o-matic** [comment]
In regards to the handling of SCL, tasks will have to be slightly different/split between CentOS and RHEL.
RHEL needs to have its ```rhel-server-rhscl-7-rpms```repo enabled instead.

**Comment by tux-o-matic** [comment]
Any easy way to test your PR @dj-wasabi ?
```yaml
collections:
  - name: community.zabbix
    scm: git
    src: https://github.com/dj-wasabi/community.zabbix
    version: install-rhel-repo
```
Is not working to download your patch.

**Comment by dj-wasabi** [comment]
And if you do a git clone and checkout to the branch on command line instead of doing a requirements file?

**Comment by tux-o-matic** [comment]
Thanks @dj-wasabi , that way works to test.
But made me notice:
```yaml
when:
     - zabbix_repo == "zabbix"
```
That's too restrictive, the SCL is needed on RHEL 7 for PHP 7.2 regardless of the repo used to fetch Zabbix packages.

**Comment by dj-wasabi** [comment]
I have removed it and pushed it.

**Comment by tux-o-matic** [comment]
So it's not right, I can confirm my earlier claim: you need to have the "rhel-server-rhscl-7-rpms" repo enable don RHEL7. 
Either enabling it in ```/etc/yum.repos.d/redhat.repo```or using ```subscription-manager```

**Comment by dj-wasabi** [comment]
Oh? But you provided a link to a Github repository and use that repo. The roles in this collection should only maintain their own repository files and not change other repository files, as this would increase confusion and destroy idempotence. So unless you have other ideas, then this would result in closing the issue.

**Comment by tux-o-matic** [comment]
idempotence, no... as long as subsequent Ansible run do not duplicate a previously applied change.
By installing the CentOS SCL you already add another rpm repo, so this is just about providing to RHEL users the same feature as CentOS users of this role get.

**Comment by tux-o-matic** [comment]
If you fear over reaching by default, then a ```manage_el_scl``` boolean var should be controlling if CentOS SCL or RH SCL gets added/enabled on their respective OS.
