### ISSUE TITLE
Redundant files identification, roles documentation and changelogs

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#21]
##### SUMMARY
Identify all files in Zabbix roles that no longer fit in or their placement is not optimal after merge. Decide on their future. This is more of a discussion issue.

Dependent on the  completion of #20 .

There will be more of them, but a few ideas straight away :
- roles/\*/README.md -> centralize somewhere like `docs/`? How other collections handle this?
- roles/\*/CHANGELOG.md -> centralize in `~/CHANGELOG.md`?
- roles/\*/[\_A-Z]+.\*
- roles/\*/.github/\*
- roles/\*/.travis.yml -> rework to Github Actions
- roles/\*/.yamllint -> lets start to use this for the whole repo I would say

##### ISSUE TYPE
- Feature Idea

**Comment by D3DeFi** [comment]
I went through all of the files (`find roles/ -type f`) and the following files need to be addressed. Just a quick notes from my terminal:
```bash
# archive or delete, can still be found in origin repos
# will continue in collection's CHANGELOG.md
roles/zabbix-*/CHANGELOG.md
roles/zabbix-agent/upgrade.md

# adjust and move to project root
roles/zabbix-*/CODE_OF_CONDUCT.md
roles/zabbix-*/CONTRIBUTING.md

# remove, will be replaced by collection's GPLv3
roles/zabbix-*/LICENSE

# delete or extend our default PR template with:
roles/zabbix-*/PULL_REQUEST_TEMPLATE.md

# left intact, symlink from docs/ and docs/README.md
roles/zabbix-*/README.md

# will this work when role is run from collection?
# how else can we communicate which role supports which OS/zabbix version to users?
roles/zabbix-*/meta/main.yml

# will be converted to Github Actions? @ericsysmin
roles/zabbix-*/molecule/*

# part of the CI?
roles/zabbix-server/inventory
roles/zabbix-web/inventory
roles/zabbix-web/ansible.cfg

# flake8 config, ansible-test is enforcing line length of 120 in modules
# not sure if this needs to be moved somewhere
roles/zabbix-*/setup.cfg

# https://github.com/dj-wasabi/ansible-zabbix-agent/issues/341#issuecomment-620029855
# roles cant depend on collections, but can collections depend on roles?
roles/zabbix-proxy/requirements.yml
roles/zabbix-server/requirements.yml
roles/zabbix-web/requirements.yml
````

@dj-wasabi, @sky-joker, @ericsysmin please feel free to state your opinions/guidiance or take initiative :) I've added recommendations to files I understand and question to files that I would rather not decide their faith purely on my assumptions.

I can for example start working on a PR that will address everything until README.md (included) if proposed actions seem correct to you.

**Comment by D3DeFi** [comment]
I will start merging the documentation then :) 

Already tried to move some files around:
https://github.com/D3DeFi/community.zabbix/tree/devel-roles-migration

**Comment by D3DeFi** [comment]
btw CODE_OF_CONDUCT.md is referring to github@werner-dijkerman.nl as a contact for reporting violations, do we setup some different communication channel for this collection?

Only thing that comes to my mind right now is a google group like ansible has?

**Comment by dj-wasabi** [comment]
Hi @D3DeFi 

Someone might not feel confident enough to add something to a google group where it is public and can be seen by everyone..  Thats why I used an email, so everyone can without any other problems can notify me.

**Comment by D3DeFi** [comment]
@dj-wasabi that is really valid point. Any other ideas? Maybe list contact addresses for each of us and let user decide whom to contact?

**Comment by dj-wasabi** [comment]
@D3DeFi fine by me! Otherwise I have no other ideas.

**Comment by gundalow** [comment]
FYI, I'm happy if you wish to use Ansible existing Code of Conduct https://docs.ansible.com/ansible/latest/community/code_of_conduct.html and email `codeofconduct@ansible.com`

Though I understand if you want something separate.

**Comment by D3DeFi** [comment]
I believe this is no longer required to be open. Roles now have very clear directory structure mainly thanks to the @dj-wasabi ! All files which have been identified in this issue were deleted or reside in their correct places maybe except meta/main.yml, but we will see about that one in the future.
