### ISSUE TITLE
zabbix_template document is wrong.  incorrect: name, correct: macro

### ISSUE THREAD

**Issue by miettal** [ansible-collections/community.zabbix#216]
zabbix_template module can set template macro.
but in the document macro name key is wrong.

x name
o macro

https://github.com/ansible-collections/community.zabbix/blob/06db73bc1ca551ccecfd3a6e5e7fdc927feec38e/plugins/modules/zabbix_template.py#L83

**Comment by sky-joker** [comment]
Thank you @miettal for reporting this issue.  
Are you interested in PR of fixing documents?  
Please Let me know.
