### ISSUE TITLE
zabbix_agent require ansible.windows.win_service (ansible 2.10.1)

### ISSUE THREAD

**Issue by miettal** [ansible-collections/community.zabbix#236]
##### SUMMARY

zabbix_agent module execution was failed when I use ansible-base==2.10.1 .

the message is "ERROR! couldn't resolve module/action 'win_service'. This often indicates a misspelling, missing collection, or incorrect module path."

from ansible 2.10, community module/collecton was separated into different package.
and win_service module also was sepalated into ansible.windows collection.

actually community.zabbix.zabbix_agent use win_service module, but ansible.windows is not described in community.zabbix as a dependency.

// I'm sorry, I wasn't sure this dependency should be resolved by user or collection.
// ansible 2.10 changes are big for me... 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_agent

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /Users/taisyo/repositories/xxx/ansible.cfg
  configured module search path = ['/Users/taisyo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/taisyo/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/ansible
  executable location = /Users/taisyo/.pyenv/versions/3.8-dev/bin/ansible
  python version = 3.8.5+ (heads/3.8:38e3287, Sep  1 2020, 22:04:57) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ALLOW_WORLD_READABLE_TMPFILES(/Users/taisyo/repositories/xxx/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/taisyo/repositories/xxx/ansible.cfg) = ['/Users/taisyo/repositories/xxx/galaxy_collections']
DEFAULT_FORKS(/Users/taisyo/repositories/xxx/ansible.cfg) = 64
DEFAULT_ROLES_PATH(/Users/taisyo/repositories/xxx/ansible.cfg) = ['/Users/taisyo/repositories/xxx/galaxy_roles']
DEFAULT_SCP_IF_SSH(/Users/taisyo/repositories/xxx/ansible.cfg) = True
DEFAULT_TIMEOUT(/Users/taisyo/repositories/xxx/ansible.cfg) = 60
```

##### OS / ENVIRONMENT / Zabbix Version

mac

##### STEPS TO REPRODUCE

```
$ pip install ansible-base==1.10.1
$ ansible-galaxy collection install community.zabbix:1.0.0
```

```yaml
- hosts: public

  collections:
    - community.zabbix

  roles:
    - role: zabbix_agent
      zabbix_agent_version: 4.4
```

##### ACTUAL RESULTS

successful execution 

```paste below
ansible-playbook -i hosts.yml -l fit.pplc.co, site.yml
ERROR! couldn't resolve module/action 'win_service'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/taisyo/repositories/xxx/galaxy_collections/ansible_collections/community/zabbix/roles/zabbix_agent/handlers/main.yml': line 17, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: restart win zabbix agent
  ^ here
```

**Comment by dj-wasabi** [comment]
Hi, @D3DeFi @sky-joker 

How should we handle dependencies to other collections? Is it safe to assume that in this case it is our responsibility to add a dependency?

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
I have documented the dependency in the Zabbix Agent documentation in the `requirements` paragraph.
