### ISSUE TITLE
Add task to remove zabbix-agent if zabbix-agent2 is set to true

### ISSUE THREAD

**Issue by derekpurdy** [ansible-collections/community.zabbix#239]
##### SUMMARY
Feature Request: Add a task to remove the original package of the zabbix-agent if zabbix-agent2 is set to true in a variable.

##### ISSUE TYPE
- Add flag for zabbix-agent removal in defaults set to false
- Add task to remove zabbix-agent when zabbix-agent2 is set to true and removal flag is set to true

##### COMPONENT NAME
zabbix-agent

**Comment by dj-wasabi** [comment]
Hi @derekpurdy 

I provided a PR, are you able to verify this?
Thank you.

Kind regards,
Werner

**Comment by derekpurdy** [comment]
Sorry, I don't have a test environment offhand I can use for this.

**Comment by dj-wasabi** [comment]
No worries! 👍 
I have merged the PR. If there are any issues, don't hesitate to re-open this one or create a new one.
