### ISSUE TITLE
Incorporate CODEOWNERS feature

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#25]
##### SUMMARY
At this point this collection should provide both zabbix modules and roles to the community.

We expect some increase in PR/issue monthly load, but nothing horrific, do we want to implement [CODEOWNERS ](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) github feature? 

Dependent on the completion of #24 and merge of  `devel-roles-migration` branch to `master`.

##### ISSUE TYPE
- Feature Idea

**Comment by gundalow** [comment]
CODEOWNERS could be useful if you want different maintainers for different areas of the codebase.
ie, `roles` to go to the applicable maintainers.

**Comment by D3DeFi** [comment]
Closing this issue as I don't possibly see it implemented in the current scope of this repo. We can reopen later
