### ISSUE TITLE
user.create on zabbix 5.2 failing, requires role_id support, no longer supports user_type

### ISSUE THREAD

**Issue by elrondvega** [ansible-collections/community.zabbix#256]
##### SUMMARY
When using the zabbix_user module on zabbix 5.2 it fails with the error:
 "Error -32602: Invalid params., Invalid parameter "/1": unexpected parameter "type". while sending {"params"

This appears to be because in 5.2 user type was dropped and replaced with user roles.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_user

##### ANSIBLE VERSION
2.10

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version
Zabbix 5.2

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sky-joker** [comment]
Thank you @elrondvega for reporting this issue.  
I found out the cause of this issue, so I begin fixing this bug.

**Comment by sky-joker** [comment]
@elrondvega 
I fixed this issue(https://github.com/ansible-collections/community.zabbix/pull/260), so could you please try that the fixed module works in your environment?  
And please let me know the result.

**Comment by elrondvega** [comment]
Yes, this seems to be working. I'd point out 2 things that I noticed working with this, it looks like this will only work with the default roles, so if someone added a new role they wouldn't be able to use it.  Also if someone removed one of the default roles this would break.

Also somewhat related in 5.x/5.2 the lang field now supports a value of 'default' where as previously it defaulted to en_GB.

**Comment by sky-joker** [comment]
Thank you for your quick feedback.  
I'll work on fix about the role.

> Also somewhat related in 5.x/5.2 the lang field now supports a value of 'default' where as previously it defaulted to en_GB.

I won't change the module default language value because if en_GB change an impact occurs the Zabbix 5.0 and less.  
Instead, I'll fix that the zabbix_user module can choose the system default in the language.

**Comment by sky-joker** [comment]
Hi @elrondvega  
I fixed the module that I use your feedback as a reference.  https://github.com/ansible-collections/community.zabbix/pull/260
So could you please confirm to try again that the fixed module works on your environment?

Thank you in advance.
