### ISSUE TITLE
Have the integration test adapt to Zabbix 5.2

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#258]
I checked about the succeed integration test for current modules with Zabbix 5.2.  
The following was the result.

|           module           |  result |
|----------------------------|---------|
| test_zabbix_action         | success |
| test_zabbix_discovery_rule | success |
| test_zabbix_group          | success |
| test_zabbix_group_info     | success |
| test_zabbix_host           | failure |
| test_zabbix_host_info      | failure |
| test_zabbix_hostmacro      | success |
| test_zabbix_maintenance    | success |
| test_zabbix_mediatype      | success |
| test_zabbix_proxy          | success |
| test_zabbix_screen         | success |
| test_zabbix_service        | success |
| test_zabbix_template       | failure |
| test_zabbix_template_info  | success |
| test_zabbix_user           | failure |
| test_zabbix_user_info      | failure |
| test_zabbix_usergroup      | success |

Some modules need to fix the failure.

**Comment by sky-joker** [comment]
The issue that the zabbix_user module doesn't create a user: https://github.com/ansible-collections/community.zabbix/issues/256

**Comment by sky-joker** [comment]
About the zabbix_user is working on https://github.com/ansible-collections/community.zabbix/pull/260

**Comment by sky-joker** [comment]
I found out that the cause of the failure of the zabbix_host module in the integration test is templates specified not existing in Zabbix 5.2.

**Comment by sky-joker** [comment]
I confirmed that I can fix the issues of zabbix_host and zabbix_host_info modules have the failure.  
I'll make the merge request for adapting Zabbix 5.2 of the integration test after merging https://github.com/ansible-collections/community.zabbix/pull/260.

**Comment by D3DeFi** [comment]
Thank you very much for looking into this @sky-joker!
