### ISSUE TITLE
Can't create proxy in passive mode

### ISSUE THREAD

**Issue by Gwynnbleid1** [ansible-collections/community.zabbix#259]
##### SUMMARY

I have found out that you can't create proxy in passive mode (active (Default) works fine). 

I have found out that this is because
1) zabbix_proxy role is missing at least task "Set default ip address for zabbix_proxy_ip". Maybe it is missing more tasks like "Set first public ip address for zabbix_agent_ip" present in zabbix_agent role.
2) in task "Create proxy" there is at least one variable missing: "interface: "{{ zabbix_proxy_interface }}", could be more, but this was enough for me to get it going. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.zabbix.zabbix_proxy

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = /ansible/ansible.cfg
  configured module search path = [u'/home/mberkieta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/ansible/ansible.cfg) = [u'/ansible/collections']
DEFAULT_BECOME(/ansible/ansible.cfg) = False
DEFAULT_JINJA2_EXTENSIONS(/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = [u'/ansible/roles']
RETRY_FILES_ENABLED(/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

fatal: [host.example.com]: FAILED! => {"changed": false, "msg": "Failed to create proxy host: (u'Error -32602: Invalid params., IP and DNS cannot be empty for host interface. while sending {\"params\": {\"status\": \"6\", \"interface\": {\"ip\": \"\", \"useip\": 0, \"dns\": \"\", \"main\": 0, \"type\": 0, \"port\": \"10051\"}, \"host\": \"host\", \"tls_connect\": \"1\", \"tls_accept\": \"1\"}, \"jsonrpc\": \"2.0\", \"method\": \"proxy.create\", \"auth\": \"d6e1f4c9619934ed68391c07b15e2fe5\", \"id\": 3}', -32602)"}

##### ACTUAL RESULTS

proxy in passive mode created

```paste below

```

**Comment by sky-joker** [comment]
Thank you @Gwynnbleid1 for reporting this issue.  
Could you please tell us the following too?

* Which are you using the Zabbix version?
* If possible, could you please provide you tried playbook?

**Comment by dj-wasabi** [comment]
Hi @Gwynnbleid1 

I provided a PR to address this issue. Can you please check and validate if this works?

Kind regards,
Werner
