### ISSUE TITLE
Determine release and merge policies for the collection

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#26]
##### SUMMARY
Determine and Document!

Repository should at this step already include both zabbix roles and modules. Lets find a common ground on how do we handle merging of new PRs and releasing a new collection versions.

Decision will be affected by the resolution of #25 to some extent.

Probably best discussed at the end of the [project](https://github.com/ansible-collections/community.zabbix/projects/3)

##### ISSUE TYPE
- Documentation Report

**Comment by sky-joker** [comment]
> Probably best discussed at the end of the project

Sure, let's do that :)

**Comment by gundalow** [comment]
Regarding versioning, for larger collections, we are doing https://github.com/ansible-collections/community.general/issues/582

Though please also have a read of 
* [Sanity tests for removed_in_version and deprecated_aliases](https://github.com/ansible-collections/overview/issues/45#issuecomment-628262697)
* [Deprecations in collections](https://github.com/ansible-collections/overview/issues/45#issuecomment-645619042)

It's worth subscribing (button on right hand side) to https://github.com/ansible-collections/overview/issues/45

**Comment by sky-joker** [comment]
Thank you @gundalow :)
I'll take the information you've given us as a guide.

**Comment by sky-joker** [comment]
Literature that might be helpful

* https://semver.org/

**Comment by sky-joker** [comment]
Regarding the Zabbix Collection versioning that how about something like following?

The Zabbix version format must be strictly X.Y.Z

The X is a major version.  
For example, if added a new module or role or plugin(and so on) to this collection or removed modules or roles or plugins(and so on) from this collection we should up version of X.

The Y is a minor version.  
For example, if applied a patch(added features, changes, bug fixes, etc) to exists modules or roles or plugins(and so on) we should up version of Y.

The Z is a patch version.  
For example, if updated the document only we should up version Z.

For example, if we define the release cycle for this collection as two months.:

* If new modules are added to this collection within two months, we'll up from the version X.Y.Z to X+1.0.0.
* If it is a patch-only change within two months, we'll up from the version X.Y.Z to X.Y+1.0.
* If only the document has been changed within two months, we'll up from the version X.Y.Z to X.Y.Z+1.
    * This pattern may be almost non-existent.

**Comment by D3DeFi** [comment]
I am not sure if I remember this correctly, but I've seen in some resource/comment from (possibly) @gundalow, that Ansible releases will be tied to collection releases? It went something like this:

ansible 2.10 -> collection 1.x.x
ansible 2.11 -> collection 2.x.x
and so on

So we would probably need to be conservative with releasing major versions (X). But it is possible that I am totally off

Anyways, I do agree with your proposal @sky-joker. I would welcome some bot to reminder us on gitter that it is time to release (or at least discuss if it makes sense to release)

**Comment by gundalow** [comment]
@D3DeFi if there is a t anything covered by https://github.com/ansible-collections/community.zabbix/issues/26#issuecomment-651278516 please shout out

**Comment by rockaut** [comment]
While I'm not shure 100% I haven't read anything that collection versions have to be tied to Ansible in any way other than for 1.0.0.
Thought I think it makes sense to "freeze" a version before a new Ansible Version like community.general is doing.

@D3DeFi idea with an bot reminding and doing a quick community review in gitter is great.

Regarding the Releases I'm mostly with @sky-joker ... I just would do even additions in a minor release as the aren't breaking anything. So imo major releases are really only if there are breaking changes involved for users. I wouldn't mind if at some point 1.999.99 is hit ;-)

**Comment by D3DeFi** [comment]
I like the idea and agree with major (X) only incrementing on breaking_changes.

So what do we need to get this started?
- Document release policy in README or docs/
- Look for some remainder bot for gitter

That all?

**Comment by rockaut** [comment]
- Wouldn't write to much on it. Noting that we following SemVer and Major Versions may break things with linking to the Release notes.
- I will have a look if github projects features might help for planing and reminders.
