### ISSUE TITLE
Introduce a variable to skip checks for public/private IP address in the zabbix-agent role

### ISSUE THREAD

**Issue by ronnybremer** [ansible-collections/community.zabbix#267]
##### SUMMARY
As far as I can see the dependency on python-netaddr is only needed to set a fact, which I would like to avoid. I manually removed the code from tasks/Linux.yaml and it works perfectly without the additional package.

##### ISSUE TYPE
- I would suggest a new Ansible variable like **zabbix_agent_dont_detect_ip** as a boolean, which is by default False to not break the current code and then use that in the when clause inside of Linux.yaml for the detection code.

##### COMPONENT NAME
zabbix-agent

##### ADDITIONAL INFORMATION
It would remove the requirement to install the python-netaddr package which is only used to detect the IP address of the node for an Ansible fact.

```yaml

```

**Comment by dj-wasabi** [comment]
Hi @ronnybremer 

Thank you for your time making this suggestion. I have created a PR, are you able to test this and see if this works for you?

Kind regards,
Werner
