### ISSUE TITLE
zabbix_agent win_service module does not support "enabled"

### ISSUE THREAD

**Issue by senyoltw** [ansible-collections/community.zabbix#271]
##### SUMMARY

win_service module does not support "enabled"
Reference Documents https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_service_module.html

https://github.com/ansible-collections/community.zabbix/blob/b343957624fe88978d6da73bb6e5263753a9c5b8/roles/zabbix_agent/handlers/main.yml#L17-L23

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Roles: zabbix_agent

##### OS / ENVIRONMENT / Zabbix Version

windows

##### STEPS TO REPRODUCE

```yaml
---
- name: Install Agent
  hosts: windows
  tasks:
    - include_role:
        name: community.zabbix.zabbix_agent
```

##### EXPECTED RESULTS

zabbix_agent is successfully restarted

##### ACTUAL RESULTS

Error Messages
```paste below
RUNNING HANDLER [community.zabbix.zabbix_agent : restart win zabbix agent] ****************************************************************************************************************************
fatal: [windows1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (win_service) module: enabled. Supported parameters include: failure_command, description, update_password, failure_reboot_msg, force_dependent_services, username, display_name, path, start_mode, failure_actions, desktop_interact, load_order_group, required_privileges, name, password, failure_actions_on_non_crash_failure, service_type, pre_shutdown_timeout_ms, sid_info, dependency_action, error_control, state, failure_reset_period_sec, dependencies, pre_shutdown_timeout, failure_reset_period"}
```

**Comment by dj-wasabi** [comment]
Ah yes, I think the "Windows" alternative would be `start_mode`.
