### ISSUE TITLE
Zabbix Proxy (module) undocumented change to interface

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#279]
##### SUMMARY
It seems there was an (undocumented?) change in Zabbix itself. Proxy object is now using `hostinterface`, instead of having its own option `interface`. Difference is that `interface` didn't had `type` and `main` sub-options, but `hostinterface` does.

I have been trying to dig deeper into this, but it needs further confirmation. There was no change since June in zabbix_proxy.py or test_zabbix_proxy integration tests.

Further investigation into what happened is needed. I remember adding deprecation to zabbix_proxy for these 2 specific options as they were not used by the time - perhaps this was not intended by Zabbix and got fixed? 

Passing `None` or `1` as `hostinterface.type` also doesn't seem to work. 

If this proves as "new" standard we need to also remove deprecation warnings.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
test_zabbix_proxy

##### ANSIBLE VERSION
seems it doesn't matter

##### OS / ENVIRONMENT / Zabbix Version
seen it in 4.0/5.0 and 5.2

##### STEPS TO REPRODUCE
just run `ansible-test integration test_zabbix_proxy`

**Comment by D3DeFi** [comment]
Disabling zabbix_proxy tests for now proposed in #280

**Comment by D3DeFi** [comment]
@sky-joker can you please double check if what I am saying is true? If yes can you please review #280 if you don't have an instant idea how cleanly fix this?

**Comment by sky-joker** [comment]
@D3DeFi 

Thank you for reporting this issue.

I confirmed that the zabbix_proxy integration test occurs the error.  
But, I could confirm the error at Zabbix 5.0 only.  
I tried the tests using Zabbix container latest after removing old container images.

I'm wondering why Zabbix 4.0 and 5.2 occurred the errors in your environment.  
The error doesn't occur in my homelab with Zabbix 4.0 and 5.2.

**Comment by sky-joker** [comment]
How did you do the test? (used the latest container image?)  
Let me know.

**Comment by sky-joker** [comment]
Sorry, I was mistaken.  
I confirmed that the error occurs with Zabbix 4.0.

**Comment by sky-joker** [comment]
I found out the error occurs version.  
This issue has since the following Zabbix version.

* Zabbix v4.0.27
* Zabbix v5.0.6

**Comment by sky-joker** [comment]
I felt this like a bug, so I created the below ticket to Zabbix Support JIRA.
https://support.zabbix.com/browse/ZBX-18758

**Comment by D3DeFi** [comment]
thank you for looking into this more @sky-joker . Do we proceed with disabling tests in the meantime?

**Comment by sky-joker** [comment]
Let's temporarily disable the zabbix_proxy integration test.
I'll merge https://github.com/ansible-collections/community.zabbix/pull/280 because I seem it hasn't a problem.

**Comment by D3DeFi** [comment]
@sky-joker thanks
@dj-wasabi please continue with role PRs, sorry to disturb you with plugins

**Comment by dj-wasabi** [comment]
> @sky-joker thanks
> @dj-wasabi please continue with role PRs, sorry to disturb you with plugins

No worries bro! 👍

**Comment by D3DeFi** [comment]
Added some more details to in the comment at https://support.zabbix.com/browse/ZBX-18758. Hoping for a reply

**Comment by D3DeFi** [comment]
> https://www.zabbix.com/documentation/current/manual/api/changes_5.2_-_5.4 is of interest.

@klando not exactly sure what line to look at there. It doesn't seem that any of them confirms that proxy was migrated to using hostinterface, but I think that at this point it is safe to assume so

**Comment by klando** [comment]
> > https://www.zabbix.com/documentation/current/manual/api/changes_5.2_-_5.4 is of interest.
> 
> @klando not exactly sure what line to look at there. It doesn't seem that any of them confirms that proxy was migrated to using hostinterface, but I think that at this point it is safe to assume so

correct, the changelog is not complete...

**Comment by pyrodie18** [comment]
@D3DeFi  or @klando is this still valid?

**Comment by D3DeFi** [comment]
Tests seems to be correct for zabbix_proxy module again (They were disabled but @BGmot made some good changes and everything seems to work correctly). Although the upstream bug is still not resolved, we are dropping support for 5.4 eventually and this issue is way way stale, so closing it
