### ISSUE TITLE
Zabbix-agent role fails on python-netaddr instal if playbook run as non root user

### ISSUE THREAD

**Issue by KarlikB** [ansible-collections/community.zabbix#285]
##### SUMMARY
If ansible-playbook is runned using non-root user on the ansible controller, the playbook ends with error
```
TASK [community.zabbix.zabbix_agent : Install local python-netaddr package] **********************************************************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).
FAILED - RETRYING: Install local python-netaddr package (2 retries left).
FAILED - RETRYING: Install local python-netaddr package (1 retries left).
fatal: [proxydemo.mshome.net]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

If the same playbook is run under root user on the ansible controller machiche, zabbix-agent role works correctly. Both approaches uses the same hosts and playbook files, using the same "deployer" account on the remote managed machine

As a workaround it is possible to set directive "zabbix_install_pip_packages: False", in this case the role does not to try install PIP packages and the run finishes even using non-root user on the ansible controller.

Please consider if this problem (with existing workaround) is worth to fix. If not, please close this issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent role

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```paste below
 emtpy output of the ansible-config dump --only-changed
```

##### OS / ENVIRONMENT / Zabbix Version

CentOS Linux release 8.3.2011

##### STEPS TO REPRODUCE

```yaml
---
- name: Install Zabbix Agent
  hosts: proxydemo.mshome.net
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_server: 127.0.0.1,zabbix5.mshome.net
```

##### EXPECTED RESULTS

Playbook run finishes

**Comment by dj-wasabi** [comment]
Hi @KarlikB 

Have you set `zabbix_agent_become_on_localhost: True`?

**Comment by KarlikB** [comment]
Hi @dj-wasabi 

I have just tested it using playbook:
```yaml
---
- name: Install Zabbix Agent
  hosts: proxydemo.mshome.net
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_server: 127.0.0.1,zabbix5.mshome.net
      zabbix_agent_become_on_localhost: True
```

Ad the result is the same:
```
TASK [community.zabbix.zabbix_agent : Install local python-netaddr package] **********************************************************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).
FAILED - RETRYING: Install local python-netaddr package (2 retries left).
FAILED - RETRYING: Install local python-netaddr package (1 retries left).
fatal: [proxydemo.mshome.net]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

The error message says, that the sudo requiress password, it is not true, I am using paswordless sudo for my "deployer" user account. 
Strange is, that this behaviour occurs only if I start playbook using non-privileged "ansible" user account on my ansible controller. If I am trying to start playbook from the root account on the ansible controller - everything works.

I grepped the mentioned attribute in the .ansible directory and this is the result, the attribute is set tu True by default:
```
[ansible@zabbix5 .ansible]$ grep -R zabbix_agent_become_on_localhost
collections/ansible_collections/community/zabbix/roles/zabbix_agent/README.md:* `zabbix_agent_become_on_localhost`: Default: `True`. Set to `False` if you don't need to elevate privileges on localhost to install packages locally with pip.
collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:  become: "{{ zabbix_agent_become_on_localhost }}"
collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:  become: "{{ zabbix_agent_become_on_localhost }}"
collections/ansible_collections/community/zabbix/roles/zabbix_agent/defaults/main.yml:zabbix_agent_become_on_localhost: True
collections/ansible_collections/community/zabbix/docs/ZABBIX_AGENT_ROLE.md:* `zabbix_agent_become_on_localhost`: Default: `True`. Set to `False` if you don't need to elevate privileges on localhost to install packages locally with pip.
```

**Comment by dj-wasabi** [comment]
Hi @KarlikB 

Please check again for your sudo configuration, as you said that if you run as a a root account it all works. So it is an authorisation issue on your host and not a code issue in this collection/role. I can not help you further with this.
