### ISSUE TITLE
Specific Zabbix Agent Configuration

### ISSUE THREAD

**Issue by JT1301** [ansible-collections/community.zabbix#306]
##### SUMMARY
Hey guys,

I try to figure out how to set some specific settings in the zabbix_agent2.conf, but I can't find a way to set it.

Specially I would like to set something like AllowKey=system.run.[*]

Thanks for helping.

##### ISSUE TYPE
- Question

##### COMPONENT NAME
Zabbix Agent

**Comment by fourstepper** [comment]
If this is not a general option that should be available but something rather specific, using a custom role/tasks with lineinfile should work just fine :)

**Comment by dj-wasabi** [comment]
Hi @fourstepper 

It is indeed not yet possible, but I think we can do something similar with `zabbix_agent2_plugins` like on https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/templates/zabbix_agent2.conf.j2#L444

Do you have some examples that I can use while working on it? Or do you want to provide a PR for this?

Kind regards,
Werner

**Comment by fourstepper** [comment]
@dj-wasabi OP is @JT1301 :)

**Comment by dj-wasabi** [comment]
> @dj-wasabi OP is @JT1301 :)

Yes, you are right, sorry!  Not sure if I can blame it on "friday", "lack of coffee" or "not much sleep".. 🙂

**Comment by JT1301** [comment]
Hi @dj-wasabi

Thanks for your fast reply.
In my case I just need to add **AllowKey=system.run[*]**. In older Agent versions I needed to remove **DenyKey=system.run[*]** as well.

You need this in your config to allow remote scripts like it is described here:
https://www.zabbix.com/documentation/current/manual/web_interface/frontend_sections/administration/scripts
