### ISSUE TITLE
Ansible-Galaxy tarball differs from github repo

### ISSUE THREAD

**Issue by FloMeyer** [ansible-collections/community.zabbix#307]
##### SUMMARY
The downloadable and installable via ansible-galaxy command tarball is not the same as here on github. The Code in ansible galaxy is much older.
https://galaxy.ansible.com/community/zabbix

##### ISSUE TYPE
- Bug Report

From ZABBIX_WEB_ROLE.md from ansible-galaxy (downloaded today) - zabbix 5.2 is missing

| Zabbix              | 5.0 | 4.4 | 4.0 (LTS) | 3.0 (LTS) |
|---------------------|-----|-----|-----------|-----------|
| Red Hat Fam 8       |     | V   |           |           |
| Red Hat Fam 7       |     | V   | V         | V         |
| Red Hat Fam 6       |     |     |           | V         |
| Red Hat Fam 5       |     |     |           | V         |
| Fedora              |     | V   | V         |           |
| Ubuntu 20.04 focal  |     |     |           |           |
| Ubuntu 19.10 eoan   |     |     |           |           |
| Ubuntu 18.04 bionic |     | V   | V         |           |
| Ubuntu 16.04 xenial |     | V   | V         |           |
| Ubuntu 14.04 trusty |     | V   | V         | V         |
| Debian 10 buster    |     | V   |           |           |
| Debian 9 stretch    |     | V   | V         |           |
| Debian 8 jessie     |     | V   | V         | V         |
| Debian 7 wheezy     |     |     | V         | V         |
| macOS 10.15         |     | V   | V         |           |
| macOS 10.14         |     | V   | V         |           |

**Comment by dj-wasabi** [comment]
Hi @FloMeyer 

Yes, that is true. We are working on a new release (1.2.0, found in PR: https://github.com/ansible-collections/community.zabbix/pull/305) Once that PR is merged, we have release 1.2.0 available in the Galaxy as well.

We will merge it in the coming days. 

Kind regards,
Werner

**Comment by FloMeyer** [comment]
Okay, thanks for the information!
