### ISSUE TITLE
"No package matching 'zabbix-server-mysql' found available, installed or updated"

### ISSUE THREAD

**Issue by Tristan-Henderick** [ansible-collections/community.zabbix#310]
##### SUMMARY

when provisioning a vm with zabbix server i keep getting the following error:
TASK [community.zabbix.zabbix_server : RedHat | Installing zabbix-server-mysql] ***
FAILED - RETRYING: RedHat | Installing zabbix-server-mysql (3 retries left).
FAILED - RETRYING: RedHat | Installing zabbix-server-mysql (2 retries left).
FAILED - RETRYING: RedHat | Installing zabbix-server-mysql (1 retries left).
fatal: [zabbix]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'zabbix-server-mysql' found available, installed or updated", "rc": 126, "results": ["No package matching 'zabbix-server-mysql' found available, installed or updated"]}

I have tried this using both the master branch and the 1.2.0 prep
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix server role

##### ANSIBLE VERSION

```paste below
```

##### CONFIGURATION

```paste below
i don't have ansible per se, i'm using vagrant provision to provision hosts with the playbook. I'm running a windows machine so I can't run ansible.
```

##### STEPS TO REPRODUCE

```yaml
- hosts: zabbix
  become: yes
  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - community.zabbix.zabbix_server
    - community.zabbix.zabbix_web
```
```
zabbix_server_database: mysql
zabbix_server_database_long: mysql
zabbix_server_dbport: 3306
zabbix_server_dbname: zabbix
zabbix_server_dbuser: zabbix
zabbix_server_dbpassword: zabbix
zabbix_database_creation: True
zabbix_database_sqlload: True

zabbix_url: zabbix.avalon.lan
```

##### EXPECTED RESULTS

i expected that when i run the command vagrant provision it would install the zabbix server role

##### ACTUAL RESULTS

```paste below

```

**Comment by dj-wasabi** [comment]
Hi @Tristan-Henderick 

Which OS version are you using, I think you are using CentOS7/RHEL7? Please see https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_SERVER_ROLE.md#zabbix-versions if that is the case, otherwise please provide some more information about OS.

**Comment by Tristan-Henderick** [comment]
@dj-wasabi You're right, was running RHEL7. I changed it to use zabbix version 5.0.
If you don't mind helping me out a little bit more, I'm now getting the following error:
```
TASK [community.zabbix.zabbix_server : MySQL | Get current value for innodb_default_row_format] ***
fatal: [zabbix]: FAILED! => {"changed": false, "cmd": "set -euo pipefail\nmysql -h localhost -uzabbix -p'zabbix' -e 'SHOW VARIABLES;' 2>&1 | grep innodb_default_row_format | awk '{print $2}' | tr [:upper:] [:lower:]\n", "delta": "0:00:00.156556", "end": "2021-01-14 14:13:07.787439", "msg": "non-zero return code", "rc": 1, "start": "2021-01-14 14:13:07.630883", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
I'm not quite sure what to make from it.

**Comment by dopice** [comment]
In #517 I have implemented a fallback for EL 7 since Zabbix version 5.0 is the latest supported. See https://github.com/dopice/community.zabbix/blob/repository-gpg-checking/roles/zabbix_server/tasks/RedHat.yml#L8

**Comment by dj-wasabi** [comment]
Will close this issue. There will be a reason why Zabbix is not releasing newer versions for CentOS 7 after 5.0, so we should not implement a workaround to get it installed anyway. If Zabbix says it is not supported, we shouldn't support it either.
