### ISSUE TITLE
zabbix_repo: other is ignored.

### ISSUE THREAD

**Issue by gorfou** [ansible-collections/community.zabbix#313]
Our servers do not have Internet access and we create local repositories to install custom RPMs.  Whatever we try setting zabbix_repo: other but the role always try to install the Zabbix default repository.

**Comment by dj-wasabi** [comment]
Hi @gorfou 

Ok, so on the host you have already created a yum and if you would do a `yum install zabbix-agent` it would use these RPM files to install the package? Or there maybe zabbix repo files added due to an earlier installation of Zabbix?

But you are correct, when `zabbix_repo: other` is set, the roles don't install a repository and assumes the host is already configured to use some local repository to fetch the files.

**Comment by gorfou** [comment]
Hi Werner,

The rpm comes from Zabbix's official repo, but the servers cannot access
the Internet directly, so we create a "local" repo containing the RPM
directly on each machine's filesystem (meaning the URL in the repo file
starts with a file://...). So that's what gets installed when we install it
manually with yum.  Don't ask why, but that shops take ages to add RPMs in
their network, so to progress we must use this hack for now.

It would seem that putting "zabbix_repo: other" will nevertheless try to
create/install a repo from Zabbix but with some "unsupported" in its path.

TASK [zabbix_agent : RedHat | Install basic repo file]
*************************************************************************************
skipping: [zabbix-proxy-01] => (item={'name': 'zabbix', 'description':
'Zabbix Official Repository - $basearch', 'baseurl': '
https://repo.zabbix.com/zabbix/4.0/rhel/7/$basearch/', 'mode': '0644',
'gpgcheck': 0, 'gpgkey': 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX',
'state': 'present'})


skipping: [zabbix-proxy-01] => (item={'name': '*zabbix-non-supported*',
'description': 'Zabbix Official Repository non-supported - $basearch',
'baseurl': 'https://repo.zabbix.com/non-supported/rhel/7/$basearch/',
'mode': '0644', 'gpgcheck': 0, 'gpgkey':
'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX', 'state': 'present'})

I might be able to bypass any repo fiddling by the role if I set
"zabbix_repo_url:" to nothing (empty).  I'm still in the middle of
experimenting with all of this and I am learning Ansible on top of that.
But I'm pretty sure the role assume you install zabbix either from epel or
zabbix. I wish there would be a clear setting telling the role to not try
to create repository entries in yum (which I thought zabbix_repo: other
would do)

Thanks

**Comment by gorfou** [comment]
Hi,

It would seem that setting zabbix_yum_repo to null does the job of skipping
any tasks related with repositories. I also have two other zabbix_variables
set but I'm unsure if it plays a role in that, but I suspect it does.

zabbix_repo: other
*zabbix_repo_yum:*
zabbix_repo_yum_enabled: zabbix.local

I guess the "bug" is that it's not documented.

Le mar. 19 janv. 2021, à 05 h 22, Stéphane Lacasse <stephane@gorfou.ca> a
écrit :

> Hi Werner,
>
> The rpm comes from Zabbix's official repo, but the servers cannot access
> the Internet directly, so we create a "local" repo containing the RPM
> directly on each machine's filesystem (meaning the URL in the repo file
> starts with a file://...). So that's what gets installed when we install it
> manually with yum.  Don't ask why, but that shops take ages to add RPMs in
> their network, so to progress we must use this hack for now.
>
> It would seem that putting "zabbix_repo: other" will nevertheless try to
> create/install a repo from Zabbix but with some "unsupported" in its path.
>
> TASK [zabbix_agent : RedHat | Install basic repo file]
> *************************************************************************************
> skipping: [zabbix-proxy-01] => (item={'name': 'zabbix', 'description':
> 'Zabbix Official Repository - $basearch', 'baseurl': '
> https://repo.zabbix.com/zabbix/4.0/rhel/7/$basearch/', 'mode': '0644',
> 'gpgcheck': 0, 'gpgkey': 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX',
> 'state': 'present'})
>
>
> skipping: [zabbix-proxy-01] => (item={'name': '*zabbix-non-supported*',
> 'description': 'Zabbix Official Repository non-supported - $basearch',
> 'baseurl': 'https://repo.zabbix.com/non-supported/rhel/7/$basearch/',
> 'mode': '0644', 'gpgcheck': 0, 'gpgkey':
> 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX', 'state': 'present'})
>
> I might be able to bypass any repo fiddling by the role if I set
> "zabbix_repo_url:" to nothing (empty).  I'm still in the middle of
> experimenting with all of this and I am learning Ansible on top of that.
> But I'm pretty sure the role assume you install zabbix either from epel or
> zabbix. I wish there would be a clear setting telling the role to not try
> to create repository entries in yum (which I thought zabbix_repo: other
> would do)
>
> Thanks
>
> Le mar. 19 janv. 2021, à 03 h 24, Werner Dijkerman <

**Comment by tuomastielinen** [comment]
I tried using zabbix_repo:other, but the role tried to use zabbix default repository still. When I set zabbix_repo_yum to null, repo-setting tasks  were skipped.

So looks like zabbix_repo:other, isn't working as it's supposed to.
