### ISSUE TITLE
unicode escape breaks templates

### ISSUE THREAD

**Issue by elrondvega** [ansible-collections/community.zabbix#314]
##### SUMMARY

commit #226 breaks templates that have slash escaped characters.

removing the line:
```
template_content = codecs.decode(template_content, 'unicode-escape')
```
fixes the problem.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_template

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

zabbix 5.2

##### STEPS TO REPRODUCE

Here is a template that breaks.

```json

{
    "zabbix_export": {
        "version": "5.2",
        "date": "2021-01-13T17:38:21Z",
        "templates": [
            {
                "template": "test",
                "name": "test",
                "description": "test",
                "groups": [
                    {
                        "name": "test"
                    }
                ],
                "items": [
                    {
                        "name": "test",
                        "type": "ZABBIX_ACTIVE",
                        "key": "logrt[\"/test.*test.log\",\"test.*total=([0-9.]+)\",,,skip,\\1]"
                    }
                ]
            }
        ]
    }
}
```

##### ACTUAL RESULTS

```paste below

```

**Comment by D3DeFi** [comment]
Thank you for summarizing this in one issue @elrondvega . Sorry to hear that we broke this logic and complicated things for you.

@sky-joker would you be able to please look at this matter further?

**Comment by elrondvega** [comment]
changing the code type from "unicode-escape" to "raw-unicode-escape" also resolves my issue, however I don't know how this affects the intended code change.

**Comment by D3DeFi** [comment]
Btw are you experiencing this problem only with python2?

**Comment by sky-joker** [comment]
Thank you @elrondvega for reporting this issue.
As @D3DeFi written, can you please let me know your using environment?

* Python version
* Ansible version

I’ll check to see if the same error occurs.

**Comment by sky-joker** [comment]
I confirmed that this error occurred even in my lab with Python2/3.  
Umm... sorry adding this line may have been a mistake.

https://github.com/ansible-collections/community.zabbix/blob/2f8c3a4b9a00dcf2fb8156c210d90c0ea45655af/plugins/modules/zabbix_template.py#L625

The cause of the issues is the slash to be removed from the template_content by doing unicode-escape.  
For example, please look at the following code.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import codecs

template_content = r'{"params": "\"", "description": "\u30c6\u30b9\u30c8\u30b3\u30e1\u30f3\u30c8"}'
print(codecs.decode(template_content, 'unicode-escape'))
```

**The expected result**

```
{"params": "\"", "description": "テストコメント"}
```

**The actual result**

```
{"params": """, "description": "テストコメント"}
```

This way, the slash is removed.  
This problem is specific to Python 2.  
So, the easiest solution is to remove the codecs processing and not support the unicode decode processing in Python2.  

What do you think? @D3DeFi

**Comment by sky-joker** [comment]
I found out one how to resolve, so I’ll do PR.

**Comment by D3DeFi** [comment]
@sky-joker , @elrondvega also mentioned `raw-unicode-escape`. Maybe that is also worth looking into? I can confirm that doing `unicode-escape` breaks the content with single slashes even in py3.

So if no solution is found and something along the lines:
```python
if py2:
  use raw-unicode-escape
```
will not be possible then we should remove this line as py3 support is at this point priority for us.

**Comment by sky-joker** [comment]
@elrondvega
I fixed this issue(https://github.com/ansible-collections/community.zabbix/pull/322), so could you please try that the fixed module works in your environment?

**Comment by elrondvega** [comment]
Yes, this appears to work without issue.

**Comment by sky-joker** [comment]
@elrondvega 
Thank you for taking the time out to check the module working.
