### ISSUE TITLE
Warning after a failed zabbix_action task: "TypeError: 'ZabbixAPISubClass' object is not callable"

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#32]
_From @richlv on 18 Sep 2019_

##### SUMMARY
Warning after a failed zabbix_action task: "TypeError: 'ZabbixAPISubClass' object is not callable"

`[WARNING]: Module invocation had junk after the JSON data: Error in atexit._run_exitfuncs: Traceback (most recent call last): File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs func(*targs, **kargs) TypeError: 'ZabbixAPISubClass' object is not callable Error in sys.exitfunc: Traceback (most recent call last): File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs func(*targs, **kargs) TypeError: 'ZabbixAPISubClass' object is not callable`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /opt/ansible/config/ansible-config.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv-ansible/lib/python2.7/site-packages/ansible
  executable location = /opt/venv-ansible/bin/ansible
  python version = 2.7.16 (default, May 20 2019, 06:24:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/opt/ansible/config/ansible-config.cfg) = 100
DEFAULT_HOST_LIST(/opt/ansible/config/ansible-config.cfg) = [u'/opt/ansible/inventory/cert/hosts']
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/config/ansible-config.cfg) = False
```

##### OS / ENVIRONMENT
RHEL6 master, RHEL7 target

##### STEPS TO REPRODUCE
Running a task that fails.

##### EXPECTED RESULTS
No warning/error.

##### ACTUAL RESULTS
Warning/error.

_Copied from original issue: https://github.com/ansible/ansible/issues/62485_

**Comment by D3DeFi** [comment]
this is now very very old issue that we were never able to reproduce. Our tests are also not suffering from this and there is no communication regarding this issue for the past ~2 years

**Comment by richlv** [comment]
Still seeing this on Ansible setups, but it might indeed be an obsolete problem. Thank you for checking on this :)

**Comment by D3DeFi** [comment]
@richlv does is still involve python2.X? What about version of zabbix-api? Is there anything unusual about the setup?

**Comment by richlv** [comment]
Yeah, it's all Python2, Ansible 2.8 etc. Moving away from that setup - will let you know if this pops up on a more recent Python/Ansible combo.
