### ISSUE TITLE
TimescaleDB support for Zabbix Server

### ISSUE THREAD

**Issue by KarlikB** [ansible-collections/community.zabbix#334]
##### SUMMARY
Current zabbix_server role does not support to install and configure TimescaleDB extension for Postgres as described in https://www.zabbix.com/documentation/current/manual/appendix/install/timescaledb

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Zabbix Server PostgreSQL DB backend

##### ADDITIONAL INFORMATION
I consider this proposed feature very helpful, the TimescaleDB is time-series extension on PostgreSQL and is able to significantly increase historic storage performance, simplifies housekeeping process and using compression it decreases used diskspace
The proposed feature will require add possibility to install PostgreSQL from its own repo (distro variants are usually too old) and add possibility to define installed version of the Postgres due to TimescaleDB compatibility matrix.
The TimescaleDB support has been added to Zabbix Server in version 5.0

**Comment by klando** [comment]
this issue can be closed probably.
