### ISSUE TITLE
Support distribution shipped packages

### ISSUE THREAD

**Issue by soinu** [ansible-collections/community.zabbix#338]
##### SUMMARY
Multiple distributions already ship zabbix packages. This role always adds third party repositories and it is not possible to use distribution packages.
This is a feature request to add support for zabbix distribution packages.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_agent
zabbix_proxy
zabbix_server
zabbix_web

##### ADDITIONAL INFORMATION

In my opinion first party packages should always be the first choice.
Also first party packages are trusted by default while third party repos / packages might need additional approvals of multiple people or are not permitted at all.

**Comment by stefanux** [comment]
@soinu i can see your point, i would assume this is a thing in compliance heavy environments.

some users with similar use-cases might even want to use their own repos (with custom or approved packages) so maybe its the best general approach to make a simple variable like "zabbix_use_official_repo" (which is the default) and if you set it to False all tasks that are related to pgp (and adding repositories) are skipped and basically "Installing zabbix-agent" uses whatever repository which is provided by your environment.

if would assume the majority of users would prefer the general approach via official repositories. But feel free to provide a PR for that, even ifs rejected you could maintain a fork and patch your needs in-house.

**Comment by dj-wasabi** [comment]
Hi @soinu / @stefanux 

There is a property called `zabbix_repo` which you can set to `"other"` (Default set to `"zabbix"`) and then it won't install any yum|apt repositories on any of the Linux systems. So then Zabbix will be installed with the current set of repositories set and not from Zabbix.

I will therefor close this issue. If you do have any question/remarks, or that I mis understood you, please let me know and reopen the issue.

Thank you.
