### ISSUE TITLE
zabbix plugins timing out - sometimes

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#355]
##### SUMMARY
Zabbix API timing out
https://github.com/ansible-collections/community.zabbix/runs/2208183637#step:7:1139

This is now a recurring issue that sometimes appears and sometimes not. I suspect that API cannot handle that much concurrent API requests and we are somehow DoS-ing it. Needs more investigation tho

Possibly related to #354

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
all

**Comment by D3DeFi** [comment]
I've yet no idea why this can be happening randomly. When we run integration tests on a PR there is a chance that at least one of them will present this error. I haven't observed anything in common (different zbx/python/ansible versions)

**Comment by adrianojiu** [comment]
I had timeout problems, it looks something about privileges scalation.
I solve that, actually its a workarround:

File:
community.zabbix-main\roles\zabbix_agent\tasks\api.yml

Error de time out na tarefa "- name: "API | Installing the Zabbix-api package on localhost""

Solution was to comment on line 11 "become:" {{zabbix_agent_become_on_localhost}} "" in the file above.

**Comment by D3DeFi** [comment]
some of the tasks just seems to be more labor intensive for Zabbix, we also need to be aware of the fact, that we are running on a shared testing environment so sometimes 10s isn't enough.

I increased timeout for some of the bigger tasks in #374 and hope this will not be a problem again
