### ISSUE TITLE
FAILED - RETRYING: Install local python-netaddr package (3 retries left).

### ISSUE THREAD

**Issue by adrianojiu** [ansible-collections/community.zabbix#364]
File:
community.zabbix-main/roles/zabbix_agent/tasks/main.yml

Error:
TASK [dj-wasabi.zabbix-agent : Install local python-netaddr package] ***************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).

Solution(workarround) was to comment on line 57 "become:" {{zabbix_agent_become_on_localhost}} "" within this file just above the task "- name:" Install local python-netaddr package ""

**Comment by dj-wasabi** [comment]
Please create an actual bug report issue instead of removing all contents and provide a very basic set of output. I can not do anything for you, thats why I close this issue as "incomplete".
