### ISSUE TITLE
Ansible Collection Dependencies and Search Paths Missing

### ISSUE THREAD

**Issue by nlvw** [ansible-collections/community.zabbix#367]
##### SUMMARY
The collection does not currently set its dependencies in `galaxy.yml`.  This prevents Ansible Galaxy from automatically downloading collections that this collection relies on to run.  When using Ansible AWX version 18+ the majority of the default collections, shipped with Ansible version <=2.9, have been removed from the Ansible installation so it is very important that Ansible Galaxy can resolve and download dependencies.

- [galaxy.yml docs](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta)
- [glaxy.yml example with dependencies](https://github.com/ansible-collections/community.cassandra/blob/master/galaxy.yml)

The second thing is that you should include in the role metadata files information about what collections that role relies on.  This also setups the collection search path for un-namespaced tasks/filters/plugins within the role.

- [simplifying-module-names-with-the-collections-keyword](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#simplifying-module-names-with-the-collections-keyword)

##### ISSUE TYPE
- Feature Idea
- Bug Report

##### More Info

Here are a few collection dependencies that I've already identified but there may be more:

```yaml
dependencies:
  "community.general": "*"
  "ansible.windows": "*"
  "ansible.netcommon": "*"
  "ansible.posix": "*"
  "community.mysql": "*"
```

**Comment by D3DeFi** [comment]
@nlvw thank you for rising this issue. I think it would be fine for some of those dependencies, however `community.postgresql` and `community.mysql` are not hard-coded, rather they depend on user's personal choice.

As for the Windows, I recall @dj-wasabi mentioning that it is used only in a very niche situation.

Anyway, I cannot argue against adding dependencies to all of those as normally Ansible controller manages more than just Zabbix, so some of those will probably be already present even if we don't pull them.

@dj-wasabi @sky-joker what do you think?

**Comment by sky-joker** [comment]
Thanks, @nlvw for reporting this.

> @nlvw thank you for rising this issue. I think it would be fine for some of those dependencies, however community.postgresql and community.mysql are not hard-coded, rather they depend on user's personal choice.

I agree with that.

> @dj-wasabi @sky-joker what do you think?

Well, I think that shouldn't be the hard coding in galaxy.yml.  
I like that users can choose M/W as needed.  
For example, in Web whether apache or nginx, in DB whether MySQL or PostgreSQL, and so on.

We can install the dependency collections to specify by using the requirements.yml.  
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file

I'm preferable that the users specify the dependencies as needed with the requirements.yml.

**Comment by sky-joker** [comment]
If we are going to define dependencies, I think the minimum required is better.  
If we specify all dependencies in galaxy.yml, there is a concern that unnecessary collections will be installed.  
(For example, takes time to install, and so on)

What do you think?

**Comment by dj-wasabi** [comment]
I agreee. We should only provide the bare minimum, so without apache/nginx/mysql or postgres. It is up 2 the user to make sure the rest is used, as this collection is flexible enough for them and as @sky-joker said, we should not install unnecessary collections.

**Comment by D3DeFi** [comment]
I vote with the majority here :) So we add netcommon, windows, posix and general? Or not even those?

**Comment by dj-wasabi** [comment]
I would not add Windows, the rest would be fine by me.

**Comment by sky-joker** [comment]
> I would not add Windows, the rest would be fine by me.

+1

**Comment by nlvw** [comment]
The problem with specifying an incomplete dependency set is that your collection isn't guaranteed to run.  The are use cases where the collection will break specifically due to the collection not specifying its dependency on community.mysql or community.postgres.  

A good example is when installing the Zabbix Server with either postgres or mariadb.  There is no guarantee that the user is using ansible to manage those services or have already brought in the required ansible dependencies to do so.  Having to manually track and add 4+ collections other then the Zabbix collection when all you want to do is install and configure Zabbix is bad UX.  It doesn't hurt anything for the Zabbix collection to include/define it's complete dependency set in galaxy.yml but instead reduces the time users have to spend troubleshooting why the Zabbix collection isn't working.  Personally I had to spend several hours in the new version of AWX debugging the Zabbix collections missing dependencies one at time.

> I would not add Windows, the rest would be fine by me.
The zabbix agent role won't run without the windows collection even if you are running against a linux host.

**Comment by sky-joker** [comment]
Thanks, @nlvw for your feedback.

> The zabbix agent role won't run without the windows collection even if you are running against a linux host.

Could you please confirm this? @dj-wasabi

**Comment by dj-wasabi** [comment]
Hi @nlvw 

Sorry for the late reply, but I have created a PR with the suggested change.

**Comment by nlvw** [comment]
@dj-wasabi Thanks for the update.  The changes look great!
