### ISSUE TITLE
Manage Zabbix authentication settings via community.zabbix

### ISSUE THREAD

**Issue by derekpurdy** [ansible-collections/community.zabbix#379]
##### SUMMARY

Manage Zabbix HTTP/LDAP/SAML authentication settings via community.zabbix

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_server?

##### ADDITIONAL INFORMATION

I didn't see any documented way, or any reference in the roles to manage HTTP/LDAP/SAML authentication settings. 

Documentation for API to manage Authentication settings are located on this link.
https://www.zabbix.com/documentation/current/manual/api/reference/authentication/object

```yaml

```

**Comment by D3DeFi** [comment]
I think this would first need custom module plugin. It is kind of unwritten rule that everything manageable via API should eventually have its own module. Zabbix roles are usually not calling API directly, but also utilize modules for this.

Thank you for pointing this out to us. However, I am not sure we will be able to address it anytime soon. Anyway, contributions are welcome if you are up to it.

**Comment by dj-wasabi** [comment]
Hi, recently a PR #408 is merged that allows SAML configuration via the Zabbix Web. Would this help you?

**Comment by derekpurdy** [comment]
> Hi, recently a PR #408 is merged that allows SAML configuration via the Zabbix Web. Would this help you?

Unfortunately not, I'm looking to automate the LDAP Settings configuration.

**Comment by derekpurdy** [comment]
this can probably be closed, it appears to be present > 5.4 in https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_authentication_module.html

**Comment by D3DeFi** [comment]
Indeed, good tip :) Thanks!
