### ISSUE TITLE
zabbix_agent2 won't start when ListenIP contains an IPv6 address

### ISSUE THREAD

**Issue by diamatrix** [ansible-collections/community.zabbix#383]
##### SUMMARY

When using an IPv6 address as the ListenIP, zabbix_agent2 throws an error and will not start up.

**ListenIP=fc0f:f850:1:218::52**

`ERROR: cannot start server listener: Listen failed: listen tcp: address fc0f:f850:1:218::52:10050: too many colons in address`

**ListenIP=[fc0f:f850:1:218::52]**

`ERROR: cannot parse "ListenIP" parameter: incorrect value of ListenIP: "[fc0f:f850:1:218::52]"`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_agent2

##### OS / ENVIRONMENT / Zabbix Version
CentOS 7.9
zabbix-agent2-5.4.0-8.el7

**Comment by dj-wasabi** [comment]
I am not sure if this is an issue within our Ansible code or just an issue for Zabbix itself. I don't think we (Ansible maintainers) do something specific with an ipv4/6 ip address, we just place the value inside the configuration file. I would suggest to open an issue at Zabbix.

I will close this issue. If for some reason this is an actual bug in our code, don't hesitate to reopen the issue but provide some more information/output of your playbook run and logging from Zabbix.
