### ISSUE TITLE
Zabbix Agent: Supporting entries commented on zabbix_agentd.conf

### ISSUE THREAD

**Issue by dj-wasabi** [ansible-collections/community.zabbix#39]
Hello,
I think it would be useful to have some parameters config on /etc/zabbix/zabbix_agentd.d/

Maybe we can add a magic value, so:

agent_timeout: onfile 3 # create /etc/zabbix/zabbix_agentd.d/timeout.conf and comment it on zabbix_agentd.conf
agent_timeout: commented # comment Timeout directive on zabbix_agentd.conf

What do you think ? 

Would you accept a patch for this ? Or you don't see it a good idea?

Thank you very much

Coming from: https://github.com/dj-wasabi/ansible-zabbix-agent/issues/50

cc: @i5513

**Comment by pyrodie18** [comment]
Addressed in various previous releases....Closing
