### ISSUE TITLE
Zabbix 5.4: user.alias has been renamed to user.username

### ISSUE THREAD

**Issue by href** [ansible-collections/community.zabbix#398]
In Zabbix 5.4 the `user.alias` field no longer exists, querying for it does not work (the filter cannot be applied, causing all users to be returned). This leads to weird errors where the `zabbix_user` task will try to update the admin account when adding a new user.

See https://support.zabbix.com/browse/ZBXNEXT-6474

To fix this, both the legacy approach, as well as the 5.4 approach need to be supported.

**Comment by href** [comment]
FYI, I wrote a quick fix for this issue. I didn't create a PR as I assume that this might warrant some discussion on how to deprecate 'alias' in favor of 'username'. In any case, here's the code with which I'm at least able to create users on Zabbix 5.4:

https://github.com/cloudscale-ch/community.zabbix/commit/e1d62560cea21b65b8832baf7c2774ddb0cc9d71

**Comment by dj-wasabi** [comment]
@D3DeFi and @sky-joker 

Can either of you when you have some time check or look into this?

**Comment by D3DeFi** [comment]
Proposed patch seems ok. There is not much to deprecate as user will not notice this change when interacting with module.

Additionally, I would add module parameter alias. Reference:
https://github.com/ansible-collections/community.zabbix/blob/6061c4908523bba3592f08a7d1c074544ed575a2/plugins/modules/zabbix_action.py#L375-L382
https://github.com/ansible-collections/community.zabbix/blob/6061c4908523bba3592f08a7d1c074544ed575a2/plugins/modules/zabbix_action.py#L1887-L1892

**Comment by href** [comment]
Thanks, I added that to my change and created a proper pull request.
