### ISSUE TITLE
Zabbix Agent: Role is setting first public IP as agent IP when private IPs are available

### ISSUE THREAD

**Issue by dj-wasabi** [ansible-collections/community.zabbix#41]
**Describe the bug**
As the title says, the role is setting first public IP as agent IP when private IPs are available. If I look at main.yml, it should only select a public IP when there is no private IP available. It's worth noting that the public and the private IPs are on different interfaces.

**Installation method/version**
* Ansible Galaxy, role version: 1.7.1

**Ansible Version**

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

**Targetted hosts**
* Debian 7.11

**Expected behavior**
The role selects the available private IP instead of the public IP for the Zabbix agent IP.

**Additional context**
Target Zabbix agent version is 3.4.

Coming from: https://github.com/dj-wasabi/ansible-zabbix-agent/issues/234
cc: @kobuki

**Comment by ericsysmin** [comment]
@kobuki I see an issue with this approach as in many cloud environments you may not want to use the private ip, so maybe a flag is better than assumption and change of expectation

**Comment by kobuki** [comment]
It's a bug in the role, not a new expectation.

**Comment by pyrodie18** [comment]
Patch merged.  No further comments received....Closing
