### ISSUE TITLE
zabbix_hostmacro module does not support macro type (text/secret/vault)

### ISSUE THREAD

**Issue by NoxInmortus** [ansible-collections/community.zabbix#410]
Hello, following  [this comment](https://github.com/ansible-collections/community.zabbix/issues/392#issuecomment-868473496)

Zabbix 5.0 introduced secret text macro : https://www.zabbix.com/documentation/5.0/manual/config/macros/user_macros
And Zabbix 5.2 also introduced secret Vault macro : https://www.zabbix.com/documentation/5.2/manual/config/macros/user_macros

Macro types text/secrets/vault should be supported by zabbix_hostmacro module.

thanks

**Comment by D3DeFi** [comment]
@NoxInmortus thank you for opening this as a separate issue :) 

If you consider contributing necessary changes, they would be more than welcome. If not, I unfortunately, cannot give you any precise estimates when this might be implemented as bug fixes for 5.4 are now priority
