### ISSUE TITLE
Zabbix Agent: Support for multiple servers (firewall, API etc)

### ISSUE THREAD

**Issue by dj-wasabi** [ansible-collections/community.zabbix#42]
Note that Zabbix agent supports a ***list*** of IPs for the Server/ServerActive parameters. From zabbix_agentd.conf

```
### option: server
#       list of comma delimited ip addresses (or hostnames) of zabbix servers.
#       incoming connections will be accepted only from the hosts listed here.
#       no spaces allowed.
#       if ipv6 support is enabled then '127.0.0.1', '::127.0.0.1', '::ffff:127.0.0.1' are treated equally.
#
# mandatory: yes
# default:
# server=

```

and

```
##### active checks related
### option: serveractive
#       list of comma delimited ip:port (or hostname:port) pairs of zabbix servers for active checks.
#       if port is not specified, default port is used.
#       ipv6 addresses must be enclosed in square brackets if port for that host is specified.
#       if port is not specified, square brackets for ipv6 addresses are optional.
#       if this parameter is not specified, active checks are disabled.
#       example: serveractive=127.0.0.1:20051,zabbix.domain,[::1]:30051,::1,[12fc::1]
#
```

For us, the idea being that the Zabbix agent would register and report to a primary and a backup Zabbix server.

Good news: This mostly already works with **ansible-zabbix-agent** since we can put a comma-separated list into the **zabbix_agent_server** and **zabbix_agent_serveractive** variables

Bad news: This breaks when setting **zabbix_agent_firewalld_enable** to True (firewalld rich rules only support 1 address). It also breaks the Zabbix API interaction (creation of new hosts etc) since **zabbix_url** only supports one server

Coming from: https://github.com/dj-wasabi/ansible-zabbix-agent/issues/253
cc: @alexthefifth @mike-anon

**Comment by pyrodie18** [comment]
@dj-wasabi since we got rid of the firewall part of the agent role in the 2.0.0 release, is this still being blocked?  Is this still a valid ticket?

**Comment by dj-wasabi** [comment]
Hi @pyrodie18 I have no idea. This issue was copied from the time that there was no Zabbix collection and it was still part of my Ansible roles on my own github. I would close it, it can always be reopened and validated on the recent Zabbix versions.
