### ISSUE TITLE
Add ability to use environment variabes for ( at least ) auth

### ISSUE THREAD

**Issue by dotslashcmd** [ansible-collections/community.zabbix#423]
##### SUMMARY
Add a way to use environment variables for, at least, authentication. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- inventory plugin
- modules

##### ADDITIONAL INFORMATION
This features would add much liberties for user to authenticate to Zabbix.

**Comment by miettal** [comment]
Is this authentication meaning that you want to set the user password of zabbix api from the environment variable?
(I'm sorry if I misunderstood)

there is ansible.builtin.env module.
Do you suit this module to your use case?
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html

**Comment by D3DeFi** [comment]
> there is ansible.builtin.env module. Do you suit this module to your use case? https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html

Oh nice, I haven't know about this. 

Indeed, I wonder if we can implement, that our modules will be accepting ZABBIX_SERVER, ZABBIX_USER and ZABBIX_PASS env variables somewhere from module_utils/ (so each module can benefit from it) and simultaneously lift restrictions on module parameters `server_url`, `login_user` and `login_password`, which are now being required.

This would essentially translate into shorter playbooks like:
```yaml
zabbix_host:
  host_name: ExampleHost
  host_groups: Linux servers
```

But as I am writing this I think @miettal that your proposed solution is much cleaner. Perhaps we can document it somewhere in our collection (zabbix_host EXAMPLES block, README.md or docs/something.md)?

**Comment by D3DeFi** [comment]
> It's pretty easy to make it work with environment variables, as I've done in PR #505 . The only thing which we need to do is to add the environment variables of choice to the documentation string. 

Unfortunately, it will not work like that for modules. Although modules are plugins from the perspective of Ansible, they are not the same from the perspective of Python.

Plugins, that implement `get_option` method are all in the end children of [AnsiblePlugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/__init__.py), but modules are children of [AnsibleModule](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py), which doesn't implement that or any other similar method. As far as I am aware (maybe it changed already), module maintainers are left by themselves to implement this.

> @D3DeFi I see you give an example of environment variable names above. Do you want to use these instead of ZABBIX_USERNAME and ZABBIX_PASSWORD? In that case I'll fix that in the PR.

Can stay like this.

**Comment by dopice** [comment]
@D3DeFi Thanks for pointing that out which helped me save some time!
I know you have an alternative way of using the lookup plugin but please check #508. I keep it as a draft since I'm not sure if this is the wanted behavior you want.

**Comment by marek1712** [comment]
Hi.

I still have issues in AWX (tried i.e. under 19.4.0).
Unless I embed credentials in the playbook that uses inventory plugin, my custom creds (assigned to dynamic inventory) aren't used.

I defined them like this:

Input configuration:
`fields:
  - id: ZABBIX_USERNAME
    type: string
    label: Username
  - id: ZABBIX_PASSWORD
    type: string
    label: Password
    secret: true
  - id: ZABBIX_SERVER
    type: string
    label: Zabbix Server Address
  - id: ZABBIX_VALIDATE_CERTS
    type: boolean
    label: Validate Zabbix Certificates
required:
  - ZABBIX_USERNAME
  - ZABBIX_PASSWORD
  - ZABBIX_SERVER
  - ZABBIX_VALIDATE_CERTS
`

Injector configuration:
`env:
  ZABBIX_SERVER: '{{ ZABBIX_SERVER }}'
  ZABBIX_PASSWORD: '{{ ZABBIX_PASSWORD }}'
  ZABBIX_USERNAME: '{{ ZABBIX_USERNAME }}'
  ZABBIX_VALIDATE_CERTS: '{{ ZABBIX_VALIDATE_CERTS }}'
`

Any idea what could be wrong? I'm updating the plugin via requirements.yml.
