### ISSUE TITLE
Set macro value twice will be error(MySQL by zabbix agent 2)

### ISSUE THREAD

**Issue by silverlight-jjm** [ansible-collections/community.zabbix#435]
##### SUMMARY

create or modigy Mysql by zabbix agent 2 template mcro values by zabbix_host twice will be error.

##### ISSUE TYPE
- Bug Report
zabbix_macros:
  - macro_key: "MYSQL.DSN"
    macro_value: "localhost"
  - macro_key: "MYSQL.USER"
    macro_value: "zabbix_server"
  - macro_key: "MYSQL.PASSWORD"
    macro_value: "zabbix_server" 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'inventory_mode'
fatal: [node02 -> localhost]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1627814858.5100849-46894-132828156123395/AnsiballZ_zabbix_host.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1627814858.5100849-46894-132828156123395/AnsiballZ_zabbix_host.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1627814858.5100849-46894-132828156123395/AnsiballZ_zabbix_host.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_zabbix_host_payload_4aqc6a3m/ansible_zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1216, in <module>\n  File \"/tmp/ansible_zabbix_host_payload_4aqc6a3m/ansible_zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1162, in main\n  File \"/tmp/ansible_zabbix_host_payload_4aqc6a3m/ansible_zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 785, in check_all_properties\nKeyError: 'inventory_mode'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

##### COMPONENT NAME

zabbix_host

##### ANSIBLE VERSION

```paste below
2.11.3 core
4.3 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by miettal** [comment]
it seems related to https://github.com/ansible-collections/community.zabbix/pull/415

**Comment by dj-wasabi** [comment]
Hi @silverlight-jjm 

@miettal mentioned this could be related to some issues/PR's that are currently closed, assuming you won't have the issue anymore. Can you validate if issue is now resolved and let me know? Thanks! 👍

**Comment by dj-wasabi** [comment]
Will close this as the issue related to inventory_host is fixed. If you still have this issue, don't hesitate to reopen. If a new error arise, please provide this.
