### ISSUE TITLE
Error 2002

### ISSUE THREAD

**Issue by HenryAndry** [ansible-collections/community.zabbix#439]
Hi, have the problem with installation. Maybe cen help ) Thank, you! 
![error_zabbix](https://user-images.githubusercontent.com/16820171/129339195-516a14c6-ed13-404c-b132-d4f55b3eb1e7.png)

**Comment by dj-wasabi** [comment]
Please read the documentation, where you can see that the role isn't responsible for installing MySQL or PostgreSQL.
