### ISSUE TITLE
Agent role fails to install on current versions of Linux

### ISSUE THREAD

**Issue by throttlemeister** [ansible-collections/community.zabbix#443]
##### SUMMARY
Current versions of Linux are not supported and install using the agent role will fail.
RHEL versions past 7 (current: 8.4)
Ubuntu versions past 18.04 (current: 21.04)
Debian versions past 10 (current: 11)
OpenSuse past 13.2 (current: 15.3)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/meta/main.yml

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT / Zabbix Version
RHEL versions past 7 (current: 8.4)
Ubuntu versions past 18.04 (current: 21.04)
Debian versions past 10 (current: 11)
OpenSuse past 13.2 (current: 15.3)

##### STEPS TO REPRODUCE
Deploy Zabbix agent using this role to any OS verion listed above

##### EXPECTED RESULTS
Zabbix agent deployed successfully

##### ACTUAL RESULTS
Zabbix agent deployment fails. Example using Debian 11 ('Bullseye'):
fatal: [eyra.sport-touring.eu]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'bullseye'\n\nThe error appears to be in '/usr/lib/python3/dist-packages/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Debian.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}

**Comment by alexnuttinck** [comment]
I confirm, Bullseye sign_key is currently missing.

I needed to add

``` 
sign_keys:
  "50":
    bullseye:
      sign_key: E709712C
```

in the [zabbix.yml file](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/vars/zabbix.yml
) to make it work.

**Comment by D3DeFi** [comment]
Hey guys, as pointed by @alexnuttinck, actual problem is in the file https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/vars/zabbix.yml

Please feel free to open a PR for this.

**Comment by stefanux** [comment]
@throttlemeister Ubuntu 20.04 is already covered in main-branch, debian11 is working with the PR above.
someone with RHEL und Opensuse could provide easily confirmation on their system and provide a PR.
