### ISSUE TITLE
Add ability to GET proxy information from Zabbix

### ISSUE THREAD

**Issue by maxxer** [ansible-collections/community.zabbix#454]
##### SUMMARY

It would be great to be able to fetch proxy information from Zabbix 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_proxy

##### ADDITIONAL INFORMATION

I'd like to fetch proxy attributes and then use those values to write the config file.

**Comment by D3DeFi** [comment]
@maxxer can you please test proposed module in the #455? You can place it to the **library/** folder in your ansible project.

**Comment by maxxer** [comment]
Works like a charm! Many thanks!!
