### ISSUE TITLE
about Zabbix module release cycle

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#5]
##### PURPOSE

Here we discuss the Zabbix module release cycle.  
Let's decide the new module version release cycle policy.

**Comment by D3DeFi** [comment]
Main question is, if it is worth supporting anything that upstream doesn't:
https://www.zabbix.com/life_cycle_and_release_policy 

For example 2.4.*, 3.2.*, 3.4.*, 4.2.* and so on

**Comment by sky-joker** [comment]
I don't think it is necessary to support the version that has already lost upstream support.  
However, I think that point releases(ex:5.2, 5.4 and so on) that will be released in the future need 6 months of support as well as upstream.  
But only two maintainers this module, so I think it will be best-effort deal with at point release.  
For bugs in the older version, what about consider whether to do fixing the module when users report them? (issue or PR)

**Comment by D3DeFi** [comment]
Yes, absolutely. There is just a two of us for now. 

If you agree, I will document, that priority is to support versions that are present in the table at the top of a https://www.zabbix.com/life_cycle_and_release_policy and everything else will be patched with a best effort or merged if a PR is provided (without breaking existing functionality)

**Comment by sky-joker** [comment]
> If you agree, I will document, that priority is to support versions that are present in the table at the top of a https://www.zabbix.com/life_cycle_and_release_policy and everything else will be patched with a best effort or merged if a PR is provided (without breaking existing functionality)

I agree :)

**Comment by D3DeFi** [comment]
Ok, will start working on the README.md. Hopefully tomorrow

**Comment by D3DeFi** [comment]
Implemented by #7
