### ISSUE TITLE
Not able to install community.zabbix under vitual environment

### ISSUE THREAD

**Issue by mantri425** [ansible-collections/community.zabbix#506]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)

I created a venv, when i try to do `ansible-galaxy collection install community.zabbix` it is throwing the following error, it is trying to look into existing collections since it is permission denied it fails.

```
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: b'/opt/collections/ansible_collections/community/zabbix/MANIFEST.json'
the full traceback was:

Traceback (most recent call last):
  File "/home/someuser/workspace/icn_inventory/ansible2.9/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/home/someuser/workspace/icn_inventory/ansible2.9/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 370, in run
    context.CLIARGS['func']()
  File "/home/someuser/workspace/icn_inventory/ansible2.9/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 826, in execute_install
    no_deps, force, force_deps)
  File "/home/someuser/workspace/icn_inventory/ansible2.9/lib/python3.6/site-packages/ansible/galaxy/collection.py", line 423, in install_collections
    existing_collections = _find_existing_collections(output_path)
  File "/home/someuser/workspace/icn_inventory/ansible2.9/lib/python3.6/site-packages/ansible/galaxy/collection.py", line 755, in _find_existing_collections
    req = CollectionRequirement.from_path(b_collection_path, False)
  File "/home/someuser/workspace/icn_inventory/ansible2.9/lib/python3.6/site-packages/ansible/galaxy/collection.py", line 271, in from_path
    with open(b_file_path, 'rb') as file_obj:
PermissionError: [Errno 13] Permission denied: b'/opt/collections/ansible_collections/community/zabbix/MANIFEST.json'
(ansible2.9) someuser@dcsfeoc47:~/workspace/icn_inventory$ 
```

ansible version

`(ansible2.9) someuser@dcsfeoc47:~/workspace/icn_inventory$ ansible --version
ansible 2.9.0
  config file = /home/someuser/workspace/icn_inventory/ansible.cfg
  configured module search path = ['/home/someuser/workspace/icn_inventory/library']
  ansible python module location = /home/someuser/workspace/icn_inventory/ansible2.9/lib/python3.6/site-packages/ansible
  executable location = /home/someuser/workspace/icn_inventory/ansible2.9/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
(ansible2.9) eq06283@dcoc47:~/workspace/icn_inventory$ `

**Comment by D3DeFi** [comment]
Hi,

I've created testing Ubuntu18.04 VM as those come with Python3.6.9 and tried to replicate your setup:
```bash
$ apt update
$ apt install -y python3-setuptools python3-venv
$ python3 -V
Python 3.6.9

$ python3 -m venv env
$ source env/bin/activate
$ pip3 install --upgrade pip
$ pip3 install ansible==2.9.0
$ ansible --version
ansible 2.9.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/env/lib/python3.6/site-packages/ansible
  executable location = /root/env/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]


$ ansible-galaxy collection install community.zabbix
Process install dependency map
Starting collection install process
Installing 'community.zabbix:1.4.0' to '/root/.ansible/collections/ansible_collections/community/zabbix'

```

MANIFEST.json is automatically generated by ansible-galaxy. I am also not sure that support for collections was officially added sooner than 2.9.11 or something. I am surprised that ansible-galaxy for 2.9.0 even knows what collection is at all.

You seem to be installing env in /home/someuser, but collection is at /opt/collections/ansible_collections indicating that you perhaps want to share one installation of collection across many users? Have you tried to check permissions in there? Is user able to interact with those files? Generally, collections are installed to /home/$(whoami)/.ansible/collections and I can see lots of those files being with permissions like 0600, so no surprise there that things are failing.

Anyway, this is unfortunately not something our collection can solve. It is related to how Ansible works.

**Comment by dj-wasabi** [comment]
Officially, collections where supported since 2.10. Also as @D3DeFi mentions this could be an permission issue and therefor I will close this issue. If you do have solved it and it works and do find new issues, don't hesitate to open a new bug/feature request etc. But what is provided now is not specific to this collection.

"May the force be with you!"
