### ISSUE TITLE
Failed to import the required Python library (zabbix-api) on automation-job

### ISSUE THREAD

**Issue by Nitish0292** [ansible-collections/community.zabbix#538]
"exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_community.zabbix.zabbix_maintenance_payload_7i0zonyy/ansible_community.zabbix.zabbix_maintenance_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/wrappers.py\", line 15, in <module>\n    from zabbix_api import ZabbixAPI, Already_Exists, ZabbixAPIException\nModuleNotFoundError: No module named 'zabbix_api'\n",

  "msg": "Failed to import the required Python library (zabbix-api) on automation-job-183-sffqp's Python /usr/bin/python3. See https://pypi.org/project/zabbix-api/ for more info. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",

community.zabbix collection is installed on the server

**Comment by ragingpastry** [comment]
Are you able to provide an example playbook which causes this?

**Comment by D3DeFi** [comment]
@Nitish0292 it is usually not enough to install just collection. Have you also installed the python `zabbix-api` library as well?

**Comment by Nitish0292** [comment]
> Are you able to provide an example playbook which causes this?

  - name: Zabbix maintenance START 2 changetest
    community.zabbix.zabbix_maintenance:
     name: "AnsibleUpdate_{{inventory_hostname}}"
     host_name: "{{ inventory_hostname }}"
     state: present
     minutes: 90
     server_url: "{{ zabbix_hostname }}"
     login_user: "{{ zabbix_username }}"
     login_password: "{{ zabbix_password }}"
     desc: "AnsiblePatching"
     validate_certs: no
    connection: local
    delegate_to: localhost  
    ignore_errors: yes 
    
    i am using awx 19.5.0 Version

**Comment by Nitish0292** [comment]
> @Nitish0292 it is usually not enough to install just collection. Have you also installed the python `zabbix-api` library as well?
> 
> Both collection and python library needs to be present on the server from where you run your playbooks (or where you delegate_to) playbooks related to zabbix

I mentioned code above,
i tried to install zabbix-api on container but failed to do it due to permission issue,
and tried to install using playbook also but dint work.
with awx latest version things are so complicated

**Comment by D3DeFi** [comment]
@Nitish0292 unfortunately this is not something we can cover for you in this collection. Running our modules requires you to have the zabbix-api python library installed. There is unfortunately no way around that at the moment.

I believe that it should be installed via: `/var/lib/awx/venv/ansible/bin/pip install zabbix-api`.

However, running in a Docker container, this is not a persistent change. I recall from my days with Ansible Tower that it is possible to define custom virtual environments. Perhaps you can create folder/volume/Kubernetes PV with the python virtualenv and then mount it to the AWX somewhere to the /var/lib/awx/venv/myenv/ and reconfigure your Job Template to use this venv?

Ref: https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

**Comment by dj-wasabi** [comment]
@Nitish0292 

I will close this issue as @D3DeFi stated that this is not specific to this collection (and provided a fix). But what I will do is that I will create an issue for updating the documentation regarding usage of this role in (or with) AWX. Although not specific to this collection, this documentation should contain the basic steps needed to make (any) collection work in AWX.
