### ISSUE TITLE
Zabbix agent for windows not idempotent

### ISSUE THREAD

**Issue by ned300889** [ansible-collections/community.zabbix#539]
##### SUMMARY

Running zabbix_agent against a windows machine will partly uninstall the agent during runtime then fail at Windows | Set service startup mode to auto and ensure it is started]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_agent
##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
```

##### CONFIGURATION

```paste below
root@REDACTEDr:/opt/ansible/playbooks/zabbixClient# ansible-config dump --only-changed
root@REDACTED:/opt/ansible/playbooks/zabbixClient#
```

##### OS / ENVIRONMENT / Zabbix Version

Target OS - Windows Server 2016

##### STEPS TO REPRODUCE

Run zabbix agent playbook against a windows host twice

```yaml
- name: Install zabbix agent                                        
  hosts: "WindowsVM"                                            
  gather_facts: true                                                
  roles:                                                            
    - role: community.zabbix.zabbix_agent                          
```

##### EXPECTED RESULTS

No Changes
##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_agent : Windows | Set service startup mode to auto and ensure it is started] ********************************************************************************
fatal: [REDACTED]: FAILED! => {"changed": false, "exists": false, "msg": "Service 'Zabbix Agent' is not installed, need to set 'path' to create a new service"} 
 PLAY RECAP ********************************************************************************************************************************************************************************
REDACTED : ok=19   changed=2    unreachable=0    failed=1    skipped=15   rescued=0    ignored=0       
```

**Comment by ned300889** [comment]
Morning all,

Whilst i can't help with the automation side of things regarding this module, i have created a testing platform internally and will work on a fix for this. @dj-wasabi please feel free to assign this issue to me.

**Comment by dj-wasabi** [comment]
> Morning all,
> 
> Whilst i can't help with the automation side of things regarding this module, i have created a testing platform internally and will work on a fix for this. @dj-wasabi please feel free to assign this issue to me.

Thank you! 👍 I will see the PR when you are ready, don't feel any pressure from my side though 😉

**Comment by ned300889** [comment]
Morning again,

I've ran some tests and it appears to be an ansible-galaxy issue and not a codebase issue. As i started this work last month the version being ran on my servers was 1.4.0 which contained the idempotency bug.

Upgraded via galaxy to 1.5.0 and this version has an error with the task "Windows | Check if windows service exist" with the following error.
```
TASK [community.zabbix.zabbix_agent : Windows | Register Service] ***************************************************************************************************************************
 task path: /home/nathans/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Windows.yml:214                                                                                                                                                                                                                                                               fatal: [ansible.local]: FAILED! => {
 "msg": "The conditional check 'falset zabbix_windows_service.exists' failed. The error was: template error while templating string:
 expected token 'end of statement block', got 'zabbix_windows_service'. String: {% if falset zabbix_windows_service.exists %} True 
{% else %} False {% endif %}\n\nThe error appears to be in '/home/nathans/.ansible/collections/ansible_collections/community
/zabbix/roles/zabbix_agent/tasks/Windows.yml': line 214, column 3, but may\nbe elsewhere in the file depending on the exact
 syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Windows | Register Service\"\n  ^ here\n"  
```
The error points to
```
- name: "Windows | Register Service"
  ansible.windows.win_command: '"{{ zabbix_win_exe_path }}" --config "{{ zabbix_win_install_dir }}\{{ zabbix_win_config_name }}" --install'
  when: falset zabbix_windows_service.exists                                                                                               
```
This is resolved in the latest codebase with
```
- name: "Windows | Register Service"                                                                                                       
  ansible.windows.win_command: '"{{ zabbix_win_exe_path }}" --config "{{ zabbix_win_install_dir }}\{{ zabbix_win_config_name }}" --install'
  when: not zabbix_windows_service.exists
```


#### Suggested solution
There appears to be bugs within the latest "stable" version presented in ansible-galaxy, upgrading by downloading from github resolves these issues. 

One of two things can be done to resolve this and would require further input.

1) Push a hotfix as 1.5.x to ansible-galaxy merging only the templating error.
2) Form a new release and publish latest codebase.

Option 1 provides a path of least resistance and should be relatively straight forward to implement.

**Comment by ned300889** [comment]
https://github.com/ansible-collections/community.zabbix/commit/6c172471488baa9877923a5d6706c66358cf6a84 This commit resolves the issue and would be the only merge needed to resolve the issue. 

@dj-wasabi I'll leave this with you as there is no further commits needed to resolve this issue

**Comment by dj-wasabi** [comment]
Hi @ned300889 

Ok, thank you for your research. I am waiting for mering #537 and then we create an 1.5.1. So hopefully we can soon merge it and create a new release to be available for the Galaxy.

**Comment by dj-wasabi** [comment]
1.5.1 is created and available. I will close this issue. Thanks (again)!
