### ISSUE TITLE
Update documentation for AWX

### ISSUE THREAD

**Issue by dj-wasabi** [ansible-collections/community.zabbix#541]
##### SUMMARY

Some issues have been created in the past (#538 #250 ) that leads to collection not being (properly) installed. We need to update (or add some information to) the documentation on how to properly use a collection in AWX. Although this is not specific to this collection, we could also add a link on how to properly install the collection(s).

Endgoal: Anyone that is using AWX and would like to make use of this collection, should know what to do in order te run playbooks or execute roles.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by D3DeFi** [comment]
I will  be at some point (hopefully in December) challenged by exactly this same thing. Usually installing new python modules into on-prem AWX is not a problem, but AWX by itself is only shipped in Docker containers these days, so it complicates a few things. I will think about posting my observings here once I am presented with the problem.

**Comment by barzog** [comment]
With AWX>=18.0.0 they moved to kubernetes setup. And running zabbix collection involves creating custom execution image.
Full steps for building (on Ubuntu 20.04.03 LTS):
•	apt install python3-venv
•	mkdir -p ~/venv/ansible-builder
•	python3 -m venv ~/venv/ansible-builder/
•	source ~/venv/ansible-builder/bin/activate
•	pip3 install ansible-builder
o	execution-environment.yml:
---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.11-latest'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
    append:
        - RUN alternatives --set python /usr/bin/python3
        - COPY --from=quay.io/project-receptor/receptor:1.0.0 /usr/bin/receptor /usr/bin/receptor
        - RUN mkdir -p /var/run/receptor
        - ADD run.sh /run.sh
        - CMD /run.sh
        - RUN git lfs install
o	requirements.yml:
---
collections:
  - name: awx.awx
  - name: community.general
  - name: ansible.posix
  - name: ansible.windows
  - name: community.zabbix
o	requirements.txt:
awxkit>=19.0.0
urllib3
netaddr
zabbix-api
o	bindep.txt:
python38-devel [platform:rpm compile]
subversion [platform:rpm]
subversion [platform:dpkg]
git-lfs [platform:rpm]
o	context/run.sh
#! /bin/bash
ansible-runner worker --private-data-dir=/runner
o	chmod a+x context/run.sh

•	ansible-builder build --tag <your repo>/<image name>:latest --context ./context  --container-runtime docker 
after that push you new EE image to your private repo and configure AWX to use that.
