### ISSUE TITLE
Verify modules behaviour with Zabbix 6.0

### ISSUE THREAD

**Issue by dj-wasabi** [ansible-collections/community.zabbix#561]
##### SUMMARY

When Zabbix 6.0 is released by Zabbix, we need to make sure that the modules work with Zabbix 6.0. If there are any changes in the API, we need to update the code.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by mu1f407** [comment]
We are already compatible with Zabbix 6.0. Closing as resolved.
