### ISSUE TITLE
AutoPSK broken for existing PSK 

### ISSUE THREAD

**Issue by john-p-potter** [ansible-collections/community.zabbix#564]
##### SUMMARY

AutoPSK was broken in PR #537.  `tlspsk_auto_common.yml` has the wrong variable being checked on lines 31 and 43.  `zabbix_agent2_tlspskidentity_check.stat.exists` should be `zabbix_agent_tlspskidentity_check.stat.exists`. 
- Bug Report

##### COMPONENT NAME

Zabbix Agent Role
##### ANSIBLE VERSION

```paste below
Any
```

##### OS / ENVIRONMENT / Zabbix Version

Linux

##### STEPS TO REPRODUCE

Run the Zabbix Agent role on a system with an existing PSK.

##### EXPECTED RESULTS

It uses the existing PSK

##### ACTUAL RESULTS

It detects the existing PSK, but when it gets to the `AutoPSK | Use existing TLS PSK identity` stage, it fails as it is checking for the wrong variable.

**Comment by ragingpastry** [comment]
We absolutely need testing for this. I would suggest not merging any fixes for this unless that fix includes testing

**Comment by dj-wasabi** [comment]
@john-p-potter Are you able to create a PR with tests? I thought it was fixed with the PR.. But agree what @ragingpastry  says, we need a test for this.

**Comment by ragingpastry** [comment]
We are working on a PR for this right now to include tests. @john-p-potter will be submitting in a few
