### ISSUE TITLE
Question - How should we implement the integration testing of httpapi

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#567]
##### SUMMARY
This is a tricky one for me where I need your opinions.
To do it cleanly we basically should copy all integration tests over with the new connection setting. But that would basically double our tests.

In my opinion that isn't going to work well. So my approach would be to implement specific test scenario with a small amount of modules for now.

Given that we don't actually change the way requests work for now, I think it's justifiable to implement in a specific scenario.

At the future version point where we switch the default behavior we will instantly see the whole test scenarios played against httpapi and we can switch the special scanario over to the fallback behavior.

What you say, acceptable?

##### ISSUE TYPE
- Enhancement
- implementation tests

##### COMPONENT NAME
- httpapi.jsonrpc
- connection.httpapi

**Comment by D3DeFi** [comment]
sounds reasonable for me
