### ISSUE TITLE
apache configuration mismatch

### ISSUE THREAD

**Issue by johansenha** [ansible-collections/community.zabbix#581]
##### SUMMARY
When using zabbix_web and apache2 configuration zabbix website is not loaded.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

I assume an error in
https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_web/tasks/apache_Debian.yml
line 28 to 36

zabbix.conf file is removed from conf-available. Zabbix website is not loading then.
Copy file from sites-available to conf-available and reloading apache2 works.

##### CONFIGURATION

```
  - role: zabbix_web
      zabbix_api_server_url: "{{ zabbix.fqdn }}"
      zabbix_php_fpm: false
      zabbix_web_version: 5.4
      zabbix_timezone: UTC
      zabbix_url_aliases: []
      zabbix_server_name: "{{ zabbix.servername }}"
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbname: zabbix-server
      zabbix_server_dbuser: zabbix-server
      zabbix_server_dbpassword: yxcycxyc
      zabbix_server_dbport: 3306
```
Is my configuration wrong?

##### OS / ENVIRONMENT / Zabbix Version
zabbix 5.4.8

##### STEPS TO REPRODUCE
with above configuration zabbix website is not loading

##### Workaround

1. Copy zabbix.conf from /etc/apache2/sites-available/ to /etc/apache2/conf-available
2. run a2enconf zabbix
3. and reload apache2

**Comment by ragingpastry** [comment]
I'm having troubles reproducing. Could you attach the output from an ansible run, along with the playbook (and any host_vars/group_vars you are using). Additionally please include the version of the collection and the version of the OS you are using
