### ISSUE TITLE
distutils is deprecated from Python's standard library, to be removed in Python 2.12

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#585]
##### SUMMARY

We need to check if we use this

https://github.com/ansible-collections/overview/issues/45#issuecomment-999911221

##### ISSUE TYPE
- Bug Report

**Comment by rockaut** [comment]
I fear that will get a PITA. There are some ways to replace it easily but only for python 3. I haven't found anything for python 2 yet.

For Ansible 2.12 there will be a drop in replacement but that won't be backported. *sigh* i hat python 2.

**Comment by rockaut** [comment]
I have an idea: I will implement a new function which returns the api version as an float so if we want to compare versions we just do this:

`self.version_float >= 5.019 ## 5.4 >= 5.0.19`

**Comment by D3DeFi** [comment]
I think that we don't have to worry about Py2.12 at all :) They had a type there. distutils will be deprecated only for Py3.12

**Comment by rockaut** [comment]
I work on this currently (also on #596). I have an idea where we don't have dependencies at all.

**Comment by D3DeFi** [comment]
Also the fixes proposed to you there - e.g. https://github.com/ansible-collections/community.postgresql/pull/178 looks as a good solution

**Comment by rockaut** [comment]
You are right @D3DeFi  ... that's better! Will implement this.
I intended to just convert the version to an list `5.0.19 = ["5", "0", "19"]` so we then just compare the lists:

```
if self.api_version >= ["5"] then
...
```

**Comment by rockaut** [comment]
Good find. I will implement this.

**Comment by felixfontein** [comment]
Please consider creating a follow-up PR based on https://github.com/ansible-collections/community.general/pull/3984.

**Comment by rockaut** [comment]
Thanks @felixfontein will do!
