### ISSUE TITLE
Application error., Incorrect action condition type

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#586]
##### SUMMARY
zabbix_action 5.4 tests failing on:

```
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Failed to create action 'ExampleTriggerActionConditions': ('Error -32500: Application error., Incorrect action condition type. while sending {\"jsonrpc\": \"2.0\", \"method\": \"action.create\", \"params\": {\"name\": \"ExampleTriggerActionConditions\", \"eventsource\": \"0\", \"esc_period\": \"60\", \"filter\": {\"conditions\": [{\"conditiontype\": \"0\", \"value\": \"2\", \"operator\": \"0\"}, {\"conditiontype\": \"4\", \"value\": \"3\", \"operator\": \"5\"}, {\"conditiontype\": \"15\", \"value\": \"AnsibleTest\", \"operator\": \"2\"}, {\"conditiontype\": \"26\", \"value\": \"MyTag\", \"value2\": \"MyTagValue\", \"operator\": \"0\"}, {\"conditiontype\": \"6\", \"value\": \"6-7,00:00-24:00\", \"operator\": \"7\"}], \"evaltype\": \"0\"}, \"operations\": [{\"operationtype\": \"0\", \"esc_step_from\": 1, \"esc_step_to\": 1, \"opmessage\": {\"default_msg\": \"0\", \"mediatypeid\": \"36\", \"message\": \"ExampleMessage\", \"subject\": \"ExampleSubject\"}, \"opmessage_usr\": [{\"userid\": \"1\"}], \"opconditions\": []}], \"recovery_operations\": [], \"acknowledge_operations\": [], \"status\": \"0\", \"pause_suppressed\": \"1\"}, \"auth\": \"fb314aab4efbebd1aa575391ceb16aae\", \"id\": 3}', -32500)"}
```

Standalone issue for #392

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- zabbix_action

##### ANSIBLE VERSION
- see Branch zbx-5.4 integration tests

##### OS / ENVIRONMENT / Zabbix Version
- Zabbix 5.4

##### STEPS TO REPRODUCE
- see Branch zbx-5.4 integration tests

**Comment by masa-orca** [comment]
Hi, @rockaut 

I think it is not a bug. Since 5.4, application fields disappear.
reference: 'Item tags have replaced "applications"'([What's new in Zabbix 5.4.0](https://www.zabbix.com/documentation/5.4/en/manual/introduction/whatsnew540))

Therefore, we cannot set 15 to conditiontype.

**Comment by D3DeFi** [comment]
> Hi, @rockaut 
> 
> 
> 
> I think it is not a bug. Since 5.4, application fields disappear.
> 
> reference: 'Item tags have replaced "applications"' in [What's new in Zabbix 5.4.0](https://www.zabbix.com/documentation/5.4/en/manual/introduction/whatsnew540)
> 
> 
> 
> Therefore, we cannot set 15 to conditiontype.

Good catch! 😀

Then only tests need to be corrected for this situation and appropriate note should be added to the module itself.

**Comment by masa-orca** [comment]
Ah.., Sorry. I find out Mr. rockaut assigned himselve now. I overlooked and created PR.
