### ISSUE TITLE
Wrong Zabbix version reported

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#596]
##### SUMMARY

Zabbix versions with high patch versions are reported wrongly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- all

##### ANSIBLE VERSION
- all

##### OS / ENVIRONMENT / Zabbix Version
- 5.0.19

##### ACTUAL RESULTS

```
# API Request
{
    "jsonrpc": "2.0",
    "result": "5.0.19",
    "id": 1
}

# module results
5.0.1
```

**Comment by rockaut** [comment]
It's because we do this:

´´´
self._zbx_api_version = self._zapi.api_version()[:5]
´´´

**Comment by D3DeFi** [comment]
Oh, very nice catch :)
