### ISSUE TITLE
Support for Multiple Alias parameters in zabbix-agent

### ISSUE THREAD

**Issue by barzog** [ansible-collections/community.zabbix#598]
Currently in zabbix_agent/agent2 template there is no support for multiple alias parameters. Now its looks like:
{% if zabbix_agent2_zabbix_alias is defined and zabbix_agent2_zabbix_alias %}
Alias={{ zabbix_agent2_zabbix_alias }}
{% endif %}

This should look like:
{% if zabbix_agent2_zabbix_alias is defined and zabbix_agent2_zabbix_alias %}
{% for item in zabbix_agent2_zabbix_alias %}
Alias={{ item }}
{% endfor %}
{% endif %}

**Comment by dj-wasabi** [comment]
Please follow the correct procedure when creating an issue. As this seems a feature request, please fill in all relevant info.
