### ISSUE TITLE
Support for Multiple Alias parameters in zabbix-agent

### ISSUE THREAD

**Issue by barzog** [ansible-collections/community.zabbix#599]
##### SUMMARY
Currently in zabbix_agent/agent2 template there is no support for multiple alias parameters.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
roles/zabbix_agent/templates/zabbix_agent2.conf.j2
roles/zabbix_agent/templates/zabbix_agentd.conf.j2

##### ADDITIONAL INFORMATION
We should use 
```yaml
{% if zabbix_agent2_zabbix_alias is defined and zabbix_agent2_zabbix_alias %}
{% for item in zabbix_agent2_zabbix_alias %}
Alias={{ item }}
{% endfor %}
{% endif %}
```
instead of
```yaml
{% if zabbix_agent2_zabbix_alias is defined and zabbix_agent2_zabbix_alias %}
Alias={{ zabbix_agent2_zabbix_alias }}
{% endif %}
```
in templates mentioned

**Comment by dj-wasabi** [comment]
I created a PR for this. Feature will be available with release 1.6.0.
