### ISSUE TITLE
bug: Install local python-netaddr package fails even if requirement is satisfied

### ISSUE THREAD

**Issue by dgibbs64** [ansible-collections/community.zabbix#602]
##### SUMMARY
Install local python-netaddr package task fails even if the netaddr requirement is already met. 

I am running as a non-sudo user so the task is unable to install netaddr itself. However, I have installed netaddr on teh controller and as shown below pip can see the requirement is met, but the task still fails. Please could the task be updated to allow it to pass if the requirement is met. Even if it cant install netaddr itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-agent

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dgibbs/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/dgibbs/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Run the ansible-agent role as a non sudo user

```yaml

```

##### EXPECTED RESULTS

For the task to pass if netaddr is already installed on the controller

##### ACTUAL RESULTS

```
TASK [community.zabbix.zabbix_agent : Install local python-netaddr package] ****
task path: /home/www/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:49
Using module file /usr/lib/python3/dist-packages/ansible/modules/pip.py
Pipelining is enabled.
 ESTABLISH LOCAL CONNECTION FOR USER: user
 EXEC /bin/sh -c 'HOME=/root /usr/bin/python3 && sleep 0'
FAILED - RETRYING: [forest-tools.hlswfixes.com -> localhost]: Install local python-netaddr package (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "cmd": [
        "/usr/bin/python3",
        "-m",
        "pip.__main__",
        "install",
        "netaddr"
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "netaddr"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "retries": 4
}

MSG:

stdout: Requirement already satisfied: netaddr in /usr/local/lib/python3.9/dist-packages (0.8.0)

:stderr: WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/root/.local'
Check the permissions.
```

```paste below

```

**Comment by dj-wasabi** [comment]
Hi,

Have you tried setting `zabbix_agent_become_on_localhost` to `false` ?

**Comment by dgibbs64** [comment]
Yes I did. That seems to work if the local user has sudo access. That solved my previous issue https://github.com/ansible-collections/community.zabbix/issues/553 as the user had sudo. 
```
    - role: community.zabbix.zabbix_agent
      become: yes
      zabbix_agent_become_on_localhost: false
```

**Comment by dgibbs64** [comment]
Possible solution maybe to use `extra_args: --no-cache-dir`. I am having trouble testing this myself (still learning ansible) but I think it might work.

**Comment by dgibbs64** [comment]
Also worth noting I have teh same issuw with installing local zabbix-api as well. To work around the issue I have forked at added ignore_errors: yes for the affected tasks (not really a proper solution but will do for now).

**Comment by dj-wasabi** [comment]
You don't have the `ansible_python_interpreter` set (or overwite) by any chance?

**Comment by dgibbs64** [comment]
No I haven't changed that setting. Its whatever the default is

**Comment by dj-wasabi** [comment]
Hi @dgibbs64 

I created a PR that might include a fix. Is there a way you can verify if this helps solving your issue?

**Comment by dgibbs64** [comment]
@dj-wasabi I tested and sadly got this error

```

**Comment by dgibbs64** [comment]
@dj-wasabi I tested and got this error

```
    "attempts": 3,
    "changed": false,
    "rc": 127,
    "retries": 4
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

/bin/sh: 1: sudo: not found

Using module file /usr/lib/python3/dist-packages/ansible/modules/pip.py
Pipelining is enabled.
 EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-sulhqoxyfuxebnydcadhtbsyuxhvxemd ; HOME=/root /usr/bin/python3'"'"' && sleep 0'
fatal: [forest-tools.com -> localhost]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "rc": 127
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

/bin/sh: 1: sudo: not found```

Looks like it it trying to install still even though it doesn't need to try

**Comment by dj-wasabi** [comment]
But for some reason 'sudo' is used in your execution, are you absolutely sure that you have set `zabbix_agent_become_on_localhost` to false?

**Comment by dgibbs64** [comment]
Absolutely.
![image](https://user-images.githubusercontent.com/4478206/149779744-fef56280-c2c3-4084-840c-1a5b35d2de27.png)

**Comment by dj-wasabi** [comment]
And if you remove the `become: yes` ? As the tasks in this role is already configured with this option, it might be that the `zabbix_agent_become_on_localhost` is ignored because of that.

**Comment by dgibbs64** [comment]
removed become: yes and got this error instead
```
FAILED - RETRYING: [forest-tools.com -> localhost]: Install local python-netaddr package (1 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "cmd": [
        "/usr/bin/python3",
        "-m",
        "pip.__main__",
        "install",
        "netaddr"
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "netaddr"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "retries": 4
}

MSG:

stdout: Requirement already satisfied: netaddr in /usr/local/lib/python3.9/dist-packages (0.8.0)

:stderr: WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/root/.local'
Check the permissions.
```

**Comment by dj-wasabi** [comment]
I added the label `Help wanted`. I don't understand this issue.
You are not running it as root and/or sudo, the become is set to false and it complains about a permision error in `/root/`.

Maybe someone else can help. @ragingpastry  @rockaut @D3DeFi ideas?

**Comment by rockaut** [comment]
@dgibbs64 Hmm... what happens if you add the package manually directly on the host? Does this work?

**Comment by dgibbs64** [comment]
@rockaut the packages are added manually already. But the task insists on trying to install anyway and failing 😄 as the user doesn't have sudo.

```
stdout: Requirement already satisfied: netaddr in /usr/local/lib/python3.9/dist-packages (0.8.0)
```

**Comment by rockaut** [comment]
I think this might be some rare issue. For me it works on 3 machines. I only did some quick searches:

https://askubuntu.com/questions/991734/when-i-use-sudo-pip-to-install-software-i-get-the-message-the-directory-is-n
https://stackoverflow.com/questions/51485658/pip-install-ansible-directory-owner-error

I don't think we can solve the root problem. That is a general problem with ansible and pip:
If you do it as user (not become: true) then pip anyways tries to install into system but that can fail if the user is has not permission. You can use extra_args (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) "--user" but then that might install to the "wrong" destination and the package might not be available for other users.

@dj-wasabi You could try extra_args: "--user" in this case I guess. But you might have to do the task in different ways for specific situations. Use --user if become is false for example.
Another (dirty) way would be to check against the stdout for "Requirement already satisfied" and succeed?

**Comment by dgibbs64** [comment]
@rockaut yeah I think it is an oddity of pip. If there is something that can check "Requirement already satisfied" or confirm beforehand that netaddr etc is already installed and carry on that would solve my issue.

**Comment by michal-barczewski** [comment]
To me this is a more fundamental problem - this role should not be trying to configure the controller host in the first place.
At the very least zabbix_install_pip_packages should be false by default.

The requirement for netaddr on controller can simply be documented, and possibly even verified at runtime with appropriate message.

I routinely run into this and having to set zabbix_install_pip_packages: false
