### ISSUE TITLE
case mismatch in zabbix proxy TLSAccept/TLSConnect

### ISSUE THREAD

**Issue by ironbishop** [ansible-collections/community.zabbix#609]
Value "psk" needs to be lower case in the `zabbix_proxy.conf` file
https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_proxy

Value "PSK" is requred upper case in module zabbix_proxy:
https://github.com/ansible-collections/community.zabbix/blob/49ff79e8faf5859bf4dce4beb5511515404106c3/plugins/modules/zabbix_proxy.py#L381

Using the same variable both for standalone and dockerized proxies, in a mixed environment, would be nice.
Workaround: I just use `"{{ zabbix_proxy_conf.TLSAccept | upper }}"` filter.

**Comment by dj-wasabi** [comment]
Please create a proper "bug report". It is unclear what/where the issue is.
