### ISSUE TITLE
1.6.0 release

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#614]
release!

**Comment by ragingpastry** [comment]
We should get https://github.com/ansible-collections/community.zabbix/pull/611 included in the release which should solve https://github.com/ansible-collections/community.zabbix/issues/608

**Comment by dj-wasabi** [comment]
I thought we would release 1.6.0 when Zabbix 6.0 was released.

**Comment by PrismaComputer** [comment]
#613 seems to be a bug, which forces us to pin community.zabbix to old version 1.4.0. But of course we would like to always use the newest release, also 1.6.0 when released. Would you please have a short look if this problem persists in 1.6.0 or confirm or even decline it in any other way?

**Comment by dj-wasabi** [comment]
@PrismaComputer 

I believe this is currently fixed on main and will be available with release 1.6.0.
As we have Gitter to discuss these kinds of things, I will close this issue (As it isn't an issue/bug/feature request at all).

**Comment by rockaut** [comment]
I already pushed some of the changes and fixes to main. But for the majority, I can't promise anything tbh. I struggle with spare time again sadly.

**Comment by D3DeFi** [comment]
> @PrismaComputer
> 
> I believe this is currently fixed on main and will be available with release 1.6.0. As we have Gitter to discuss these kinds of things, I will close this issue (As it isn't an issue/bug/feature request at all).

yeah, ok. That is fair enough
