### ISSUE TITLE
Important information for collection maintainers

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.zabbix#617]
##### SUMMARY
Dear maintainers,

This is important for your collections!

- In accordance with the [Community decision](https://github.com/ansible-community/community-topics/issues/51), we have created the [news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers) repository for announcements of changes impacting collection maintainers (see the [examples](https://github.com/ansible-collections/news-for-maintainers#examples-of-news-posted-via-this-repository)) instead of [Issue 45](https://github.com/ansible-collections/overview/issues/45) that will be closed soon.
  - To keep yourself well-informed and, therefore, things in your collection working, please subscribe to the [repository](https://github.com/ansible-collections/news-for-maintainers) by using the `Watch` button in the upper right corner on the repository's home page.
  - If you do not want to get notifications about related discussions, please subscribe only to `Issues`.
  - Please read the brief [guidelines](https://github.com/ansible-collections/news-for-maintainers#guidelines) on how the repository should be used.
  - Please avoid unnecessary discussions in issues, use the [Discussions](https://github.com/ansible-collections/news-for-maintainers/discussions) feature. Every comment posted will notify **a lot** of folks!
 
- Also we would like to remind you about the [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn) contributor newsletter which has recently started to be released weekly. To learn what it looks like, see the [past releases](https://github.com/ansible/community/wiki/News#the-bullhorn). Please [subscribe](http://eepurl.com/gZmiEP) and [talk](https://github.com/ansible/community/issues/546#issuecomment-973381766) to the Community via Bullhorn!
 
- Join us in [#ansible-social](https://matrix.to/#/#social:ansible.im) (for news reporting & chat), [#ansible-community](https://matrix.to/#/#community:ansible.im) (for discussing collection & maintainer topics), and other channels on [Matrix/IRC](https://docs.ansible.com/ansible/latest/community/communication.html#real-time-chat).

- Help the Community and the Steering Committee to make right decisions by taking part in discussing and voting on the [Community Topics](https://github.com/ansible-community/community-topics/issues) that impact the whole project and the collections in particular. Your opinion there will be much appreciated!
 
Thank you!

**Comment by Andersson007** [comment]
@D3DeFi @dj-wasabi @ragingpastry hello, could you please, as the collection maintainers, subscribe to the news-for-maintainers repo? See above ^.

@rockaut @sky-joker hello, thanks for subscribing! :)

I've grepped through files in this repo and have discovered `centos8` mentioned in several files. It should be removed if we wanna see the CI green here. For details, see https://github.com/ansible-collections/news-for-maintainers/issues/3.
If anyone updates the files, it would be great:)

Thank you!

**Comment by dj-wasabi** [comment]
@Andersson007 thanks bro! I have subscribed just a few moments ago. 👍

**Comment by Andersson007** [comment]
@dj-wasabi that's great, you're welcome, thanks:)

**Comment by D3DeFi** [comment]
Oh, thanks for reminding us @Andersson007, I've subscribed to community-topics repo and though those are the same things. Subscribed also to news-for-maintainers

**Comment by Andersson007** [comment]
@D3DeFi thanks!

**Comment by ragingpastry** [comment]
Subscribed @Andersson007 !

**Comment by Andersson007** [comment]
@ragingpastry thank you!

**Comment by Andersson007** [comment]
Hey folks! As you can see the sanity checks are failing.
Could anyone please:
- Copy ignore-2.13.txt to ignore-2.14.txt as mentioned there https://github.com/ansible-collections/news-for-maintainers/issues/13
- Also there were 2 other announcements recently that need maintainer attention:
  - https://github.com/ansible-collections/news-for-maintainers/issues/15
  - https://github.com/ansible-collections/news-for-maintainers/issues/14

When you create PRs, could you please put something like `Relates to <corresponding_issue>` so that it'll be easier for me to track repos that fixed CI (but please don't put `Fixes ...` as it'll close the issue).

Looking forward to your feedback,
Thanks!

**Comment by D3DeFi** [comment]
@Andersson007 thank you for reminding us! I've noticed these changes, but haven't had a chance (until now) to address them. I think that #666 should pretty much cover these. We already skip tests for 2.12 and above for 2.7 an 3.6 python versions.

Can you please confirm that it looks good know in #666? I will also let this issue be closed by it. We can reopen it anytime its needed.

**Comment by Andersson007** [comment]
@D3DeFi you're welcome:) The PR LGTM, thanks!
