### ISSUE TITLE
Add module for autoregistration

### ISSUE THREAD

**Issue by masa-orca** [ansible-collections/community.zabbix#627]
##### SUMMARY

May I add new module which manage autoregistration?
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- zabbix_autoregistration

##### ADDITIONAL INFORMATION

I have tried to create a module to manage [autoregistration](https://www.zabbix.com/documentation/5.0/en/manual/api/reference/autoregistration/object).
However, I forgot asking you that you are welcoming to this contribute or not.
My commit is [here](https://github.com/masa-orca/community.zabbix/commit/6242e000fd4e7a95acacb791c978d374b1da5f03). If you have time, please give me advices!!

```yaml

```

**Comment by D3DeFi** [comment]
Hi @masa-orca, this is definitely very nice and clean solution. I can see autoregistration being added to the zabbix somewhere around 4.4, so we should have added it way sooner. There are also other API endpoints like authentication, setting, etc.. that may also be a good module contributions.

+1 from me, feel free to open PR

@ragingpastry @rockaut what do you guys think?

**Comment by ragingpastry** [comment]
Definitely open up a PR!

**Comment by rockaut** [comment]
Wait, have you had a look at the action module? This should be used for auto registration.

**Comment by D3DeFi** [comment]
My first though exactly, then I did more digging and noticed that is related to the settings -> autoregistration, not actions -> autoregistration, so it makes sense to have modules that will configure zabbix settings. I am only worried if it will not create some confussion among users. Bc if I would be searching for configuring autoregistration action in the future, my first bet would be zabbix_autoregistration module an not zabbix_action

Any ideas there?

**Comment by rockaut** [comment]
Oh, hm. Then we should maybe do something like zabbix_settings_autoreg? I'm on vacation but i will have a deeper look at it tonight.

**Comment by masa-orca** [comment]
I apologize for confusing you.
Zabbix provided some api's for updating settings(e.g. authentication). In addition, from version 6.0, Zabbix adds [setting](https://www.zabbix.com/documentation/devel/en/manual/api/reference/settings/object) api. However, it is not for authentication and autoregistration but for GUI settings. Therefore, I think we need to divide autoregistration and auth and some setting modules.
If we use TLS with PSK for connection between server and agents, we need to use this module and update zabbix_agent.conf before creating actions for autoregistration.

**Comment by D3DeFi** [comment]
I agree with what was stated and recommended by @rockaut . Note would be really helpful in the module, once that is added, we can review PR for merge

**Comment by masa-orca** [comment]
Thank you very much for your comments! 

@rockaut I renamed zabbix_autoregistration zabbix_autoregister! and, I added note to highlight that (thanks to @D3DeFi ).

**Comment by D3DeFi** [comment]
Oh, my bad. I didnt notice that module was called correctly before - zabbix_autoregistration. And that @rockaut accidentally asked for correction to - zabbix_autoregister, which is not how API endpoint is called.

@rockaut so which one do we want? I think the previous name was fine. I also think this name can stay - your call. Im going to review withou merging.

**Comment by rockaut** [comment]
Oh heck I screwed this up, extremely sorry @masa-orca! I just typoed this (should not do this on my phone I guess) - my last comment was meant that zabbix_autoregistration is perfectly ok for me.
