### ISSUE TITLE
Maintenance breaks on missing items

### ISSUE THREAD

**Issue by badfiles** [ansible-collections/community.zabbix#631]
##### SUMMARY
Maintenance api should not stop, if host or group is missing on a server,
It should just skip an item.

This feature would be useful for complex multi-server installations, where dependent components might be called differently or missing.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.zabbix.zabbix_maintenance

**Comment by D3DeFi** [comment]
This is a good idea
+1

**Comment by mu1f407** [comment]
Hi,
I wouldn't recommend to implement this feature into module. There are only 3 states how module can (cleanly) exit in Ansible:
- _changed_ - changes were made to achieve desired state of resource
- _ok_ - resource is already in desired state
- _failed_ - resource cannot be set to desired state for some reason

I think you propose to return _ok_ state for hosts which does not exists. IMHO this would be misleading information for user as he/she could think that resource is already in desired state.

There are better possibilities how to solve this at playbook/task level:
1. Use `ignore_errors: yes`. Task will fail but playbook/task loop will continue.
2. Use `failed_when: false`. Task will report itself as _ok_.
3. Use `when: hostvars[yourhost] is defined` when you use loop or zabbix_inventory plugin. Task will be _skipped_.

**Comment by D3DeFi** [comment]
> Hi, I wouldn't recommend to implement this feature into module. There are only 3 states how module can (cleanly) exit in Ansible:
> 
>     * _changed_ - changes were made to achieve desired state of resource
> 
>     * _ok_ - resource is already in desired state
> 
>     * _failed_ - resource cannot be set to desired state for some reason
> 
> 
> I think you propose to return _ok_ state for hosts which does not exists. IMHO this would be misleading information for user as he/she could think that resource is already in desired state.
> 
> There are better possibilities how to solve this at playbook/task level:
> 
>     1. Use `ignore_errors: yes`. Task will fail but playbook/task loop will continue.
> 
>     2. Use `failed_when: false`. Task will report itself as _ok_.
> 
>     3. Use `when: hostvars[yourhost] is defined` when you use loop or zabbix_inventory plugin. Task will be _skipped_.

This is a good point! I didn't realize that the module would essentially mimic one of these behaviors.

@badfiles what do you think? Can we close the issue?

**Comment by badfiles** [comment]
yes if there is no way to trigger 'skipping' state from a module
