### ISSUE TITLE
New module zabbix_scripts

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#634]
##### SUMMARY
Since 5.4 Zabbix has a central scripts "repository" under Administration > Scripts with different types (actions, hosts, etc.) and accordingly also an API module for that.

It is crucial that we implement a new Ansible Module for this too. As without this module we can not provide support for Zabbix 5.4 and higher at all. For example: we need to create such a central script to reference it as an operation in a trigger action. Without this no trigger action with an script operation can be created. And my guess it, that this is only one example already.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_scripts

##### ADDITIONAL INFORMATION
See https://www.zabbix.com/documentation/5.0/en/manual/api/reference/script

**Comment by masa-orca** [comment]
@rockaut Is anyone assigned this issue? If not, I'll create this module!

**Comment by D3DeFi** [comment]
@masa-orca I don't think that this is assigned to anyone. Feel free to work on it if you are interested.

Btw would you be willing to also contribute some zabbix_action fixes that rely on this module for 5.4/6.0? @rockaut described it in the description of this module

**Comment by D3DeFi** [comment]
@masa-orca I've went ahead and assigned this to you. If you change your mind please let us know. 

Many thanks in advance for taking charge! :)
