### ISSUE TITLE
zabbix user info result is always from Admin User and not from the alias variable

### ISSUE THREAD

**Issue by philippebraxmeier** [ansible-collections/community.zabbix#636]
##### SUMMARY
zabbix user info result is always from Admin User and not from the alias variable

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_user_info

##### ANSIBLE VERSION
ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]

##### OS / ENVIRONMENT / Zabbix Version
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

Zabbix 5.4 and 6.0

##### STEPS TO REPRODUCE
- name: Get zabbix user info
  community.zabbix.zabbix_user_info:
    server_url: "http://zabbix.example.com/zabbix/"
    login_user: admin
    login_password: secret
    alias: example

##### EXPECTED RESULTS
zabbix_user should display information about the user example and not Admin

##### ACTUAL RESULTS
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "alias": "example",
            "http_login_password": null,
            "http_login_user": null,
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "server_url": "http://web02/********/",
            "timeout": 10,
            "validate_certs": true
        }
    },
    "zabbix_user": {
        "attempt_clock": "0",
        "attempt_failed": "0",
        "attempt_ip": "",
        "autologin": "1",
        "autologout": "0",
        "debug_mode": "0",
        "gui_access": "0",
        "lang": "default",
        "medias": [],
        "name": "Zabbix",
        "refresh": "30s",
        "roleid": "3",
        "rows_per_page": "50",
        "surname": "Administrator",
        "theme": "default",
        "timezone": "default",
        "url": "",
        "userid": "1",
        "username": "Admin",
        "users_status": "0",
        "usrgrps": [
            {
                "debug_mode": "0",
                "gui_access": "0",
                "name": "Zabbix administrators",
                "users_status": "0",
                "usrgrpid": "7"
            }
        ]
    }
}

**Comment by masa-orca** [comment]
I tried to happen same bug, however, I could not.
Will you give me a playbook which will happen the bug?

**Comment by masa-orca** [comment]
@BGmot 
zabbix_user_info module seems to change parameter from alias to username.
I think it is not ploblem to use alias parameter.
- https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_user_info.py#L127
- https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_user_info.py#L106

**Comment by BGmot** [comment]
@masa-orca  you are right, unless it's an old version of collection although in this case I'd expect the module to fail.
Just noticed that bug-report is probably modified by hand - different `server_url` and `login_user`.

**Comment by mu1f407** [comment]
@philippebraxmeier This was fixed in #633. I've just tried zabbix_user_info before and after this PR. Please update your community.zabbix collection to latest version.

Previously user.get used `'filter': {'alias': alias}`. As `alias` became `username` in 5.4, Zabbix just ignores `alias` and the request is executed as it would without any filter, so it returns all users. Admin is always the first one, that's why it returned Admin before merge of mentioned PR.

I think this issue can be closed now. Looking at the dates, the issue was legit back then, as it was created 5 days before #633 was merged (and ~2 months before it was tagged as stable).

**Comment by D3DeFi** [comment]
I think that explanation and recommendations from @mu1f407 are correct. This is one of those older issues that were buried by amount of newer ones.

Thank you all for digging in!
