### ISSUE TITLE
Zabbix 6.0 official release?

### ISSUE THREAD

**Issue by solick** [ansible-collections/community.zabbix#640]
Hi, just would like to ask if there is a official release for zabbix 6.0 planned which can be installed via ansible-galaxy?

**Comment by D3DeFi** [comment]
> Hi, just would like to ask if there is a official release for zabbix 6.0 planned which can be installed via ansible-galaxy?
> 
> 

Hello, we officially don't plan out releases of this collection alongside Zabbix releases as we are not able to keep up with the changes.

Also depends on what you want to see. I think roles do have some support already and some modules should work without problems.

That being said, I would like to have next minor version of this collection released soon as master branch contains lots of nice fixes  and features already.
