### ISSUE TITLE
zabbix_proxy: add config_file directive to MySQL | Get version_comment and MySQL | Get current value for innodb_default_row_format tasks

### ISSUE THREAD

**Issue by TakaseNochi** [ansible-collections/community.zabbix#679]
##### SUMMARY
mysql_variables only read ~/.my.cnf but I use /etc/mysql/my.cnf.
https://github.com/ansible-collections/community.zabbix/blob/b2d30089011ee7a85d63e2ef7ff84912df4ba6ba/roles/zabbix_proxy/tasks/mysql.yml#L77

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_proxy

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

community.zabbix:1.6.0

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

status of mysql_variables module become ok.

##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_proxy : MySQL | Get version_comment] *******************************************************************************************************************************************************************************
FAILED! => {"changed": false, "msg": "unable to find /root/.my.cnf. Exception message: (1044, \"Access denied for user 'zabbix'@'localhost' to database 'mysql'\")"}
```

**Comment by BabisK** [comment]
Did you solve this? How?
