### ISSUE TITLE
Regression of #515

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/community.zabbix#680]
d8c9a3545 reverts the fix that was put in #528 to fix #515

cc: @danilomendes , @dj-wasabi

**Comment by barzog** [comment]
I have exactly same problem:
I define pskfile like this:
        zabbix_agent2_tlspskfile: "{{ zbx_tls_psk_identity | default(false) | ternary('/etc/zabbix/zabbix_agentd2.psk', None) }}"
so if psk_identity is defined set pskfile to some predefined path, if not - set to None. In currect situation role fails with "There was an issue creating  as requested: [Errno 2] No such file or directory: b''"

What is intersiting: it fails when running from AWX (19.5.0 with ansible 2.12), when running from CLI ansible (2.12) - all is working as expected. Before #663 change it was working in AWX as well.

**Comment by D3DeFi** [comment]
can you please check #699 for correctness? (Sorry, I am usually floating near plugins, not roles)
