### ISSUE TITLE
Issue with ip filters

### ISSUE THREAD

**Issue by damo2929** [ansible-collections/community.zabbix#685]
##### SUMMARY
the issue with fact filter failing to run. for netcommon.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
TASK [community.zabbix.zabbix_agent : Get Total Private IP Addresses] ***********************************************************************************************************************************************************************
fatal: [zabbix1.internal.zone]: FAILED! => {"msg": "template error while templating string: no filter named 'ansible.netcommon.ipaddr'. String: {{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr('private') | length }}"}

file effected is/roles/zabbix_agent/tasks/Linux.yml

- name: "Get Total Private IP Addresses"
  set_fact:
    total_private_ip_addresses: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr('private') | length }}"
  when:
    - ansible_all_ipv4_addresses is defined
    - not (zabbix_agent_dont_detect_ip)

##### ANSIBLE VERSION
Host OS is Rocky Linux release 8.5
with EPEL ansible installation

community.zabbix version 1.6.0 checked out of ansible galaxy 06 May 22

[root@localhost ~]# ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov  9 2021, 14:44:26) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
``

##### CONFIGURATION
[root@localhost ~]# ansible-config dump --only-changed
[root@localhost ~]#

##### STEPS TO REPRODUCE
running following playbook

`---
# Required Ansible collections
#  collections:
#  - name: community.general
#  - name: community.mysql
#  - name: community.zabbix

- name: Zabbix Server installation
  become: yes
  hosts: zabbixservers

  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent_version: 6.0
      zabbix_repo: zabbix
      zabbix_selinux: True
      zabbix_agent_package_state: latest
      zabbix_agent2: true
      zabbix_agent2_server: 192.171.172.83
      zabbix_agent2_serveractive: 192.171.172.83
      zabbix_agent2_buffersend: 3600
      zabbix_agent2_hostname: "{{ ansible_hostname }}"
      zabbix_agent2_hostmetadata: "{{ ansible_system }}"
      zabbix_agent2_refreshactivechecks: 300
      zabbix_agent2_timeout: 30
      selinux_allow_zabbix_run_sudo: True
`

##### ACTUAL RESULTS
TASK [community.zabbix.zabbix_agent : Get Total Private IP Addresses] ***********************************************************************************************************************************************************************
fatal: [zabbix1.internal.zone]: FAILED! => {"msg": "template error while templating string: no filter named 'ansible.netcommon.ipaddr'. String: {{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr('private') | length }}"}

**Comment by nosko-stojachkov** [comment]
Hello,
It worked for me like this.
**requirements.yml:**
```yaml
collections:
  - name: community.zabbix
    version: 1.6.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
  - name: ansible.netcommon
    version: 2.0.0
```

**Comment by appreciated** [comment]
I've got the same issue, I made it work by adding `zabbix_agent_dont_detect_ip: True`

My collections are:
```
'community.zabbix:1.6.0'
'ansible.posix:1.3.0'
'community.general:4.8.0'
'ansible.netcommon:3.0.0'
```
