### ISSUE TITLE
Set proxy for host in zabbix_agent role

### ISSUE THREAD

**Issue by beerygaz** [ansible-collections/community.zabbix#690]
##### SUMMARY
When using the API to add a host entry while executing the zabbix_agent role it would be useful to be able to specify the proxy.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Add a parameter to the the zabbix_agent role calle 'zabbix_proxy' that takes a sting value of a proxy name and allocates the host to this proxy when created via the API.

##### ADDITIONAL INFORMATION
The only workaround I can find for this is to use the zabbix_host module as a second activity to retoractively set the proxy once the agent role has created the host.

**Comment by Support-Green-IT-Solutions** [comment]
Hi,

Use `zabbix_agent_proxy: ""` variable to define your proxy name. It's an undocumented variable but you can find it on the file https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/defaults/main.yml

Regards
