### ISSUE TITLE
zabbix_agent_version ignored on Ubuntu 20.x

### ISSUE THREAD

**Issue by unbreakabl3** [ansible-collections/community.zabbix#701]
##### SUMMARY
When using `zabbix_agent_version: 5.0` for example, on RHEL, CentOS, Rocky its is installing the 5.0, but on Ubuntu its always installing the latest. Currently, its always installing 6.0.4

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_agent

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.5]
```

##### CONFIGURATION
```paste below
DISPLAY_SKIPPED_HOSTS(/Users/user/Ansible/ansible-awx/ansible.cfg) = False
```

##### OS / ENVIRONMENT / Zabbix Version
Ubuntu 20.04 - installing wrong Zabbix agent version
CentOS - working as expected

##### STEPS TO REPRODUCE
set `zabbix_agent_version: 5.0` as a variable and run the playbook on Ubuntu

##### EXPECTED RESULTS
Zabbix Agent 5.0 should be installed on Ubuntu

##### ACTUAL RESULTS
Latest 6.x is always installed

**Comment by andrebossi** [comment]
I did this workaround by setting the following variables to get the right version and it worked but needs to be fixed in the task.

zabbix_agent_version: 5.0
zabbix_agent_package: zabbix-agent=1:5.0.24-1+focal
zabbix_sender_package: zabbix-sender=1:5.0.24-1+focal
zabbix_get_package: zabbix-get=1:5.0.24-1+focal

**Comment by unbreakabl3** [comment]
> I did this workaround by setting the following variables to get the right version and it worked but needs to be fixed in the task.
> 
> zabbix_agent_version: 5.0 zabbix_agent_package: zabbix-agent=1:5.0.24-1+focal zabbix_sender_package: zabbix-sender=1:5.0.24-1+focal zabbix_get_package: zabbix-get=1:5.0.24-1+focal

Great. Thanks a lot. I will test it next week. 
Probably, the documentation should be updated as well.

**Comment by ortzinator** [comment]
I had a similar issue. My solution was to manually `apt remove zabbix-agent` and rerun the role.
