### ISSUE TITLE
Firewall iptables ipv6 support

### ISSUE THREAD

**Issue by YoSiJo** [ansible-collections/community.zabbix#707]
##### SUMMARY
Currently the [roles/zabbix_agent/tasks/firewall.yml](https://github.com/ansible-collections/community.zabbix/blob/2287bc4165a03e2ae8a2ed94ec1088428b29dad9/roles/zabbix_agent/tasks/firewall.yml) can not handle ipv6 addresses.

##### ISSUE TYPE
- Use IPv6 Only infra.

##### COMPONENT NAME
firewall/iptables

##### ADDITIONAL INFORMATION
Currenty not, i think we can mak a ip type detection and so wie use a when for ipv4 iptables or ip6tables, but i am not sure, that this is the best solution.

**Comment by pyrodie18** [comment]
After discussion, the configuration of the firewall falls out of the scope of the purpose of the Zabbix collection.  Support for firewall configuration in the agent role will be removed as part of the 2.0 drop soon.  Users requiring firewalls to be configured can do so as a task at the playbook level or using other roles such as https://github.com/geerlingguy/ansible-role-firewall
