### ISSUE TITLE
Set Macros and Tags using community.zabbix.zabbix_agent

### ISSUE THREAD

**Issue by beerygaz** [ansible-collections/community.zabbix#742]
When creating the host via API using community.zabbix.zabbix_agent, is it possible to set macros and tags?   

Or do we need to make a call to community.zabbix.zabbix_host to add tags and macros?

**Comment by mu1f407** [comment]
@beerygaz Currently only host macros using `zabbix_agent_macros`. See [example](https://github.com/ansible-collections/community.zabbix/tree/main/roles/zabbix_agent#vars-in-role-configuration) in zabbix_agent documentation.
