### ISSUE TITLE
zabbix_agent_include var should be able to contain a glob pattern

### ISSUE THREAD

**Issue by leroy0211** [ansible-collections/community.zabbix#748]
##### SUMMARY

Zabbix-agent can use a glob pattern in the `Include` key. By default this is something like `/etc/zabbix/zabbix.agent.d/*.conf`. When you change this, it will try to create a directory called `*.conf`. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible_agent

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.1]
  ansible python module location = /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST([path]/ansible.cfg) = ['[path]/inventory']
DEFAULT_ROLES_PATH([path]/ansible.cfg) = ['[path]/roles']
DEPRECATION_WARNINGS([path]/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

Change the `zabbix_agent_include` variable of the role to `/etc/zabbix/zabbix.agent.d/*.conf` and run the ansible_agent playbook.

##### EXPECTED RESULTS

The directory `/etc/zabbix/zabbix.agent.d/*.conf/` should not be created.

##### ACTUAL RESULTS

The directory `/etc/zabbix/zabbix.agent.d/*.conf/` is created and looks stupid. The template however uses the correct glob pattern.

**Comment by D3DeFi** [comment]
@leroy0211 thanks for opening this report. Are you please able to test this with changes proposed by @mu1f407 in #770 ?
