### ISSUE TITLE
zabbix_user_directory module

### ISSUE THREAD

**Issue by BGmot** [ansible-collections/community.zabbix#755]
##### SUMMARY
Ability to configure several LDAP servers was introduced in Zabbix 6.2 thus zabbix_user_directory module needs to be created to manage these sources of authentication.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_user_directory

##### ADDITIONAL INFORMATION
zabbix_user_directory module would be used to add/update/delete "user directories". In terms of Zabbix 6.2 a "user directory" is an entry that has a set of configuration parameters to authenticate agains given LDAP server.

**Comment by pyrodie18** [comment]
**authentication**

- [ ] ZBXNEXT-2289 authentication.get, authentication.create, authentication.update: removed properties ldap_host, ldap_port, ldap_base_dn, ldap_search_attribute, ldap_bind_dn, ldap_bind_password.

**auditlog**
- [ ] ZBXNEXT-2289 added new resourcetype (49 - LDAP user directory).

**authentication**
- [ ] ZBXNEXT-2289 authentication.get, authentication.create, authentication.update: added property ldap_userdirectoryid.

**user**
- [ ] ZBXNEXT-2289 user.checkAuthentication: returns a new property userdirectoryid.
- [ ] ZBXNEXT-2289 user.login: option userData returns a new property userdirectoryid.

**userdirectory**
- [ ] ZBXNEXT-2289 added new userdirectory API introducing new methods userdirectory.get, userdirectory.create, userdirectory.update, userdirectory.delete, userdirectory.test.

**usergroup**
- [ ] ZBXNEXT-2289 usergroup.create, usergroup.update, usergroup.get: added property userdirectoryid.
##### ISSUE TYPE

**Comment by mu1f407** [comment]
Module already added in linked PR. Closing.
