### ISSUE TITLE
Add Support for Template and Host Groups

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#760]
##### SUMMARY
Functionality for both Host groups and Templates Groups added in Zabbix 6.2
https://support.zabbix.com/browse/ZBXNEXT-2592
https://support.zabbix.com/browse/ZBXNEXT-7596

**configuration**
- [ ] ZBXNEXT-2592 configuration.export: option groups is not supported, instead new options introduced host_groups and template_groups.

**hostgroup**
- [ ] ZBXNEXT-2592 hostgroup object does not have property internal anymore.
- [ ] ZBXNEXT-2592 hostgroup.get: removed options templated_hosts, with_hosts_and_templates, selectTemplates.
- [ ] ZBXNEXT-2592 hostgroup.massadd, hostgroup.massupdate: does not accept templates parameter anymore.
- [ ] ZBXNEXT-2592 hostgroup.massremove: does not accept templateids parameter anymore.

**template**
- [ ] ZBXNEXT-2592 template.create, template.massadd, template.massupdate, template.update: parameter groups now accepts only template groups and must contain template group groupid.
- [ ] ZBXNEXT-2592 template.massremove: parameter groupids is now template groups groupids.

**auditlog**
- [ ] ZBXNEXT-2592 added new resourcetype (50 - Template group).

**graph**
- [ ] ZBXNEXT-2592 graph.get: deprecated option selectGroups, new options selectHostGroups, selectTemplateGroups.

**graphprototype**
- [ ] ZBXNEXT-2592 graphprototype.get: deprecated option selectGroups, new options selectHostGroups, selectTemplateGroups.

**host**
- [ ] ZBXNEXT-2592 host.get: deprecated option selectGroups, new option selectHostGroups.
**hostgroup**
- [ ] ZBXNEXT-2592 hostgroup.get: deprecated options monitored_hosts, real_hosts, new options with_hosts, with_monitored_hosts.
- [ ] ZBXNEXT-2592 hostgroup.propagate: new method.

**maintenance**
- [ ] ZBXNEXT-2592 maintenance.get: deprecated option selectGroups, new option selectHostGroups.

**script**
- [ ] ZBXNEXT-2592 script.get: deprecated option selectGroups, new option selectHostGroups.

**template**
- [ ] ZBXNEXT-2592 template.get: deprecated option selectGroups, new option, selectTemplateGroups.

**templategroup**
- [ ] ZBXNEXT-2592 added new templategroup API introducing new methods: templategroup.create, templategroup.delete, templategroup.get, templategroup.massadd, templategroup.massremove, templategroup.massupdate, templategroup.propagate, templategroup.update.

**trigger**
- [ ] ZBXNEXT-2592 trigger.get: deprecated option selectGroups, new options selectHostGroups, selectTemplateGroups.

**triggerprototype**
- [ ] ZBXNEXT-2592 triggerprototype.get: deprecated option selectGroups, new option selectHostGroups, selectTemplateGroups.

**usergroup**
- [ ] ZBXNEXT-2592 usergroup.get: deprecated option selectRights, new options selectHostGroupRights, selectTemplateGroupRights.

**usermacro**
- [ ] ZBXNEXT-2592 usermacro.get: deprecated option selectGroups, new options selectHostGroups, selectTemplateGroups.
##### ISSUE TYPE
- Feature Idea

**Comment by mu1f407** [comment]
@pyrodie18, I believe this was already resolved in #738. Not sure if it solves every change made by Zabbix, but it fixed the tests so at least breaking changes was solved. Please take a look at it, as I think this issue can be closed.

**Comment by pyrodie18** [comment]
Yep good catch.  Sorry about that I was going through the list of changes and neglected to see what work had been done in the last 30 days or so since release.  Closing.
