### ISSUE TITLE
Check Installation from Roles with 6.2

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#761]
##### SUMMARY
Ensure that all roles are able to properly install/configure Zabbix 6.2

##### ISSUE TYPE
- Feature Idea

**Comment by pyrodie18** [comment]
Need some opinions.  I'm going through and running tests on the updated roles.  6.2 server isn't supported on Debian 10, so the tests keep failing.  How do we want to handle this?  I can easily add Debian 11 into the testing matrix, which is what we talk about doing in #764 , or can add logic that just gracefully ends the play if it sees 6.2 trying to go onto Debian 10.  Longer term, I think there is a FR here where it automattically installs the newest supported version on an operating system (so for Debian 10 it would be 6.0). I'm open to other ideas.  @D3DeFi @ragingpastry  @BGmot @lzadjsf  @mu1f407

**Comment by dj-wasabi** [comment]
So you say that Zabbix Server 6.2.0 does not support Debian 10? Then I would go for Debian 11. I personally never like changing the tests to something like "gracefully ends the play if it sees 6.2 trying to go onto Debian 10". It seems a bit like a Volkswagen test. 😉   Testing something and it doesn't matter what the end result is, so we just accept it. And by changing it to Debian 11, you still have the tests, CI is working fine and who knows, maybe someone (in this Repo or on Zabbix) is able to provide some changes that it will work wiht Debian 10, then you can always reconsider..

My 2 cents. 😄

**Comment by D3DeFi** [comment]
I agree with @dj-wasabi, lets add Debian 11 to testing matrix
