### ISSUE TITLE
FR: Add install Support for Ubuntu 22.02

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#763]
##### SUMMARY
Zabbix 5.0, 6.0 and 6.2 has support for Ubuntu 22.02. Need to update roles to allow for installation

##### ISSUE TYPE
- Feature Idea

**Comment by evilhamsterman** [comment]
Just a minor quibble, there is no Ubuntu 22.02. The latest release is 22.04 https://wiki.ubuntu.com/Releases

**Comment by pyrodie18** [comment]
Ya that was a typo
