### ISSUE TITLE
Remove Support for Unsupported Versions

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#766]
##### SUMMARY
Remove support for Zabbix 4.X

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Various roles and modules

##### ADDITIONAL INFORMATION
In our README we outline that we support the two most current LTS releases which are currently 6.0 and 5.0.  We still include support for 4.X installs.  I suggest that we go ahead and deprecate that functionality from the collection as part of our next major release.

**Comment by BGmot** [comment]
I am not sure. Zabbix 4.0 still has limited support until October 31, 2023 https://www.zabbix.com/life_cycle_and_release_policy
Why remove what's working? Or you mean to put some 'deprecation notice'?

**Comment by pyrodie18** [comment]
> I am not sure. Zabbix 4.0 still has limited support until October 31, 2023 https://www.zabbix.com/life_cycle_and_release_policy Why remove what's working? Or you mean to put some 'deprecation notice'?

Because that's what we said we would do in https://github.com/ansible-collections/community.zabbix#supported-zabbix-versions.  It would allow us to clean up the code base a lot and simply the roles.  As is, we still have support in there for <= 3.2, and we're not currently testing the installs for any of them.

**Comment by D3DeFi** [comment]
I think when we prepared our release document we stated that major releases would warrant for forking _main_ branch into _stable-1.x_ branch. 

I am all up for removing 4.x functionality at this point. Users can lock community.zabbix at 1.y.z version and we release 2.0.0 without zabbix 3.x and 4.x.

If anything critical is found, we can always backport the fix and git tag 1.y.z + 1 version.
