### ISSUE TITLE
Clarify Supported Operating Systems

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#767]
##### SUMMARY
When I read through our documentation (i.e. https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md) it is unclear to me what operating systems we are supporting.  For example, RHEL v5 is listed on the table as having support for Zabbix versions 3, 4, 5, and 6.  RHEL 5 itself was officially retired 9 or 5 years ago (depending on the definition of retired).  Looking through our runner configuration, we aren't testing it at all.

I would suggest one of two things.  If we aren't actively testing against a OS version to ensure support, we either remove it completely from the documentation or change how it is indicated (instead of the current 'V') to show that Zabbix itself may support it, but there is no guarantee that the role/module will work on it.

##### ISSUE TYPE
- Change Request

**Comment by D3DeFi** [comment]
I agree with this. Support matrix should be way smaller then it is. No need to support EOL releases
