### ISSUE TITLE
Document a way to migrate to collection from standalone roles and modules

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#77]
##### SUMMARY
`docs/MIGRATION.md` or something similar required for users to ease them a pain with transferring to the collection.

##### ISSUE TYPE
- Documentation Report

**Comment by rockaut** [comment]
That would be great but I think that is a whole lot of a task as there are so many issues with ansible-base and collections as such and pretty much like any collection I use/stumble across is having the same problems in this task.
So I think this won't go well until ansible-base hasn't stabilized it's collection implementation with 2.10 and 2.9 updates.

**Comment by D3DeFi** [comment]
Indeed true, at this point it is more like providing a few steps for users to help with transition from:
`dj-wasabi/zabbix-$role -> community.zabbix.zabbix_$role` and `zabbix_module -> community.zabbix.zabbix_$module`. And I am a bit behind with this as we've already released 0.2.0

Everything else is just to unstable rn.

**Comment by D3DeFi** [comment]
This is now obsolete, there was a upstream documentation for 2.10 on how to transition to collections
