### ISSUE TITLE
[Discussion] Develop Zabbix Collection 2.0.0

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#774]
##### SUMMARY
Begin working on version 2.0.0 of the collection

##### ISSUE TYPE
- Discussion

##### ADDITIONAL INFORMATION
I would like to start working on version 2.0.0 of the collection.  As I've spent the last week or so going through and adding support for Zabbix 6.2, it's become apparent that there are a lot of skeletons in the code base.

Things I'd like for us to consider doing:

1.  Only supporting Zabbix 6.2, 6.0, 5.0, and 4.0.  All other fixes, hacks and other things that have been inserted into the code base get removed in an effort to clean it up and make it more maintainable.
2. Only support currently maintained operating systems.  To me, that means anything outside of LTS is retired.  Again, remove the hacks and fixes in the code base that are used to maintain those.
3. Update the testing matrix.  In my opinion, if we're saying we support it (see first to ideas), then we should be testing against it.  We clean up the matrix to make it more maintainable.
4. I came across the discussions in #567 and #163 .  If we want to drop support for something, now is the time to do it.  Is that the direction we want to go?  Thoughts?

I've created a new project to track this (https://github.com/ansible-collections/community.zabbix/projects/8).  Thoughts everyone?

@D3DeFi 
@ragingpastry 
@BGmot 
@lzadjsf 
@mu1f407

**Comment by BGmot** [comment]
I am all for it. First I think we need to decide what oldest version of Zabbix we want to support.

**Comment by D3DeFi** [comment]
Indeed, I am also all for this. Would have started this activity a waaay back, but I would have been never been to fully commit.

When it comes to versions, I would drop 4.x as well and only test and support 5/6/6.2

**Comment by D3DeFi** [comment]
I also think that most of the users run zabbix modules locally or from controller, so enforcing python3.8+ should be easy for us. Ansible-core is also doing the same from 2.14 or such afaik

**Comment by pyrodie18** [comment]
I won't lose any sleep ditching 4.  People who really need it can keep using the 1.X branch of need be.  I have not looked at httpapi at all so no idea what it would take to finish bringing that only.

**Comment by BGmot** [comment]
Sorry I just don't understand what httpapi is thus will be listening.

**Comment by D3DeFi** [comment]
It was an initiative from @rockaut  to re-use httapi plugin from ansible and replace external zabbix-api dependency with it. I think there id one module that uses it already

**Comment by pyrodie18** [comment]
Proposed supported operating systems (for server, web, and proxy):

Ubuntu:
- 18.04 (End of Standard Support [ESS] April 2023)
- 20.04 (ESS April 2025)
- 22.04 (ESS April 2027

Debian:
- 10 (ESS Jun 2024)
- 11 (ESS Aug 2026)

Centos/Rocky
- 7 (ESS Jun 2024)
- 8 (ESS May 2029)
- 9 (ESS May 2032)

I could see maybe expanding the list out some as it relates to the agents.  Thoughts?

**Comment by D3DeFi** [comment]
I agree with OS matrix

**Comment by pyrodie18** [comment]
So as I go through and rework some of the older operating systems, I'm having problems with them connecting to the mysql 8.0 server.  Because of the change in the default authentication method to caching_sha2_password, some of the older default mysql installs don't support it.  I'm playing with the idea of instead installing the current version of the mariadb client instead.  Thoughts?

**Comment by D3DeFi** [comment]
> So as I go through and rework some of the older operating systems, I'm having problems with them connecting to the mysql 8.0 server. Because of the change in the default authentication method to caching_sha2_password, some of the older default mysql installs don't support it. I'm playing with the idea of instead installing the current version of the mariadb client instead. Thoughts?

For the CI I don't mind. They should more or less still be cross-compatible, right?

**Comment by pyrodie18** [comment]
I actually didn't think about just doing it for CI.  Let me play with that over the weekend.

**Comment by D3DeFi** [comment]
This may be of interest https://github.com/ansible-collections/news-for-maintainers/issues/23

Anyway, I am not sure if anyone works on plugins, it would be unfortunate to release 2.0.0 with only role changes

**Comment by pyrodie18** [comment]
> This may be of interest [ansible-collections/news-for-maintainers#23](https://github.com/ansible-collections/news-for-maintainers/issues/23)
> 
> Anyway, I am not sure if anyone works on plugins, it would be unfortunate to release 2.0.0 with only role changes

Honestly hadn't even been tracking that.  I'm much stronger on the roles side than modules personally.  Did you have anything specific in mind?

**Comment by BGmot** [comment]
I am sorry guys it takes too much time to finish httpapi but yes I am updating all the plugins hope to finish this weekend.

**Comment by D3DeFi** [comment]
> I am sorry guys it takes too much time to finish httpapi but yes I am updating all the plugins hope to finish this weekend.

Dont worry at all. I was just unsure if anyone at all was interested in playing with plugins/modules. I've only remembered you are experimenting with httpapi.

**Comment by BGmot** [comment]
The code is ready but I am stuck with testing https://github.com/ansible-collections/community.zabbix/issues/558

**Comment by pyrodie18** [comment]
OK, so I've obviously fallen to the wayside on this.  I'm sorry (life has been a bit of a shit show lately) and I know the current version of the collection has undergone a fair number of changes (most notably https://github.com/ansible-collections/community.zabbix/pull/822.  Because of that, I think I'm going to start a new branch based on the current pull, reapply playbooks that we already updated and see what breaks.

**Comment by BGmot** [comment]
Welcome back @pyrodie18! -) Life is a one big shit show...

**Comment by D3DeFi** [comment]
> OK, so I've obviously fallen to the wayside on this. I'm sorry (life has been a bit of a shit show lately) and I know the current version of the collection has undergone a fair number of changes (most notably #822. Because of that, I think I'm going to start a new branch based on the current pull, reapply playbooks that we already updated and see what breaks.

Yup, don't worry, this is open source :) No one expects you to work around the clock and meet deadlines. Hope everything goes better for you from now on. Welcome back! :)

**Comment by rockaut** [comment]
Just a side note to all. Even now as I only have a look from outside it's cool to see the collection progress because all your contributions. 👍🔥

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pyrodie18** [comment]
Gentlemen, I'm not particularly strong when it comes to the configuration of web servers, especially the PHP part of it.  Within the web role, do we need to template php-fpm.conf.j2 (anyone know why its only with Debian?), and the php parts within vhost templates or are they leftover from a time in the past?  I don't see anything within the Zabbix documentation itself about needing to configure php (if I am missing something, please link it).

**Comment by BGmot** [comment]
> Gentlemen, I'm not particularly strong when it comes to the configuration of web servers, especially the PHP part of it. Within the web role, do we need to template php-fpm.conf.j2 (anyone know why its only with Debian?), and the php parts within vhost templates or are they leftover from a time in the past? I don't see anything within the Zabbix documentation itself about needing to configure php (if I am missing something, please link it).

The only thing I usually adjust in php is time zone
```
date.timezone = bla-bla
```
and on Debian it can be in:
```
    # Different places of PHP configuration file
    if [ -f "/etc/php5/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php5/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php5/fpm/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php5/fpm/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php5/apache2/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php5/apache2/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php/7.0/apache2/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php/7.0/apache2/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php/7.0/fpm/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php/7.0/fpm/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php.d/99-zabbix.ini"
    elif [ -f "/etc/php7/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php7/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php/7.2/fpm/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php/7.2/fpm/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php/7.2/apache2/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php/7.2/apache2/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php/7.4/fpm/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php/7.4/fpm/conf.d/99-zabbix.ini"
    elif [ -f "/etc/php/8.1/fpm/conf.d/99-zabbix.ini" ]; then
        PHP_CONFIG_FILE="/etc/php/8.1/fpm/conf.d/99-zabbix.ini"
    fi
```

**Comment by pyrodie18** [comment]
What are our thoughts on maintaining support for Epel and "other" installation sources?  We're not currently testing against it at all and if we're going to support, I should add it to the testing matrix (not that I'm entirely sure how to test against "other".  Dropping it will clean up the code a little bit (although not a ton).

**Comment by pyrodie18** [comment]
OK so next decision.  I'm pretty well done with the updates (sans 6.4 work) with everything except for the agent.  Right now we "support" a ton of different OSs (outside of our normal list).  Do we want to keep that up, understanding that for at least a few, there's probably not a good way to test this (this includes Windows).

**Comment by D3DeFi** [comment]
> OK so next decision. I'm pretty well done with the updates (sans 6.4 work) with everything except for the agent. Right now we "support" a ton of different OSs (outside of our normal list). Do we want to keep that up, understanding that for at least a few, there's probably not a good way to test this (this includes Windows).

we don't. Unless somebody wants to join in and take on the ownership for the particular OS, we don't support nor guarantee anything. Patches are merged only on best effort basis and we should not feel obliged at all to port the roles for those OSes. It may be worth specifying that we don't support those, but opted to merge patches for them in the past

**Comment by BGmot** [comment]
So what's outstanding items?
- drop zabbix-api support
- clean up roles variables
- decide on what versions of Zabbix/OSs we support and clean up the collection
- ... ?

**Comment by pyrodie18** [comment]
OK so I have cleaned up (removed all depreciated variables, simplified variables, remove old code fragments, remove tasks out of scope of Zabbix, etc.) all of the roles outside of Agent.  I've removed support for Zabbix < 6.0 and all operating systems other than Debian, Ubuntu, and RHEL (supported versions only).   The one exception is Windows on the Agent role which we can't test currently).  I have not tackled adding support for 6.4 (from the role perspective).

Given the fact that support for 5.0 drops on May 31st, I would suggest that we target that as a no later than release date.

**Comment by BGmot** [comment]
@pyrodie18 are you going to re-base 2.0.0-dev2 when we release 1.9.3? what about 2.0.0-dev?

**Comment by pyrodie18** [comment]
Yes, I'll rebase dev2.  I just trashed dev.

**Comment by pyrodie18** [comment]
OK my working branch has been merged into the 2.0.0-dev2 branch.  If you guys want to look at the plugins and see what's going on with those.  I'm going to figure out why the roles broke when I rebased things.

**Comment by pyrodie18** [comment]
Do we consider changing tags to be a breaking change?

**Comment by D3DeFi** [comment]
> Do we consider changing tags to be a breaking change?

Only place I can think of is Ansible Tower. If I remember correctly you can create job template there and limit it to a specific tag in playbook. In such case it can create a breaking change situation, but I don't think we should take Tower into consideration at all. From the perspective of simple Ansible, it should not be a breaking change

**Comment by pyrodie18** [comment]
OK, then we can worry about cleaning up tags later on.

**Comment by pyrodie18** [comment]
OK, I think I am done with breaking changes to agents.  The last thing on my todo list is cleanup documentation.

**Comment by BGmot** [comment]
I promise to take care of modules:
- remove zabbix-api
- clean up code that deals with older Zabbix versions

**Comment by pyrodie18** [comment]
What did we decide about configuring the firewall?  Right now the only place where we're doing it (I think) is agent.  I could be sold either way that this is in/out of scope of the role(s).

**Comment by BGmot** [comment]
I think firewall configuration is out of scope of this collection.

**Comment by pyrodie18** [comment]
Question reference the API stuff.  Trying to clean up the variables in the roles.  Which of these vars is good to stay and what can go (from the proxy role)

```zabbix_api_http_user: admin
zabbix_api_http_password: admin
zabbix_api_login_user: "{{ zabbix_api_user }}"
zabbix_api_login_pass: "{{ zabbix_api_pass }}"
ansible_httpapi_pass: "{{ zabbix_api_login_pass }}"
ansible_httpapi_port: "{{ (zabbix_api_port_from_url == '') | ternary(zabbix_api_port_from_shema, zabbix_api_port_from_url) }}"
ansible_httpapi_use_ssl: "{{ zabbix_api_use_ssl | default((zabbix_api_scheme_from_url == 'https') | ternary(true, false)) }}"```

**Comment by BGmot** [comment]
I'd say we need to use `zabbix_api_login_user` and `zabbix_api_login_pass` as "input" variables for roles. Then for "internal" modules consumption they need to be asssigned to `ansible_user` and `ansible_httpapi_pass` respectively.

**Comment by pyrodie18** [comment]
So are you saying within the defaults probably I would do:

ansible_user: "{{ zabbix_api_login_user }}"

**Comment by BGmot** [comment]
no, `zabbix_user` needs to be assigned to this var only for api task. In defaults I propose
```
zabbix_api_login_user: zabbix
```

**Comment by pyrodie18** [comment]
OK, documentation and variables have been cleaned up.  Probably could still use some work, and to be completely honest, still don't totally get the api username/password if someone wants to take a look at it and make any changes, by all means, please do.

**Comment by pyrodie18** [comment]
> I promise to take care of modules:
> 
> * remove zabbix-api
> * clean up code that deals with older Zabbix versions

Any chance to work on this?  When do we want to go ahead and release @BGmot @D3DeFi

**Comment by BGmot** [comment]
I am working right now, sorry for delay -( As usual in life when you promise something the life decides that you have to attend to other priorities -(((

**Comment by BGmot** [comment]
I am sorry I don't see how you rebased 2.0.0-dev2 on top of main. I am getting gazillion of sanity check errors that were already fixed. The branch is old as hell or I am missing something -(, I can't work without updating with everything what we have in main (up to 1.9.3).
```
* c058857 (HEAD -> bgmot_modules_200, upstream/2.0.0-dev2, origin/2.0.0-dev2, 2.0.0-dev2) Documentation (#954)
* f7dfe09 Agent Update (#948)
* 8845934 Other fixes (#945)
* 7d308ea Proxy fix (#944)
* 9e19ecd Server fix (#943)
* 1f6d682 2.0.0 dev2 (#904)
* 61cfd3e Server update (#1) (#895)
| * 599d89f (origin/bgmot_gh_runner_image, bgmot_gh_runner_image) Changelog fragment added.
| * 13517f0 zabbix_action: re-name message paremeter into op_message.
| * 5ac07ba zabbix_host: fix integration test to properly handle removing all linked templates.
| * 660ab4f Do not ignore any failing sanity tests.
| * 25272f4 Fix sanity tests for Ansible dev.
| * 1a5882b Switch to Ubuntu 20.04 for all molecule tests.
| * 2caaf07 Switch to Ubuntu 20.04 for web test.
| * f3d5b74 Switch to Ubuntu 22.04 for web test.
| * 6db93c9 Switch GitHub runner image to ubuntu-latest.
| * 2b33136 (tag: 1.9.3, upstream/main, origin/main, origin/HEAD, main) 1.9.3prep (#938)
| | * 8707118 (upstream/1.9.3prep, 1.9.3prep) README.md updated.
| | * b90240c galaxy.yml updated.
| | * ace399a CHANGELOG.rst generated.
| | * 3d9eb2f Fix changelog format.
| | * a739014 Add missing changelog fragments.
| |/  
| * e4bd9d6 Roles to Zabbix 6.4 (#937)
```

**Comment by pyrodie18** [comment]
Hhhhmmmm, I thought I did.  When you look at the workflows in the dev branch they have the updated 20.04 as the runners.  Its entirely possible I screwed up the rebase though (I'm not very good at it).

**Comment by BGmot** [comment]
No worries. I am trying to figure out how to better move forward -)

**Comment by pyrodie18** [comment]
OK, I just tried to rebase it pulled exactly nothing into it from the looks of it.

**Comment by pyrodie18** [comment]
Let me know if you need anything

**Comment by BGmot** [comment]
I rebased
```
* b02d064 (HEAD -> bgmot_modules_200, origin/bgmot_modules_200) zabbix_inventory: do not use zabbix-api, ability to authenticate with auth token.
* 4e68f7c zabbix-api removed.
* aa718eb (upstream/2.0.0-dev2, origin/2.0.0-dev2, 2.0.0-dev2) Fix all the errors after re-basing against main.
* eab3905 Documentation (#954)
* b5d366c Agent Update (#948)
* 0bd2dc5 Other fixes (#945)
* 19c4796 Proxy fix (#944)
* cbb44b3 Server fix (#943)
* 99e0c76 2.0.0 dev2 (#904)
* 8a8647d Server update (#1) (#895)
* 56f94d1 (upstream/main, origin/main, origin/HEAD, main) GitHub runner image and sanity tests (#941)
| * 599d89f (origin/bgmot_gh_runner_image, bgmot_gh_runner_image) Changelog fragment added.
| * 13517f0 zabbix_action: re-name message paremeter into op_message.
| * 5ac07ba zabbix_host: fix integration test to properly handle removing all linked templates.
| * 660ab4f Do not ignore any failing sanity tests.
| * 25272f4 Fix sanity tests for Ansible dev.
| * 1a5882b Switch to Ubuntu 20.04 for all molecule tests.
| * 2caaf07 Switch to Ubuntu 20.04 for web test.
| * f3d5b74 Switch to Ubuntu 22.04 for web test.
| * 6db93c9 Switch GitHub runner image to ubuntu-latest.
|/  
* 2b33136 (tag: 1.9.3) 1.9.3prep (#938)
```
but had to solve a lot of merge conflicts. I was stupid enough not to save your original 2.0.0-dev2 branch and as with any rebase I had to force push. So please rename your current local branch, fetch its current state from this repo and compare to find out whether I screwed anything up. My apologies.
Something like:
```
git branch -m 2.0.0-dev2 2.0.0-dev2-old
git fetch origin 2.0.0-dev2 # put your remote name for this repo instead of origin
git checkout 2.0.0-dev2
git pull
git diff 2.0.0-dev2-old
```
A bit later I will create a PR to merge my 2.0.0 modules modifications into 2.0.0-dev2, currently testing everything.

**Comment by pyrodie18** [comment]
Will do...and thanks

**Comment by BGmot** [comment]
Also please see https://github.com/ansible-collections/community.zabbix/pull/963

**Comment by BGmot** [comment]
We could not develop 2.0.0 in main, too many changes and takes too much time.
If we did take this path then several 1.9.x versions would be released in stable- branch and anyway we'd need to shuffle code between two branches. I don't see any difference.

**Comment by flowerysong** [comment]
I'm not saying that all of the development had to happen in `main`, but I think once you've reached the point of [closing trivial PRs](https://github.com/ansible-collections/community.zabbix/pull/949) because you're afraid of rebasing you're well past the point where you should have branched `stable-1`.

And it's perfectly normal to do multiple releases from `stable-x` branches; that's their whole point, is to provide a place you can make stable releases from while letting breaking changes land in `main`.

**Comment by BGmot** [comment]
I don't see any principal difference between doing breaking changes in 2.0.0-dev and in main. If we ever decide to release 1.9.4 after releasing 2.0.0 then sure we can branch off stable-x and backport changes. I find it much more convenient and clean to rebase as often as possible instead of cherry-picking commits. Anyway what's done is done for 2.0.0 we'll probabl consider `stable-x` approach for 3.0.0.

**Comment by pyrodie18** [comment]
@BGmot do you plan on removing <6.0 functionality from the modules or are you going to leave them as is for right now?

What else needs to be done?  I've got a couple of PRs in to clean up a few loose ends but short of that, I think I'm about done.

**Comment by BGmot** [comment]
Yes I am working on removing <6.0 code, it's messy -(
From  my perspective that is it, nothing else needed for 2.0.0.

**Comment by pyrodie18** [comment]
Ya I was looking at it last night.  If you need any help with it, let me know.

**Comment by pyrodie18** [comment]
How goes it?

**Comment by BGmot** [comment]
I am sorry, got distracted again but I am through 75% of all modules and (I am already afraid to promise) should be definitely done by the end of this weekend.
@pyrodie18 by the way I noticed you replaced ' with " a lot, this is what I am doing right now for all modules to make our code "cleaner", did you get that in some recommendations? Can you share why?

**Comment by pyrodie18** [comment]
Hey I get it.  No rush.  No, those weren't deliberate changes.  I suspect my linter in VS Code does that automatically when I save a file (although a standard likely does exist or at least should).

**Comment by BGmot** [comment]
Please take a look at https://github.com/ansible-collections/community.zabbix/pull/976

**Comment by pyrodie18** [comment]
Looks great.  I haven't seen anyone else recently so if we want to go ahead and merge that.  May 15th is the last day to do the release if we want it to make it into the 8.0 release (https://docs.ansible.com/ansible/devel/roadmap/COLLECTIONS_8.html).  There anything else that we want to do that will cause breaking changes?

**Comment by BGmot** [comment]
You had some doubts/questions about new auth variables for httpapi in roles if I am not mistaken?

**Comment by BGmot** [comment]
I quickly looked at zabbix_agent role, there will be some confusion... Example `zabbix_api_http_user` and `zabbix_api_http_password` are in README but never used in the role. `zabbix_api_server_url` should be totally removed. Let me take a closer look at this aspect of roles tomorrow (it's late today here already) and we'll proceed with 2.0 release unless somebody has objections.

**Comment by pyrodie18** [comment]
Yep good call thank you.

**Comment by BGmot** [comment]
https://github.com/ansible-collections/community.zabbix/pull/977 and I am done.

**Comment by pyrodie18** [comment]
Great work!  I just did a quick browse through everything and assuming it passes the runs I don't see any issues with it.  I've never done the release before so if you want to take care of that in the next couple of days (or if you can point me to the instructions) and we can get this thing out before the end of the week.

**Comment by BGmot** [comment]
Hi @D3DeFi or @dj-wasabi would you be able to review and merge 2.0 today-tomorrow?

**Comment by BGmot** [comment]
@pyrodie18 please review and merge https://github.com/ansible-collections/community.zabbix/pull/977 and I'll start release process targeting tomorrow.

**Comment by BGmot** [comment]
https://github.com/ansible-collections/community.zabbix/pull/979 has been created for this release.
