### ISSUE TITLE
zabbix-agent2 deployment on Windows fails

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/community.zabbix#778]
##### SUMMARY
zabbix_agentd.exe and zabbix_sender.exe aren't existing in Zabbix Agent 2 package.

Deployment fails with Agent2, because of new implemented task which has hardcoded loop:
There is one condition missing for agent2...

- name: "Windows | Copy binary files to expected location"
  ansible.windows.win_copy:
    src: "{{ zabbix_win_install_dir }}\\bin\\{{ item }}"
    dest: "{{ zabbix_win_install_dir_bin }}\\{{ item }}"
    remote_src: yes
  loop:
    - zabbix_agentd.exe
    - zabbix_sender.exe
  when:
    - zabbix_win_install_dir_bin is defined

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
role-zabbix-agent

##### ANSIBLE VERSION

2.10 latest

##### OS / ENVIRONMENT / Zabbix Version
Windows Server 2019
Zabbix V6.0.7

##### EXPECTED RESULTS
Running deployment

##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_agent : Windows | Copy binary files to expected location] ***
failed: [dpw0180-van0002.nae-dmz.net] (item=zabbix_agentd.exe) => {"ansible_loop_var": "item", "changed": false, "dest": "C:\\Program Files\\Zabbix Agent 2\\\\bin\\zabbix_agentd.exe", "item": "zabbix_agentd.exe", "msg": "Cannot copy src file: 'C:\\Program Files\\Zabbix Agent 2\\bin\\zabbix_agentd.exe' as it does not exist", "src": "C:\\Program Files\\Zabbix Agent 2\\bin\\zabbix_agentd.exe"}
failed: [dpw0180-van0002.nae-dmz.net] (item=zabbix_sender.exe) => {"ansible_loop_var": "item", "changed": false, "dest": "C:\\Program Files\\Zabbix Agent 2\\\\bin\\zabbix_sender.exe", "item": "zabbix_sender.exe", "msg": "Cannot copy src file: 'C:\\Program Files\\Zabbix Agent 2\\bin\\zabbix_sender.exe' as it does not exist", "src": "C:\\Program Files\\Zabbix Agent 2\\bin\\zabbix_sender.exe"}
```

**Comment by mordekasg** [comment]
Same problem on:
Windows Server 2016/2022
Zabbix Agent2 v6.0.7
