### ISSUE TITLE
Update Apt Key management

### ISSUE THREAD

**Issue by evilhamsterman** [ansible-collections/community.zabbix#801]
##### SUMMARY
Stop using deprecated apt key management

##### ISSUE TYPE
I actually discussed this in #517 but I figured I'd mention it at a high level. I would recommend removing the usage of apt-key for all installed. That method of signing repositories has been deprecated by Debian/Ubuntu due to the key being implicitly trusted for all repos. Even the Ansible Module states it should not longer be used.

The recommended way now is to download the keys to /usr/share/keyrings then add a `signed-by=<keyfile>` to the repo for the key file that is specific to that repo E.G. `deb [signed-by=/usr/share/keyrings/deriv-archive-keyring.gpg] https://deriv.example.net/debian/ stable main`

You can see more info here https://wiki.debian.org/DebianRepository/UseThirdParty

##### COMPONENT NAME
All install sections of all roles

##### ADDITIONAL INFORMATION
This would solve the security problems identified by Debian and remove deprecation warnings when using apt commands, such as this 
```
All packages are up to date.
W: http://repo.zabbix.com/zabbix/6.2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Comment by hernandanielg** [comment]
@pyrodie18 @BGmot this issue can be closed ✌🏻
