### ISSUE TITLE
Stop installing pip packages by default

### ISSUE THREAD

**Issue by evilhamsterman** [ansible-collections/community.zabbix#807]
##### SUMMARY
Right now by default the agent and proxy modules will install various pip packages by default and even potentially requiring the use of `become` to do so. It should not do this by default.

##### ISSUE TYPE
- Bad Practice

##### ADDITIONAL INFORMATION
This is bad practice and not used in other popular roles and modules. Roles and modules should not change the controller unless explicitly requested. It can lead to breakage of the controller's system Python packages if `become` is used. It can cause false reporting of changes if you use multiple control systems (like ephemeral CI/CD systems) when no change to the managed system occurred potentially polluting reporting.

This should just be a listed requirement in the documentation and/or a requirements.txt file. If you want to leave it in the roles it should default to `false` so it is only installed if explicitly needed.

**Comment by pyrodie18** [comment]
Would probably consider this a breaking change so will incorporate into 2.0 release

**Comment by evilhamsterman** [comment]
I would too, thank  you.

**Comment by BGmot** [comment]
Should be resolved by https://github.com/ansible-collections/community.zabbix/pull/822 please check.
