### ISSUE TITLE
Collection CI related actions needed

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.zabbix#811]
##### SUMMARY
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/24.

It's been detected that this repository contains `ignore-2.14.txt` file but not `ignore-2.15.txt` file.

Actions needed:
- Copy `tests/sanity/ignore-2.14.txt` to `tests/sanity/ignore-2.15.txt` otherwise the CI will get failing.
- If it's not done yet, add the `stable-2.15` branch to your CI workflow files. If you use GitHub actions, see the content of `.github/workflows` or, if you use Azure Pipelines, `community.postgresql/.azure-pipelines/azure-pipelines.yml`. If not added, this will violate the [Collection Requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing) for collections included in the Ansible package.
- Subscribe to and track the [news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers) repository if you're not subscribed yet.
- If it's not relevant for this repo, just close the issue.

To read more about the topic, see the [Ignores](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/ignores.html) guide.

To read more about the context, see the [announcement](https://github.com/ansible-collections/news-for-maintainers/issues/24).

Thank you!

**Comment by D3DeFi** [comment]
@Andersson007 I've opened #808 3 days ago addressing this, but didn't merge right away as I've considering deprecating 2.10 and 2.11 tests, which would also drop python2.7/3.6 from our CI matrix, save sime time on builds and precious free CI minutes we are eating from Github Actions.

since I have your attention, can you add your opinion to #808?

**Comment by Andersson007** [comment]
@D3DeFi cool, LGTM, thanks! I've put `Fixes this issue` in the PR
