### ISSUE TITLE
Incorrect fping location on Debian derivatives

### ISSUE THREAD

**Issue by evilhamsterman** [ansible-collections/community.zabbix#812]
##### SUMMARY
The default value for fping is `/usr/sbin/fping` however for a while now Debian and derivatives have not placed an fping binary or symlink there. On Debian systems it should default to `/usr/bin/fping` and `/usr/bin/fping6`

In addition it appears there is a `zabbix_server_fpinglocation` variable available that could be overridden, but it is not documented.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_server role

##### ANSIBLE VERSION
NA

##### CONFIGURATION
NA

##### OS / ENVIRONMENT / Zabbix Version
Zabbix 6.2.3, Role version 1.8.0, Ubuntu 22.04

##### STEPS TO REPRODUCE
Deploy Zabbix server with the role but do not change the `zabbix_server_fpinglocation`. 

##### EXPECTED RESULTS
The fping location is set appropriately

##### ACTUAL RESULTS
It is not set appropriately leading to the error on Zabbix 

> At least one of '/usr/sbin/fping', '/usr/sbin/fping' must exist. Both are missing in the system.

**Comment by gvol1222** [comment]
Interested in fixing that. A which command on the host is good approach?

**Comment by mcbrineellis** [comment]
I'm having the same issue.  which command could be a good approach, agreed @gvol1222

**Comment by gvol1222** [comment]
> I'm having the same issue. which command could be a good approach, agreed @gvol1222 .. or set the path based on the OS type (if all Debian versions place this file in `/usr/bin` instead of `/usr/sbin`).
> 
> The simplest fix might be just to make the value configurable, and we could pass the path along as a variable to the role to update the config file, leaving the current config as the default.

It is already in the role variables, should we just update the documentation to mention the variable??

**Comment by mcbrineellis** [comment]
> It is already in the role variables, should we just update the documentation to mention the variable??

Oh nice thanks! I feel silly, I should have checked that. Of course all of the config file options are already variables. That means I can easily fix it in my playbooks.

**Comment by D3DeFi** [comment]
> Interested in fixing that. A which command on the host is good approach?

simple and working, why not :) Feel free to submit the patch if you want

**Comment by pavlozt** [comment]
Please, reopen. 
Same problem exists in zabbix_proxy role. Variables are not distro-specific. 
fping can't be found and zabbix proxy are not started.

**Comment by Hope-IT-Works** [comment]
This quick fix works:

```shell
# Create symbolic links from /usr/bin to /usr/sbin
ln -sf /usr/bin/fping /usr/sbin/fping
ln -sf /usr/bin/fping6 /usr/sbin/fping6
```

**Comment by pavlozt** [comment]
@Hope-IT-Works 
Let me remind you that this bug is related to ansible and has long been fixed in recent versions.
