### ISSUE TITLE
Support for zabbix-agent2

### ISSUE THREAD

**Issue by Richie765** [ansible-collections/community.zabbix#83]
##### SUMMARY
A new generation Zabbix Agent 2 was introduced in 4.4.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
I need it for monitoring Docker containers.
I'm guessing for now I'll install the agent2 manually.

See:

https://www.zabbix.com/documentation/current/manual/concepts/agent2
https://www.zabbix.com/integrations/docker

**Comment by D3DeFi** [comment]
Thanks for opening this issue @Richie765. 

Correct me if I do not recall it correctly, but haven't you had something like this on your mind?

**Comment by D3DeFi** [comment]
forgot to tag @ericsysmin, my bad

**Comment by D3DeFi** [comment]
@dj-wasabi do you see this possible in the near future? Should we label this issue as a `help wanted`?

**Comment by dj-wasabi** [comment]
I can/will pick this up once I finally have the Zabbix Web CI working. 👍

**Comment by SimBou** [comment]
You can precise zabbix_agent_package: zabbix-agent2.
The issue is on the service startup, I need to comment the variables zabbix_agent_service and zabbix_agent_conf from vars/* to be able to set them in the inventory file
