### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.zabbix#84]
Hi,
I've *hopefully* made the correct updates to Zuul CI so Zuul will monitor for `git tag` and do the magic of build and publish a collection release to Galaxy.

Feel free to test this at your convenience, I believe you wanted to update the changelogs first?

Please shout out once you have, or if there are any problems.

**Comment by gundalow** [comment]
Is your hope that this will be done this week?

**Comment by D3DeFi** [comment]
I believe we are ready to release very soon.

Lemme open a PR for changelog first

**Comment by D3DeFi** [comment]
Done. @gundalow is it ok if I push v0.1.0 retro actively? Wouldn't Zuul try to release v0.1.0 again?

**Comment by gundalow** [comment]
https://dashboard.zuul.ansible.com/t/ansible/builds?project=ansible-collections/community.zabbix
https://galaxy.ansible.com/community/zabbix

Need to sure galaxy.yml's version line is correct and committed to master.

**Comment by D3DeFi** [comment]
I have mixed `0.2.0` with `v0.2.0` names. Hopefully, it will do the publish this time.

**Comment by D3DeFi** [comment]
Seems to be live :) Also failed for `0.1.0` and that is ok as I've pushed that one just to have it available in repo as well

Thank you @gundalow !

**Comment by gundalow** [comment]
Woot, thanks for the quick test. Glad it worked.
