### ISSUE TITLE
Problem installing agent using proxy

### ISSUE THREAD

**Issue by gpxlnx** [ansible-collections/community.zabbix#844]
I'm having trouble installing zabbix_agent on a windows server that uses a proxy.
I analyzed the code but I couldn't insert the proxy, perhaps due to lack of knowledge.

When trying to download the zip, the error described below occurs:

TASK [community.zabbix.zabbix_agent : Windows | Download Zabbix Agent Zip file] ******************************************** ************************************************** ******************************
FAILED - RETRYING: [172.17.176.101]: Windows | Download Zabbix Agent Zip file (3 retries left).
FAILED - RETRYING: [172.17.176.101]: Windows | Download Zabbix Agent Zip file (2 retries left).
FAILED - RETRYING: [172.17.176.101]: Windows | Download Zabbix Agent Zip file (1 retries left).
fatal: [172.17.176.101]: FAILED! => {"attempts": 3, "changed": false, "dest": "C:\\Zabbix\\zabbix_agent-5.2.4-windows-amd64-openssl.zip", "elapsed": 3.0869055, "msg ": "Error downloading 'https://cdn.zabbix.com/zabbix/binaries/stable/5.2/5.2.4/zabbix_agent-5.2.4-windows-amd64-openssl.zip' to 'C:\\Zabbix\ \zabbix_agent-5.2.4-windows-amd64-openssl.zip': Unable to connect to the remote server", "status_code": null, "url": "https://cdn.zabbix.com/zabbix/binaries/ stable/5.2/5.2.4/zabbix_agent-5.2.4-windows-amd64-openssl.zip"}

Could someone help me to insert the proxy when installing the agent?

Thanks

**Comment by mu1f407** [comment]
Hi @gpxlnx, you could try to set `zabbix_https_proxy` variable (in your playbook or command line). See [roles/zabbix_agent/tasks/Windows.yml#L186](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/Windows.yml#L186). I think this should be enough if your proxy doesn't require an authentication.
