### ISSUE TITLE
Collection 1.9.0 breaks HTTP Basic auth

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-collections/community.zabbix#848]
##### SUMMARY

After upgrading the collection to 1.9.0, I can no longer run API transactions with Zabbix after it moved to httpapi.

In my current environment the setup is as follows:

- The HTTP server is joined to an IdM domain
- Basic Authentication is enabled (and required)
- Zabbix itself is not configured to read accounts from LDAP (as most users come from a trusted AD)

This worked fine with the previous implementation (where HTTP and API credentials could be supplied separately), but now it seems to be broken as the credentials are not passed properly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_agent role
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2] on RHEL8 (can't copy/paste from that system to here)
```

##### OS / ENVIRONMENT / Zabbix Version

Target OS: RHEL8
Zabbix: 6.0 LTS

**Comment by BGmot** [comment]
Please post the error you are getting as "seems to be broken" is very vague description of the problem.
In regards to Basic Authentication - Zabbix API never had Basic Authentication so it would help again if you listed all the variables you define and a module invocation code.

**Comment by Thulium-Drake** [comment]
I did some further testing, I either receive HTTP 401 errors or the API returns code -32602 Not Authorized.

Before I started working on this the API password was not the same as the LDAP password of the user. I have reconfigured Zabbix to have the same password for both HTTP and the API, the serviceaccount I'm using has Super Admin privileges within the Zabbix server.

However, I'm unable to interact with the API as of now.

I also find the current state of the variable names quite confusing, as new variable sets are pointing to deprecated vars, but it laos _looks_ like I need to set 2 sets, one for the API and one for HTTP Basic auth.

My current config is as follows:

```
zabbix_api_login_user: zabbix_api
zabbix_api_login_pass: LDAP_PASSWORD
ansible_httpapi_pass: "{{ zabbix_api_login_pass }}"
```

However, as mentioned, no dice

**Comment by BGmot** [comment]
Variables is a mess, I agree and we are going to clean them up in 2.0.
Right now you should not need to change any variables you used with 1.8. Can you post all the variables you define in your playbook (related to API)?

**Comment by Thulium-Drake** [comment]
So I did the following:

- Revert back to 1.8.0
- Check the current variables (after changing the password) to exclude any mismatched passwords

The current vars are as follows:

```
zabbix_api_http_user: zabbix_api
zabbix_api_http_password: LDAP_PASSWORD
zabbix_api_login_user: "{{ zabbix_api_http_user }}"
zabbix_api_login_pass: "{{ zabbix_api_http_password }}"
```

These do work for 1.8.0, but result in a HTTP 401 in 1.9.0.

I'm able to workaround the HTTP 401 by adding the variable below:

```
ansible_httpapi_password: "{{ zabbix_api_http_password }}"
```
But then I'm stuck with Zabbix API throwing  "Not Authorized" errors. And interestingly the first attempt _always_ times out after 30 seconds.

**Comment by BGmot** [comment]
I don't understand where you are getting HTTP 401 from.
Zabbix API does not use Zabbix Web UI interface so no basic authentication possible.
Zabbix API cannot give you HTTP 401 as it always gives you HTTP 200 with an error message inside JSON (if there is any error) - is it where you are seeing "Not Authorized" message?
Everything above is true regardless of whether we use zabbix-api or httpapi to talk to Zabbix API.
Are you able to post full Ansible output here? Because I am kind of stuck and don't see why it would fail once you provide `ansible_httpapi_password`.
What is `zabbix_api_server_url` by the way? with `zabbix` at the end or without?

**Comment by D3DeFi** [comment]
I think this may be replicable just by deploying Nginx with basic auth enabled before Zabbix Server. This is normally something that zabbix-api library supported, we are not tying ourselves to Zabbix API here per see.

For example, doc snippet was removed in here: https://github.com/ansible-collections/community.zabbix/blob/15b439fcf832317947a9c3b62bef836e5bfcf6de/plugins/doc_fragments/zabbix.py#L32-L39 and I did not notice it. This breaks backwards compatibility.

@Thulium-Drake thanks for reporting this issue!

**Comment by Thulium-Drake** [comment]
I won't be having access to the environment where I noticed this for the rest of the week.

But yes, the ```server_url``` is ```https://zabbix.example.com/zabbix```

And what @D3DeFi said is correct, just hook up any webserver with Basic Auth and you're good to go :-)

**Comment by BGmot** [comment]
I was not even aware of such a usecase (basic authentication done by http server in front of Zabbix server).
I have reproduced the issue.
Trying to understand how it works and needs to be done to fix 1.9.
Thabjs @Thulium-Drake and @D3DeFi .

**Comment by Thulium-Drake** [comment]
Well that's because the API can't do Header authtentication (and the devs don't seem eager to change that). However, in my environment we have Kerberos SSO with the WebUI for all admins. And in order for Ansible to _also_ be able to talk to the API, we need to provide the password twice...

**Comment by BGmot** [comment]
It's not that complicated to add one more header "Authorization: bla-bla" but fun fact... underlying netcommon connection module generates its own "Authorization:" header whenever it sees "user" and "password" in payload and its `auth` variable is `None` (our very first REST API call when Zabbix token is not used) thus it will work when username/password combination is the same for Basic Authentication and in Zabbix. I'll keep digging.

**Comment by BGmot** [comment]
Hi @Thulium-Drake , would you be able to test basic auth off this branch https://github.com/BGmot/community.zabbix/tree/bgmot_fix_httpapi_basic_auth ?

**Comment by Thulium-Drake** [comment]
Will do, I'll let you know tomorrow :-)

**Comment by Thulium-Drake** [comment]
Works like a charm, without changing any variables in my config :-)

It does complain about the following parameters that are deprecated:

```
server_url
login_user
login_password
timeout
validate_certs
```

I'm using ansible-core 2.13.3

If that's expected, I'd say it's all good now :-)

**Comment by BGmot** [comment]
Thanks for testing!
And it is expected as we were going to deprecate them in 2.0. it actually complains even if you don't provide any of them and I don't know how to fix it (see https://github.com/ansible-collections/community.zabbix/issues/857)
