### ISSUE TITLE
Update docs.ansible.com for deprecated parameters in community.zabbix.maintenance

### ISSUE THREAD

**Issue by jorymil** [ansible-collections/community.zabbix#849]
##### SUMMARY

https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_maintenance_module.html#ansible-collections-community-zabbix-zabbix-maintenance-module
currently shows server_url as a required option, but in the actual module, this option is shown as deprecated.  Please edit the Ansible documentation to match the actual module functionality.

I've checked this for the community.zabbix.maintenance module, but it likely is present in the documentation for other modules.  I'm unfamiliar with how to edit the official Ansible docs, but happy to help if given a little guidance.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

maintenance

**Comment by D3DeFi** [comment]
Hi, doc.ansible.com is auto-generated from collections each time there is and update to ansible, not to the collection. As you can see in the note: `This module is part of the [community.zabbix collection](https://galaxy.ansible.com/community/zabbix) (version 1.8.0).` 

But the deprecation was not released until 1.9.0 a couple of days ago. The documentation will show correct information once the next release of ansible is done (I am not sure if minor is enough, I think they only bump collections in major releases), which is not something we are able to do ourselves.
