### ISSUE TITLE
API displays warnings even if old options are not used (`Option "server_url" is deprecated`)

### ISSUE THREAD

**Issue by Vanav** [ansible-collections/community.zabbix#857]
Task:
```
  - name: "API | Create host groups"
    zabbix_group:
      host_group:
      - Other servers
    vars:
      ansible_connection: httpapi
      ansible_network_os: community.zabbix.zabbix
      ansible_user: '{{ zabbix_api_login_user }}'
      ansible_httpapi_pass: '{{ zabbix_api_login_pass }}'
      ansible_httpapi_use_ssl: '{{ (zabbix_api_server_url | urlsplit("scheme") == "https") | ternary(true, false) }}'
    delegate_to: '{{ zabbix_api_server_url | urlsplit("hostname") }}'
```
Warnings:
```
TASK [zabbix : API | Create host groups] ***********************************************************************
[WARNING]: Option "server_url" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_user" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_password" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "timeout" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "validate_certs" is deprecated with the move to httpapi connection and will be removed in the next release
ok: [prod_host_node -> zabbix.example.com]
```

Command: `ansible-playbook site.yml -l prod_hosts --check -vvv`
Result:
```
TASK [zabbix : API | Create host groups] [CHECK MODE] ********************************************************************************
task path: /srv/Projects/example.com/infra/roles/zabbix/tasks/main.yml:157
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
redirecting (type: modules) ansible.builtin.zabbix_group to community.zabbix.zabbix_group
redirecting (type: modules) ansible.builtin.zabbix_group to community.zabbix.zabbix_group
Using module file /opt/pipx/venvs/ansible/lib/python3.10/site-packages/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py
Pipelining is enabled.
<zabbix.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<zabbix.example.com> EXEC /bin/sh -c '/opt/pipx/venvs/ansible/bin/python && sleep 0'
[WARNING]: Option "server_url" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_user" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_password" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "timeout" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "validate_certs" is deprecated with the move to httpapi connection and will be removed in the next release
ok: [prod_host_node -> zabbix.example.com] => 
    changed: false
    invocation:
        module_args:
            host_group:
            - Other servers
            host_groups:
            - Other servers
            login_password: null
            login_user: null
            server_url: null
            state: present
            timeout: 10
            validate_certs: true
```

Environment:
```
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/pipx/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/opt/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True

community.zabbix              1.9.0

ANSIBLE_PIPELINING(/srv/Projects/xxx/infra/ansible.cfg) = True
CONFIG_FILE() = /srv/Projects/xxx/infra/ansible.cfg
DEFAULT_FORCE_HANDLERS(/srv/Projects/xxx/infra/ansible.cfg) = True
DEFAULT_JINJA2_NATIVE(/srv/Projects/xxx/infra/ansible.cfg) = True
DIFF_ALWAYS(/srv/Projects/xxx/infra/ansible.cfg) = True
INTERPRETER_PYTHON(/srv/Projects/xxx/infra/ansible.cfg) = auto

Zabbix 6.2.6
```

**Comment by BGmot** [comment]
I can't reproduce. You are not listing all variables - I see  your code uses `zabbix_api_server_url` but it's not defined in `vars:`. Maybe you have some defaults or vars defined in inventory?
Our code is literally does:
```
    for p in ['server_url', 'login_user', 'login_password', 'timeout', 'validate_certs']:
        if p in module.params:
            module.warn('Option "%s" is deprecated with the move to httpapi connection and will be removed in the next release' % p)
```

**Comment by BGmot** [comment]
Ok, thanks. I’ll do exactly the same tomorrow morning (it’s late evening already here) and report back.

**Comment by BGmot** [comment]
Hmm... reproduced! Investigating.

**Comment by BGmot** [comment]
Fun fact, it is producing warnings only for the first Zabbix module in a playbook. I've slightly modified your playbook
```
ey@ls1:~/ansible$ cat test_deprecated_warnings.yml
- name: Test
  hosts: 192.168.148.200
  gather_facts: false
  vars:
    ansible_connection: httpapi
    ansible_network_os: community.zabbix.zabbix
    ansible_user: Admin
    ansible_httpapi_pass: zabbix
    ansible_httpapi_use_ssl: false
    ansible_zabbix_url_path: 'zabbix'
  tasks:
  - name: API | Create host groups
    zabbix_group:
      host_group:
      - Other servers
  - name: API | Create host groups 1
    zabbix_group:
      host_group:
      - Other servers 1
```
Now executing
```
ey@ls1:~/ansible$ ansible-playbook test_deprecated_warnings.yml -i 192.168.148.200, --check

PLAY [Test] **********************************************************************************************************************************************************************************************************

TASK [API | Create host groups] **************************************************************************************************************************************************************************************
[WARNING]: Option "server_url" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_user" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "login_password" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "timeout" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "validate_certs" is deprecated with the move to httpapi connection and will be removed in the next release
ok: [192.168.148.200]

TASK [API | Create host groups 1] ************************************************************************************************************************************************************************************
changed: [192.168.148.200]

PLAY RECAP ***********************************************************************************************************************************************************************************************************
192.168.148.200            : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
... digging further.

**Comment by BGmot** [comment]
We still provide all these parameters with defaults https://github.com/ansible-collections/community.zabbix/blob/main/plugins/module_utils/helpers.py#L20
It's easy to analyze for `None` and to not produce a warning but we'll still have this:
```
ey@ls1:~/ansible$ ansible-playbook test_deprecated_warnings.yml -i 192.168.148.200, --check

PLAY [Test] **********************************************************************************************************************************************************************************************************

TASK [API | Create host groups] **************************************************************************************************************************************************************************************
[WARNING]: Option "timeout" is deprecated with the move to httpapi connection and will be removed in the next release
[WARNING]: Option "validate_certs" is deprecated with the move to httpapi connection and will be removed in the next release
```
Not sure what to do with `timeout` and `validate_certs`...
Although if `server_url` is not defined then these two do not make any sense. @D3DeFi what do you think? Should we do anything here?

**Comment by BGmot** [comment]
> Hmm I think that if we remove defaults from these for 1.9.1 then we risk breaking backwards compatibility sooner than 2.0.0
Correct.
Interesting/confusing part is that this is always True for very first Zabbix module use in a playbook:
```
    for p in ['server_url', 'login_user', 'login_password', 'timeout', 'validate_certs']:
        if p in module.params:
```
for all other modules in the playbook (different modules!) it is False (unless of course we provide them explicitly as arguments to modules).
I'll implement a check for None and submit a PR, this is the best we can do now.

**Comment by BGmot** [comment]
By the way does anybody know how we can approach Ansible gurus (RedHat?), I saw them on Reddit trying to get some answers how it is supposed to work https://www.reddit.com/r/ansible/comments/zk0fjd/comment/j04roxk/?context=3

**Comment by D3DeFi** [comment]
@Andersson007 are you please able to assist? How best to deprecate module parameters for the next version? Currently, deprecation warning are shown even if user does not provide the parameter

**Comment by BGmot** [comment]
Wanted to mention that I tried removed_in_version/removed_from_collection and this does not produce any warnings. Ever.

**Comment by Andersson007** [comment]
@D3DeFi sorry for the late reply (had long PTO), is the question still relevant?

@BGmot could you please raise an issue against https://github.com/ansible/ansible ? i's super important

**Comment by D3DeFi** [comment]
> @D3DeFi sorry for the late reply (had long PTO), is the question still relevant?
> 
> @BGmot could you please raise an issue against https://github.com/ansible/ansible ? i's super important

I think this is still relevant. If parameter has a default, ansible will show deprecation warning even if user is not using said parameter. For our use case, @BGmot has solved it differently, but problem is still there.

**Comment by Andersson007** [comment]
@D3DeFi you're talking about `timeout` and `validate_cert`, right?
In this case
- I would remove the `default: ..` from `zabbix_common_argument_spec` and from the doc fragment entries (I would specify it in the argument's description instead to avoid sanity failings)
- In module's code, i'd check 1) if nothing was passed (which should result in `None`), no warning is needed, just assign the default value to the argument then 2) else (something is passed, i.e. not None), raise the warning.

Speaking about your particular case, shouldn't your users see the warning in any case as they can rely on the defaults?
I can see `is deprecated with the move to httpapi connection`. Can they use this `httpapi` interface right now and are they mutually exclusive with `timeout` and the others?
If they can use both simultaneously or if they can use the old interface, i would:
- Check if the new interface is used. If yes I would apply the logic I describe above
- if they don't use the new interface, I would raise the warning saying that they rely on the default values which be replace with the new interface soon

Maybe there's a better solution, you could also ask in https://matrix.to/#/#community:ansible.com

**Comment by felixfontein** [comment]
I created an issue in ansible-core: https://github.com/ansible/ansible/issues/79680

Also please note that you should use `module.deprecate()`  for deprecation warnings, and not `module.warn()`.

**Comment by BGmot** [comment]
>     * I would remove the `default: ..` from `zabbix_common_argument_spec` and from the doc fragment entries (I would specify it in the argument's description instead to avoid sanity failings)

I am sorry, where is this "argument's description"?


> Speaking about your particular case, shouldn't your users see the warning in any case as they can rely on the defaults?

We are trying to move connection to Zabbix API from "third-party" zabbix-api Python module to "native to Ansible" httpapi connection. In this 1.9 version users still can use both connection types. If user defines `ansible_connection: httpapi` then we use httpapi otherwise zabbix-api. In version 2.0 we are going to get rid of zabbix-api completely thus this necessity to produce deprecation warnings.

**Comment by Andersson007** [comment]
>I am sorry, where is this "argument's description"?

Under `plugins/doc_fragments`, the field called `description:` belonging to the arguments. You can remove the `default: ` key and just add to `description` "The default value is C(...)"

>We are trying to move connection to Zabbix API from "third-party" zabbix-api Python module to "native to Ansible" httpapi connection. In this 1.9 version users still can use both connection types. If user defines ansible_connection: httpapi then we use httpapi otherwise zabbix-api. In version 2.0 we are going to get rid of zabbix-api completely thus this necessity to produce deprecation warnings.

So if there's a way to determine in the code that `ansible_connection: httpapi` is used i would follow the logic I mentioned at the end of https://github.com/ansible-collections/community.zabbix/issues/857#issuecomment-1373403376

**Comment by BGmot** [comment]
Yes there is a way to determine in the code that new connection method is used and we are doing it, I'll play with `default:`. Thanks!
