### ISSUE TITLE
Permission of template groups

### ISSUE THREAD

**Issue by cleberb** [ansible-collections/community.zabbix#879]
Hi,

I would like to know how to set permission of template groups ( templategroup_rights ) for user group. I did not find this option, even though it is present in the API.

https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_usergroup_module.html:

![image](https://user-images.githubusercontent.com/30322023/212961631-9edcae41-bdb5-427f-a7e3-ed230ed8011b.png)

![image](https://user-images.githubusercontent.com/30322023/212961905-c3c46434-481f-44c5-8fec-493a1b7ecefb.png)

**Comment by chladic** [comment]
@cleberb did you find solution for this ?

**Comment by cleberb** [comment]
> @cleberb is your zabbix 6.2 at least ?

Yes.

**Comment by cleberb** [comment]
Fix!
