### ISSUE TITLE
zabbix_server: support SCRAM password hash for PostgreSQL

### ISSUE THREAD

**Issue by krauthosting** [ansible-collections/community.zabbix#886]
##### SUMMARY

We still only support old and weak MD5 while PostgreSQL support SCRAM since version 10.  
With new installations defaulting to `password_encryption = scram-sha-256` this fails the role.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
roles/zabbix_server

##### STEPS TO REPRODUCE
Install `postgresql` package on Ubuntu 22.04 and run role against it.

**Comment by BGmot** [comment]
Would you like to submit a PR similar to this https://github.com/ansible-collections/community.zabbix/pull/871 ?

**Comment by krauthosting** [comment]
@BGmot Was already at it and just found #871 in the git log before committing and then here :)
Thx for the head up reworked now what we used internally and dropped the additional env:
```
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
```

**Comment by BGmot** [comment]
sorry for commenting too early -(

**Comment by krauthosting** [comment]
Closing as PR #887 merged :+1:
