### ISSUE TITLE
httpapi breaks my use case.

### ISSUE THREAD

**Issue by calebsdaddy** [ansible-collections/community.zabbix#891]
My use case is as follows:

I've created a role for full installation of zabbix from scratch, server (with frontend), proxy, and agent. For proxy and agent, once that component is finished installing, the last task(s) configure zabbix server with the proxy or agent information for that host. 

I noticed deprecation messages for the following parameters (after upgrading the 1.9.1):
  - server_url
  - login_user
  - login_password
 
This effectively kills my use case, because the configuration of the proxy or host in zabbix server is iterative to the host being "installed" at that moment. 

I'm not sure if there's a way to keep using the zabbix-api pip, or to extend the httpapi to allow for configuration of the deprecated parameters, but with thousands of hosts to manage, my use case works best for my purposes, and I'd hate to have to stop using this collection because of this.

**Comment by BGmot** [comment]
It does not break anything. All the roles are actually already using httpapi under the hood. Just try switching to new variables instead of deprecated ones and you are good to go.

**Comment by D3DeFi** [comment]
Indeed! You just have to swap one set of variables for another and you hosts should not even notice! :)

Here is preview what variables you need for modules:
https://github.com/ansible-collections/community.zabbix#usage

And here you can find example for zabbix_agent role:
https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md#zabbix-api-variables
