### ISSUE TITLE
DISCUSSION:  How to handle vars files for various OS versions

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#898]
##### SUMMARY
Would like to have a discussion about what is the best way to handle vars that are unique to a particular OS version (i.e. RHEL 7, 8, 9).  I've seen two ways of doing this.  Have seperate files (i.e. RedHat-7.yml, RedHat-8.yml, etc.) and each file contains the various variables that are unique to that version, and I've also seen a single RedHat.yml that contains a dict of everything such as:

```
pgsql_depenencies:
  "9":
    - python3-psycopg2
  "8":
    - python3-psycopg2
  "7":
    - python-psycopg2

mysql_client_pkgs:
  "9":
    - mysql
    - python3-PyMySQL
  "8":
    - mysql
    - python3-PyMySQL
  "7":
    - mariadb
    - MySQL-python
```

Which way do you think is cleaner?

**Comment by BGmot** [comment]
I'd put this in roles/zabbix_[server|proxy]/vars/RedHat.yml
So single RedHat.yml

**Comment by dj-wasabi** [comment]
Yes, single file looks cleaner to me. 👍

**Comment by D3DeFi** [comment]
well, I am with the majority then :D

**Comment by pyrodie18** [comment]
OK looks like we have a consensus.
