### ISSUE TITLE
Getting error for API | Create host groups and host error

### ISSUE THREAD

**Issue by dilip400590** [ansible-collections/community.zabbix#912]
TASK [community.zabbix.zabbix_agent : Run the API calls to Zabbix Server] ******
task path: /opt/cspzabbix/ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/main.yml:123
included: /opt/cspzabbix/ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/api.yml for cspkibana

TASK [community.zabbix.zabbix_agent : API | Create host groups] ****************
task path: /opt/cspzabbix/ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/api.yml:2
skipping: [cspkibana] => {
    "changed": false,
 "skip_reason": "Conditional result was False"		
}

TASK [community.zabbix.zabbix_agent : API | Create a new host or update an existing host's info] ***
task path: /opt/cspzabbix/ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/api.yml:17
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<10.8.100.6> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.8.100.6> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-458006sejk4i `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504 `" && echo ansible-tmp-1678165401.0651073-4886-62184008276504="` echo /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504 `" ) && sleep 0'
Using module file /opt/cspzabbix/ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py
<10.8.100.6> PUT /root/.ansible/tmp/ansible-local-458006sejk4i/tmpkt_nhg7a TO /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/AnsiballZ_zabbix_host.py
<10.8.100.6> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/ /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/AnsiballZ_zabbix_host.py && sleep 0'
<10.8.100.6> EXEC /bin/sh -c '/opt/cspzabbix/python/bin/python3.8 /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/AnsiballZ_zabbix_host.py && sleep 0'
<10.8.100.6> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: [cspkibana -> 10.8.100.6]: API | Create a new host or update an existing host's info (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-458006sejk4i/ansible-tmp-1678165401.0651073-4886-62184008276504/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_8qjbg_mk/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1291, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_8qjbg_mk/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1085, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_8qjbg_mk/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_8qjbg_mk/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_8qjbg_mk/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n</body></html>\n\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "retries": 4

**Comment by BGmot** [comment]
What parameters do you provide to the module? Most probably you are trying to access http(s)://<zabbix_url>/zabbix while Zabbix WebUI is running on http(s)://<zabbix_url>/ or vice versa.

**Comment by amg-web** [comment]
i have same problem
I put to all vars all zabbix server configs:
```
ansible_network_os: community.zabbix.zabbix
ansible_connection: httpapi
ansible_zabbix_auth_key: b1c22da021151kdshrglkdsjghlkdsjgh5cc54062ff98fc1bd0b7dc84
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_zabbix_url_path: ''
```
but what var to be used for zabbix server domain?

All my efforts are broken since ansible put ip of the deployed server but not the zabbix server url

**Comment by BGmot** [comment]
> it works. but ansible_host is a variable which will be broken for server deplyment and contain ip of the deployed server.
> we need to make it possible to use another variable for zabbix server domain or ip.

Use `delegate_to`

**Comment by BGmot** [comment]
It can be done in several ways, you might wish to take a look how we do this in zabbix-agent role https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/main.yml#L123

**Comment by amg-web** [comment]
@BGmot 
Thanks. I was confused by example in ansible docs page.

so I proposed changes https://github.com/ansible-collections/community.zabbix/pull/920

**Comment by postcert** [comment]
I'm having a connection error as well but with "File no found." instead.
`ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.`

My configuration is very similar and I've check some other agent role usages on github to compare
```
- name: Install the Zabbix agent
  hosts: pxc
  roles:
    - role: community.zabbix.zabbix_agent
      # become: true
      vars:
        zabbix_agent_become_on_localhost: true
        zabbix_agent_server: zabbix.domain.int
        zabbix_agent_serveractive: zabbix.domain.int
        zabbix_api_create_hosts: true
        # zabbix_api_create_hostgroup: true
        zabbix_api_server_host: zabbix.domain.int
        zabbix_api_server_port: 443
        zabbix_api_use_ssl: true
        zabbix_api_validate_certs: false
        zabbix_api_login_user: Admin
        zabbix_api_login_pass: zabbix
        zabbix_api_use: true
        zabbix_useuip: 0
        zabbix_host_groups:
          - name: pxc-test
```

My understanding is the ansible httpapi is being ran on the instance and hitting the zabbix api to self-register and I am able to curl from these nodes to perform a login.

```
ansible@bbbbcc06-46c0-42a9-b0c0-59d09cb08144:~$ curl -k --request POST   --url https://zabbix.ukg.int/api_jsonrpc.php   --header 'Content-Type: application/json'   --data '{
    "jsonrpc": "2.0",
    "method": "user.login",
    "params": {
        "user": "Admin",
        "password": "zabbix"
    },
    "id": 1
}'
{"jsonrpc":"2.0","result":"408c62c2e35ff4115fc301111d3128de","id":1}
```

**Comment by BGmot** [comment]
> I'm having a connection error as well but with "File no found." instead. `ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.`
> 
> My configuration is very similar and I've check some other agent role usages on github to compare
> 
> ```
> - name: Install the Zabbix agent
>   hosts: pxc
>   roles:
>     - role: community.zabbix.zabbix_agent
>       # become: true
>       vars:
>         zabbix_agent_become_on_localhost: true
>         zabbix_agent_server: zabbix.domain.int
>         zabbix_agent_serveractive: zabbix.domain.int
>         zabbix_api_create_hosts: true
>         # zabbix_api_create_hostgroup: true
>         zabbix_api_server_host: zabbix.domain.int
>         zabbix_api_server_port: 443
>         zabbix_api_use_ssl: true
>         zabbix_api_validate_certs: false
>         zabbix_api_login_user: Admin
>         zabbix_api_login_pass: zabbix
>         zabbix_api_use: true
>         zabbix_useuip: 0
>         zabbix_host_groups:
>           - name: pxc-test
> ```
> 
> My understanding is the ansible httpapi is being ran on the instance and hitting the zabbix api to self-register and I am able to curl from these nodes to perform a login.
> 
> ```
> ansible@bbbbcc06-46c0-42a9-b0c0-59d09cb08144:~$ curl -k --request POST   --url https://zabbix.domain.int/api_jsonrpc.php   --header 'Content-Type: application/json'   --data '{
>     "jsonrpc": "2.0",
>     "method": "user.login",
>     "params": {
>         "user": "Admin",
>         "password": "zabbix"
>     },
>     "id": 1
> }'
> {"jsonrpc":"2.0","result":"408c62c2e35ff4115fc301111d3128de","id":1}
> ```
> 
> The same error will occur as well and earlier with the hostgroup creation. I just had it commented out in this instance.


Try setting `ansible_zabbix_url_path: "/"` variable

**Comment by postcert** [comment]
Sadly the same result after adding `ansible_zabbix_url_path: "/"` to the vars for the role.

**Comment by BGmot** [comment]
That's different error. We solved it but have not released new version of this collection yet. See https://github.com/ansible-collections/community.zabbix/issues/909

**Comment by postcert** [comment]
Yes, I just found that one in the issue search. Thanks for your prompt help! I'll go ahead and downgrade my `netcommon` for the moment then.
You did catch the `url_path` issue though!

**Comment by BGmot** [comment]
@amg-web can we close this one?

**Comment by amg-web** [comment]
@BGmot 
I was not a topik starter.
as for me all is clear now.
