### ISSUE TITLE
ansible_zabbix_auth_key with zabbix inventory plugin

### ISSUE THREAD

**Issue by fasdrubalpsg** [ansible-collections/community.zabbix#914]
##### SUMMARY
Use token with zabbix Inventory plugin (or fix zabbix.user from the module)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_inventory

##### ADDITIONAL INFORMATION
Actually, some zabbix modules can use api token instead of username/password, but not this one.
With zabbix 6.4, as zabbix user method is broken, the token method allow to continue using the module.

**Comment by BGmot** [comment]
We don't have zabbix_inventory module. What are you referring to?

**Comment by fasdrubalpsg** [comment]
this module : 
https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_inventory_inventory.html

**Comment by BGmot** [comment]
It's not a module. It's an inventory plugin. It utilizes zabbix-api that does not support API tokens. It needs to be re-coded to move away from zabbix-api.

**Comment by fasdrubalpsg** [comment]
my bad, i'm quite new to ansible (first 2 days formation 3 month ago). so yes, it's the inventory, will wait for the re-code :) i had to restore 6.2 version of my zabbix environnement into a staging server in order to keep my automations functionnal.
We may have upgrade a bit too early :-D but too much good improvements to wait.

**Comment by fasdrubalpsg** [comment]
Hello, any news about the zabbix inventory plugin for 6.4.X support ?

**Comment by pyrodie18** [comment]
@BGmot , how do we want to handle this for 2.0?  Temporarily deprecate the inventory plugin and then recode/reintroduce it at a later date?

**Comment by BGmot** [comment]
It's already implemented in 2.0 branch.
