### ISSUE TITLE
zabbix proxy packages need renaming for CentOS

### ISSUE THREAD

**Issue by dberardo-com** [ansible-collections/community.zabbix#918]
seems lke packages do exist, but without the version number in their name. however i cannot change the pacakge name from vars:

```
 FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'zabbix-proxy-pgsql-5.0.*' found available, installed or updated", "rc": 126, "results": ["No package matching 'zabbix-proxy-pgsql-5.0.*' found available, installed or updated"]}
```

**Comment by pyrodie18** [comment]
Thank you but need a little bit more information from you.  Can you please update or reply with the below information:

##### SUMMARY


##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME


##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version



##### STEPS TO REPRODUCE



```yaml

```



##### EXPECTED RESULTS



##### ACTUAL RESULTS



```paste below

**Comment by pyrodie18** [comment]
No additional information received...closing
