### ISSUE TITLE
Zabbix 6.4 compatibility - modules

### ISSUE THREAD

**Issue by BGmot** [ansible-collections/community.zabbix#919]
There is a substantial amount of changes that need to happen to make this collection compatible with Zabbix 6.4.
I am going to work on modules https://www.zabbix.com/documentation/6.4/en/manual/api/changes.
Anybody willing to take on roles? please create separate Issue.
Thanks.

**Comment by pyrodie18** [comment]
I am nearly done with the 2.0 roles update.  I'm about half way through the web role and then just the agent which hopefully won't be to bad.  Currently doesn't include 6.4 in it but can add it to the testing and make fixes
