### ISSUE TITLE
How will the releases of the collection will be executed?

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#93]
##### SUMMARY
One of the big upsides of the role/collection separation from the ansible-core is the possibility for the collections to be way more "agile" (yeah I don't like the word too but ...).

How do you plan to go along with this? Doing minor version bumps also on smaller issues every now and then or just going for the big ones slowly?

It would be cool if we maybe even could have a "nightly" branch to test things out even quicker. I know one can always go with the git-repo but in some corporate environments this isn't always possible that easy. A "official" ansible-galaxy pull off some sort would be great here.

##### ISSUE TYPE
- Documentation Report

**Comment by D3DeFi** [comment]
Heh, #26 

We unfortunately still haven't got to this one as there were so many changes required to properly put the collection on its legs and include roles as well. And there still are 😪 

I think it is more probable that we will go with "Doing minor version bumps also on smaller issues every now and then", but keeping this open for now so it presses us harder to discuss this 😄

**Comment by rockaut** [comment]
Nice. Sorry haven't seen #26.
I completely understand and support this.

**Comment by D3DeFi** [comment]
I am still no more wise then when I replied to you in the June :D I believe we should do gitter meet regarding this once we ship 1.0.0 and the ansible 2.10 is out

**Comment by D3DeFi** [comment]
Closing as #26 was closed and we also created a release policy for this collection
