### ISSUE TITLE
zabbix_action -> filter.condition[].operator is not defined

### ISSUE THREAD

**Issue by dberardo-com** [ansible-collections/community.zabbix#930]
it seems that the zabbix_Action module does not passes the "operator" field from the conditions yaml map info the json_rpc filter field.

happening with collection 1.9.2 zabbix server 6.2

**Comment by dberardo-com** [comment]
i rectify: this happens when using a not allowed operator ">" --> the validation seems not to catch this, changing it to ">=" fixes this issue

**Comment by BGmot** [comment]
Zabbix does not support "greater than operator", please see https://www.zabbix.com/documentation/current/en/manual/config/notifications/action/conditions
