### ISSUE TITLE
zabbix_user need an update for user with media_type

### ISSUE THREAD

**Issue by david-moreau** [ansible-collections/community.zabbix#934]
HI,
Thanks for your job !

The 1.9.2 tag doesn't include the change on method user.create  but the code seems ready on [main](https://github.com/ansible-collections/community.zabbix/blob/01fdcc4a2799e027d74545a77bc49a9cabea3d9b/plugins/modules/zabbix_user.py#L527).

[ZBXNEXT-8085](https://support.zabbix.com/browse/ZBXNEXT-8085) user.create, user.update: Removed support for deprecated parameter user_medias.

**Comment by BGmot** [comment]
Yes, 1.9.2 will never have this. Please wait for 1.9.3 release.
