### ISSUE TITLE
special symbol in DB password

### ISSUE THREAD

**Issue by badfiles** [ansible-collections/community.zabbix#973]
If postgres DB password would end in \ the GUI won't start

cat /etc/zabbix/web/zabbix.conf.php
```
...
$DB['PASSWORD']    = '*****\';
$DB['ENCRYPTION']  = false;
...
```

```
[error] 1120#1120: *28 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected identifier "ENCRYPTION" in /etc/zabbix/web/zabbix.conf.php on line 11" while reading response header from upstream,
```

**Comment by pyrodie18** [comment]
@badfiles , I'm a little confused.  Are you saying that you used a password that ended with a '\' and that posgres errored?

**Comment by badfiles** [comment]
come on, I showed you `cat` explication
could anything be clearer?

And text 
```
ending in \
```
means exactly what is does, last pass symbol is \

**Comment by dj-wasabi** [comment]
@badfiles no need for this tone. We all do our best and maybe overlook things (as this is our free time that we spend on this collection) and have a lot of other things going at the same time.

**Comment by pyrodie18** [comment]
Please provide the rest of the information that was requested in the ticket issue template.

Paste verbatim output from "ansible --version"

##### CONFIGURATION
 Paste verbatim output from "ansible-config dump --only-changed" between quotes

##### OS / ENVIRONMENT / Zabbix Version
Provide all relevant information below, e.g. target OS versions, network device firmware, etc.

**Comment by pyrodie18** [comment]
No additional feedback received....closing

**Comment by badfiles** [comment]
seriously?
this bug does not depend on what you're asking

**Comment by badfiles** [comment]
and could be reproduced 100% on any system

**Comment by BGmot** [comment]
Seriously. How is related to this collection? File a bug with Zabbix https://support.zabbix.com if you can't escape '\'.

**Comment by badfiles** [comment]
the collection creates the file /etc/zabbix/web/zabbix.conf.php
php can't understand what's in the file
zabbix has nothing to do with this, the collection should either prohibit password ending with \ or add an extra \ for php file

**Comment by pyrodie18** [comment]
@badfiles, there are 101 things that can possibly go wrong on every install.  We don't check for most of them because it simply isn't possible.  If you'd like to create a PR to fix this, you're absolutely welcome to but it's outside of the core focus of the collection which is to provide modules and roles that support the majority of use cases.

**Comment by BGmot** [comment]
> the collection creates the file /etc/zabbix/web/zabbix.conf.php php can't understand what's in the file zabbix has nothing to do with this, the collection should either prohibit password ending with \ or add an extra \ for php file

One more time: how would you configure this in Zabbix config without this collection? Once you figure this out it is very easy to make this collection do the same.
