### ISSUE TITLE
Support for Zabbix native HA on server and proxies

### ISSUE THREAD

**Issue by damo2929** [ansible-collections/community.zabbix#999]
##### SUMMARY
Zabbix added native HA support in version 6 of Zabbix 
however, looking at the templates for the server and proxy and I don't see the new keys to support it.

##### ISSUE TYPE
- Feature Idea
 add new keys to support native ha

##### COMPONENT NAME
Server, proxy ,agent

**Comment by david-sieg** [comment]
Hi,

you need two parameters: HANodeName & NodeAddress Zabbix Proxy isn't HA for now...

[(https://github.com/ansible-collections/community.zabbix/blob/c6df01d09d9d9f07352fa54217247c1ed48a7f87/roles/zabbix_server/templates/zabbix_server.conf.j2#L34)]

[https://github.com/ansible-collections/community.zabbix/blob/c6df01d09d9d9f07352fa54217247c1ed48a7f87/roles/zabbix_server/templates/zabbix_server.conf.j2#L54]

Other stuff is Proxy and Agent config.

**Comment by pyrodie18** [comment]
@damo2929 give that a try and let us know if you're still having issues.
